// Command gen-dns-providers generates strongly-typed DNS provider credential structs
// It reads the lego provider TOML descriptors and Go sources from the pinned module version, plus the hand-maintained provider-notes.yaml and provider-aliases.yaml, and emits:
//   - pkg/config/provider_<code>.go: one credentials struct per provider, with a newProvider method that builds the lego provider using strong types (no environment variables)
//   - pkg/config/dnsproviders_gen.go: the provider registry
//   - docs/content/dns-providers/<code>.md: one sample per provider plus _index.md
//
//nolint:forbidigo
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	toml "github.com/pelletier/go-toml/v2"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

const generatedHeader = "// Code generated by gen-dns-providers; DO NOT EDIT."

// legoModule is the lego module path whose providers are wrapped
const legoModule = "github.com/go-acme/lego/v5"

// notesPath is the hand-maintained file of extra documentation notes, relative to the module root
const notesPath = "tools/gen-dns-providers/provider-notes.yaml"

// aliasesPath is the hand-maintained file mapping DNS provider codes that lego has renamed to the code that replaces them, relative to the module root
const aliasesPath = "tools/gen-dns-providers/provider-aliases.yaml"

// unsupportedPath is the hand-maintained list of DNS provider codes that cannot be used with le-cert-server, relative to the module root
const unsupportedPath = "tools/gen-dns-providers/provider-unsupported.yaml"

// envVarRegexp matches valid environment-variable names
// Some lego TOMLs include descriptive prose as table keys, which we skip
var envVarRegexp = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// tomlConfig mirrors the parts of a lego provider TOML that we consume
type tomlConfig struct {
	Name          string
	Code          string
	URL           string
	Since         string
	Configuration struct {
		Credentials map[string]string
		Additional  map[string]string
	}
}

// mappedField is a credential field that maps onto a lego Config struct field
type mappedField struct {
	providerField
	// LegoField is the target field name on the lego Config struct
	LegoField string
	// Conv is the conversion kind: string, int, int32, int64, bool, duration, url, stringslice or pairs
	Conv string
}

// formatHint describes the expected shape of the value for conversions that are not a plain scalar
// It is empty when the value is passed through as-is, since the lego description already covers those
func (f mappedField) formatHint() string {
	switch f.Conv {
	case "stringslice":
		return "comma-separated list"
	case "pairs":
		return "comma-separated list of key:value pairs"
	default:
		return ""
	}
}

// provider is the resolved model for a single DNS provider
type provider struct {
	Code                    string
	Name                    string
	URL                     string
	Since                   string
	TypeName                string
	ImportPath              string
	Fields                  []mappedField
	DefaultConfigReturnsErr bool
	// Warnings lists the descriptor fields that could not be mapped onto a lego Config field
	Warnings []string
}

// needsStrconv reports whether the generated newProvider uses strconv
func (p provider) needsStrconv() bool {
	for _, f := range p.Fields {
		switch f.Conv {
		case "int", "int32", "int64", "bool", "duration":
			return true
		}
	}
	return false
}

// needsStrings reports whether the generated newProvider uses the strings package
func (p provider) needsStrings() bool {
	for _, f := range p.Fields {
		if f.Conv == "stringslice" {
			return true
		}
	}
	return false
}

// needsLegoEnv reports whether the generated newProvider uses lego's env package to parse a value
func (p provider) needsLegoEnv() bool {
	for _, f := range p.Fields {
		if f.Conv == "pairs" {
			return true
		}
	}
	return false
}

// needsTime reports whether the generated newProvider uses the time package
func (p provider) needsTime() bool {
	for _, f := range p.Fields {
		if f.Conv == "duration" {
			return true
		}
	}
	return false
}

// needsURL reports whether the generated newProvider uses net/url
func (p provider) needsURL() bool {
	for _, f := range p.Fields {
		if f.Conv == "url" {
			return true
		}
	}
	return false
}

func main() {
	err := run()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-dns-providers:", err)
		os.Exit(1)
	}
}

func run() error {
	legoDir, err := resolveLegoDir()
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Reading lego providers from '%s'\n", legoDir)

	tomls, err := filepath.Glob(filepath.Join(legoDir, "providers", "dns", "*", "*.toml"))
	if err != nil {
		return fmt.Errorf("failed to glob lego TOMLs: %w", err)
	}
	if len(tomls) == 0 {
		return fmt.Errorf("no provider TOMLs found under '%s'", legoDir)
	}

	providers := make([]provider, 0, len(tomls))
	var skipped []string
	for _, path := range tomls {
		p, ok, parseErr := parseProvider(path, legoDir)
		if parseErr != nil {
			return fmt.Errorf("failed to parse '%s': %w", path, parseErr)
		}
		if !ok {
			skipped = append(skipped, filepath.Base(filepath.Dir(path)))
			continue
		}
		providers = append(providers, p)
	}

	sort.Slice(providers, func(i, j int) bool {
		return providers[i].Code < providers[j].Code
	})

	// Providers that cannot be used are validated against the full set, then removed before anything is generated
	unsupported, err := loadUnsupportedProviders()
	if err != nil {
		return err
	}
	err = validateUnsupportedProviders(unsupported, providers)
	if err != nil {
		return err
	}
	providers = excludeUnsupported(providers, unsupported)

	aliases, err := loadProviderAliases()
	if err != nil {
		return err
	}
	err = validateProviderAliases(aliases, providers)
	if err != nil {
		return err
	}

	notes, err := loadProviderNotes()
	if err != nil {
		return err
	}
	warnUnknownNotes(notes, providers)
	reportProviderWarnings(providers, notes)

	configDir := filepath.Join("pkg", "config")
	docsDir := filepath.Join("docs", "content", "dns-providers")

	err = cleanGenerated(configDir, docsDir)
	if err != nil {
		return err
	}

	for _, p := range providers {
		err = writeProviderFile(configDir, p)
		if err != nil {
			return fmt.Errorf("failed to write provider file for '%s': %w", p.Code, err)
		}
		err = writeProviderDoc(docsDir, p, notes[p.Code])
		if err != nil {
			return fmt.Errorf("failed to write provider doc for '%s': %w", p.Code, err)
		}
	}

	err = writeRegistry(configDir, providers, aliases)
	if err != nil {
		return fmt.Errorf("failed to write registry: %w", err)
	}

	err = writeDocsIndex(docsDir, providers, aliases)
	if err != nil {
		return fmt.Errorf("failed to write docs index: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Generated %d DNS providers (skipped %d: %s), %d deprecated codes\n", len(providers), len(skipped), strings.Join(skipped, ", "), len(aliases))
	if len(unsupported) > 0 {
		fmt.Fprintf(os.Stderr, "Excluded %d unsupported DNS providers: %s\n", len(unsupported), strings.Join(unsupported, ", "))
	}
	return nil
}

// resolveLegoDir returns the local module cache directory for the pinned lego version
func resolveLegoDir() (string, error) {
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", legoModule)
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("failed to resolve lego module dir: %w", err)
	}
	dir := strings.TrimSpace(string(out))
	if dir == "" {
		return "", fmt.Errorf("lego module dir is empty, run 'go mod download %s'", legoModule)
	}
	return dir, nil
}

// parseProvider reads and normalizes a single provider TOML and analyzes its lego source
// The second return value is false when the provider should be skipped (e.g. no typed constructor)
func parseProvider(path string, legoDir string) (provider, bool, error) {
	data, err := os.ReadFile(path) //nolint:gosec
	if err != nil {
		return provider{}, false, err
	}

	var cfg tomlConfig
	err = toml.Unmarshal(data, &cfg)
	if err != nil {
		return provider{}, false, err
	}
	if cfg.Code == "" {
		return provider{}, false, fmt.Errorf("missing Code in '%s'", path)
	}

	dir := filepath.Dir(path)
	analysis, err := analyzeLego(dir, legoDir)
	if err != nil {
		return provider{}, false, err
	}
	if !analysis.hasConstructor {
		// Providers without a typed constructor (e.g. manual) cannot be configured without environment variables
		return provider{}, false, nil
	}

	descs := make(map[string]string)
	credKeys := sortedKeys(cfg.Configuration.Credentials, descs)
	addKeys := sortedKeys(cfg.Configuration.Additional, descs)
	fields := normalizeProvider(credKeys, addKeys, descs)

	mapped, warnings := mapFields(fields, analysis)

	return provider{
		Code:                    cfg.Code,
		Name:                    cfg.Name,
		URL:                     cfg.URL,
		Since:                   cfg.Since,
		TypeName:                typeName(cfg.Code),
		ImportPath:              legoModule + "/providers/dns/" + filepath.Base(dir),
		Fields:                  mapped,
		DefaultConfigReturnsErr: analysis.defaultConfigReturnsErr,
		Warnings:                warnings,
	}, true, nil
}

// mapFields resolves each normalized field onto a lego Config field using four strategies:
// the environment variable that lego assigns to a Config field, that same variable compared without its
// namespace prefix, then the Go field name, and finally the field name with additional segments stripped
// Fields that cannot be mapped to a supported type are dropped, and each dropped field is reported as a warning
func mapFields(fields []providerField, a legoAnalysis) ([]mappedField, []string) {
	mapped := make([]mappedField, 0, len(fields))
	var warnings []string

	// configFieldNames sorted for deterministic env-based matching
	cfgNames := make([]string, 0, len(a.configFields))
	for name := range a.configFields {
		cfgNames = append(cfgNames, name)
	}
	sort.Strings(cfgNames)

	// A few providers document their variables under a namespace that differs from the one their Go constants use (e.g. liquidweb declares LIQUID_WEB_ but its descriptor lists LWAPI_), so matching also happens on the suffix
	legoNS := commonEnvPrefix(mapValues(a.fieldEnv))
	tomlNS := commonEnvPrefix(fieldEnvVars(fields))

	for _, f := range fields {
		envSet := make(map[string]bool, 1+len(f.Aliases))
		envSet[f.EnvVar] = true
		for _, al := range f.Aliases {
			envSet[al] = true
		}

		target := ""
		// Strategy 1: a Config field that lego populates from one of this field's env vars
		for _, cf := range cfgNames {
			env := a.fieldEnv[cf]
			if env != "" && envSet[env] {
				target = cf
				break
			}
		}
		// Strategy 2: the same match, ignoring the namespace prefix on either side
		if target == "" && legoNS != "" && tomlNS != "" && legoNS != tomlNS {
			suffixSet := make(map[string]bool, len(envSet))
			for env := range envSet {
				suffixSet[strings.TrimPrefix(env, tomlNS)] = true
			}
			for _, cf := range cfgNames {
				env := a.fieldEnv[cf]
				if env != "" && strings.HasPrefix(env, legoNS) && suffixSet[strings.TrimPrefix(env, legoNS)] {
					target = cf
					break
				}
			}
		}
		// Strategy 3: a Config field whose Go name matches the normalized field name
		if target == "" {
			_, ok := a.configFields[f.GoName]
			if ok {
				target = f.GoName
			}
		}
		// Strategy 4: a Config field that matches after stripping additional leading segments
		// This handles providers with multi-word env namespaces (e.g. GOOGLE_DOMAINS_ACCESS_TOKEN -> AccessToken)
		if target == "" {
			segs := strings.Split(f.EnvVar, "_")
			for drop := 2; drop < len(segs); drop++ {
				cand, _ := buildName(strings.Join(segs[drop:], "_"), false)
				_, ok := a.configFields[cand]
				if ok {
					target = cand
					break
				}
			}
		}
		if target == "" {
			warnings = append(warnings, fmt.Sprintf("%s has no lego Config field, dropping", f.EnvVar))
			continue
		}

		conv := convFor(a.configFields[target])
		if conv == "" {
			// Report the unsupported types, but skip *http.Client since that is never settable from configuration
			if a.configFields[target] != "*http.Client" {
				warnings = append(warnings, fmt.Sprintf("%s maps to unsupported type %q, dropping", f.EnvVar, a.configFields[target]))
			}
			continue
		}

		mapped = append(mapped, mappedField{providerField: f, LegoField: target, Conv: conv})
	}

	return mapped, warnings
}

// mapValues returns the values of m
func mapValues(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for _, v := range m {
		out = append(out, v)
	}
	return out
}

// fieldEnvVars returns the environment variable of each field, including its aliases
func fieldEnvVars(fields []providerField) []string {
	out := make([]string, 0, len(fields))
	for _, f := range fields {
		out = append(out, f.EnvVar)
		out = append(out, f.Aliases...)
	}
	return out
}

// commonEnvPrefix returns the longest prefix shared by every environment variable in the list, truncated to a whole underscore-separated segment
// It returns an empty string when the list is empty or the names share no complete leading segment
func commonEnvPrefix(envs []string) string {
	if len(envs) == 0 {
		return ""
	}

	prefix := envs[0]
	for _, env := range envs[1:] {
		for !strings.HasPrefix(env, prefix) {
			prefix = prefix[:len(prefix)-1]
			if prefix == "" {
				return ""
			}
		}
	}

	// Keep only whole segments, so LIQUID_WEB_URL and LIQUID_WEB_USERNAME yield LIQUID_WEB_ rather than LIQUID_WEB_U
	idx := strings.LastIndex(prefix, "_")
	if idx < 0 {
		return ""
	}
	return prefix[:idx+1]
}

// convFor returns the conversion kind for a lego Config field type, or "" if unsupported
func convFor(typ string) string {
	switch typ {
	case "string":
		return "string"
	case "int":
		return "int"
	case "int32":
		return "int32"
	case "int64":
		return "int64"
	case "bool":
		return "bool"
	case "time.Duration":
		return "duration"
	case "*url.URL":
		return "url"
	case "[]string":
		return "stringslice"
	case "map[string]string":
		return "pairs"
	case "cloud.Configuration":
		// lego selects one of a few fixed Azure SDK cloud configurations from a name, which parseAzureEnvironment does too
		return "azureenv"
	default:
		return ""
	}
}

// sortedKeys returns the sorted env-var keys of m and records each description in descs
// Keys that are not valid environment-variable names (e.g. descriptive prose entries in the TOML) are skipped
func sortedKeys(m map[string]string, descs map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k, v := range m {
		if !envVarRegexp.MatchString(k) {
			continue
		}
		keys = append(keys, k)
		descs[k] = v
	}
	sort.Strings(keys)
	return keys
}

// typeName converts a lego provider code to a Go type name (e.g. "acme-dns" -> "AcmeDNSConfig")
func typeName(code string) string {
	parts := strings.FieldsFunc(code, func(r rune) bool {
		return r == '-' || r == '_'
	})
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(goToken(p))
	}
	return b.String() + "Config"
}

// fileSlug converts a lego provider code to a filename-safe slug
func fileSlug(code string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return r
		default:
			return '_'
		}
	}, code)
}

// cleanGenerated removes previously generated files so stale providers don't linger
func cleanGenerated(configDir string, docsDir string) error {
	patterns := []string{
		filepath.Join(configDir, "provider_*.go"),
		filepath.Join(configDir, "dnsproviders_gen.go"),
		filepath.Join(docsDir, "*.md"),
	}
	for _, pat := range patterns {
		matches, err := filepath.Glob(pat)
		if err != nil {
			return err
		}
		for _, m := range matches {
			err = os.Remove(m)
			if err != nil {
				return err
			}
		}
	}
	return os.MkdirAll(docsDir, 0o755)
}

// writeProviderFile generates pkg/config/provider_<code>.go
func writeProviderFile(configDir string, p provider) error {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n\n", generatedHeader)
	b.WriteString("package config\n\n")

	// Imports
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	if p.needsURL() {
		b.WriteString("\t\"net/url\"\n")
	}
	if p.needsStrconv() {
		b.WriteString("\t\"strconv\"\n")
	}
	if p.needsStrings() {
		b.WriteString("\t\"strings\"\n")
	}
	if p.needsTime() {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/go-acme/lego/v5/challenge\"\n")
	if p.needsLegoEnv() {
		fmt.Fprintf(&b, "\tlegoenv %q\n", legoModule+"/platform/env")
	}
	fmt.Fprintf(&b, "\tprov %q\n", p.ImportPath)
	b.WriteString("\tyaml \"sigs.k8s.io/yaml/goyaml.v3\"\n")
	b.WriteString(")\n\n")

	// Struct definition
	fmt.Fprintf(&b, "// %s holds configuration for the %q DNS provider", p.TypeName, p.Code)
	if p.Name != "" {
		fmt.Fprintf(&b, " (%s)", p.Name)
	}
	b.WriteString("\n")
	if p.URL != "" {
		fmt.Fprintf(&b, "// See %s\n", p.URL)
	}
	fmt.Fprintf(&b, "type %s struct {\n", p.TypeName)
	for _, f := range p.Fields {
		fmt.Fprintf(&b, "\t%s string // %s: %s\n", f.GoName, f.EnvVar, fieldComment(f))
	}
	b.WriteString("}\n\n")

	// newProvider method
	fmt.Fprintf(&b, "// newProvider builds the lego DNS challenge provider using strong types\n")
	fmt.Fprintf(&b, "// Credentials are passed directly to lego and never written to the process environment\n")
	fmt.Fprintf(&b, "func (c *%s) newProvider() (challenge.Provider, error) {\n", p.TypeName)
	if p.DefaultConfigReturnsErr {
		b.WriteString("\tcfg, err := prov.NewDefaultConfig()\n")
		b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	} else {
		b.WriteString("\tcfg := prov.NewDefaultConfig()\n")
	}
	for _, f := range p.Fields {
		writeFieldAssignment(&b, f)
	}
	b.WriteString("\treturn prov.NewDNSProviderConfig(cfg)\n")
	b.WriteString("}\n\n")

	// UnmarshalYAML method
	writeUnmarshal(&b, p)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt failed: %w\n%s", err, b.String())
	}

	name := filepath.Join(configDir, "provider_"+fileSlug(p.Code)+".go")
	return os.WriteFile(name, src, 0o644) //nolint:gosec
}

// fieldComment returns the single-line description used for a field, with the value format appended when it is not a plain scalar
func fieldComment(f mappedField) string {
	desc := oneLine(f.Desc)
	hint := f.formatHint()
	if hint == "" {
		return desc
	}
	if desc == "" {
		return hint
	}
	return desc + " (" + hint + ")"
}

// writeFieldAssignment emits the code that copies a populated field onto the lego Config
func writeFieldAssignment(b *bytes.Buffer, f mappedField) {
	fmt.Fprintf(b, "\tif c.%s != \"\" {\n", f.GoName)
	switch f.Conv {
	case "string":
		fmt.Fprintf(b, "\t\tcfg.%s = c.%s\n", f.LegoField, f.GoName)
	case "int":
		fmt.Fprintf(b, "\t\tv, err := strconv.Atoi(c.%s)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = v\n", f.LegoField)
	case "int64":
		fmt.Fprintf(b, "\t\tv, err := strconv.ParseInt(c.%s, 10, 64)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = v\n", f.LegoField)
	case "bool":
		fmt.Fprintf(b, "\t\tv, err := strconv.ParseBool(c.%s)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = v\n", f.LegoField)
	case "duration":
		// lego interprets these values as a number of seconds
		fmt.Fprintf(b, "\t\tv, err := strconv.Atoi(c.%s)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = time.Duration(v) * time.Second\n", f.LegoField)
	case "url":
		fmt.Fprintf(b, "\t\tv, err := url.Parse(c.%s)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = v\n", f.LegoField)
	case "int32":
		fmt.Fprintf(b, "\t\tv, err := strconv.ParseInt(c.%s, 10, 32)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = int32(v)\n", f.LegoField)
	case "stringslice":
		// lego reads these from a single comma-separated environment variable
		fmt.Fprintf(b, "\t\tcfg.%s = strings.Split(c.%s, \",\")\n", f.LegoField, f.GoName)
	case "pairs":
		// lego parses these from a comma-separated list of key:value pairs, so the same parser is reused here
		fmt.Fprintf(b, "\t\tv, err := legoenv.ParsePairs(c.%s)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = v\n", f.LegoField)
	case "azureenv":
		// parseAzureEnvironment is hand-written in pkg/config, since the mapping from a cloud name to an Azure SDK configuration cannot be derived from lego's sources
		fmt.Fprintf(b, "\t\tv, err := parseAzureEnvironment(c.%s)\n", f.GoName)
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn nil, fmt.Errorf(\"invalid value for \\\"%s\\\": %%w\", err)\n\t\t}\n", f.YAMLName)
		fmt.Fprintf(b, "\t\tcfg.%s = v\n", f.LegoField)
	}
	b.WriteString("\t}\n")
}

// writeUnmarshal emits the strict UnmarshalYAML method
func writeUnmarshal(b *bytes.Buffer, p provider) {
	fmt.Fprintf(b, "// UnmarshalYAML decodes the provider credentials\n")
	fmt.Fprintf(b, "// It accepts the normalized name, the raw lego environment variable, and documented aliases\n")
	fmt.Fprintf(b, "func (c *%s) UnmarshalYAML(value *yaml.Node) error {\n", p.TypeName)
	b.WriteString("\tif value.Kind != yaml.MappingNode {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"dnsCredentials for DNS provider \\\"%s\\\" must be a map\")\n", p.Code)
	b.WriteString("\t}\n")
	b.WriteString("\tfor i := 0; i+1 < len(value.Content); i += 2 {\n")
	b.WriteString("\t\tvar key string\n")
	b.WriteString("\t\terr := value.Content[i].Decode(&key)\n")
	b.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	b.WriteString("\t\tvar val string\n")
	b.WriteString("\t\terr = value.Content[i+1].Decode(&val)\n")
	b.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	b.WriteString("\t\tswitch key {\n")

	seen := make(map[string]bool)
	for _, f := range p.Fields {
		labels := make([]string, 0, 3)
		for _, k := range f.acceptedKeys() {
			if seen[k] {
				continue
			}
			seen[k] = true
			labels = append(labels, fmt.Sprintf("%q", k))
		}
		if len(labels) == 0 {
			continue
		}
		fmt.Fprintf(b, "\t\tcase %s:\n\t\t\tc.%s = val\n", strings.Join(labels, ", "), f.GoName)
	}

	b.WriteString("\t\tdefault:\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"unknown credential key %%q for DNS provider \\\"%s\\\"\", key)\n", p.Code)
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n}\n")
}

// writeRegistry generates pkg/config/dnsproviders_gen.go
func writeRegistry(configDir string, providers []provider, aliases map[string]string) error {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n\n", generatedHeader)
	b.WriteString("package config\n\n")
	b.WriteString("import \"github.com/go-acme/lego/v5/challenge\"\n\n")
	b.WriteString("// dnsProviderConfig is implemented by every generated per-provider credentials struct\n")
	b.WriteString("type dnsProviderConfig interface {\n")
	b.WriteString("\t// newProvider builds the lego DNS challenge provider using strong types\n")
	b.WriteString("\tnewProvider() (challenge.Provider, error)\n")
	b.WriteString("}\n\n")
	b.WriteString("// newDNSProviderConfig returns an empty credentials struct for the given lego provider code\n")
	b.WriteString("// The second return value is false when the code is not a supported lego DNS provider\n")
	b.WriteString("func newDNSProviderConfig(code string) (dnsProviderConfig, bool) {\n")
	b.WriteString("\tswitch code {\n")
	for _, p := range providers {
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn &%s{}, true\n", p.Code, p.TypeName)
	}
	b.WriteString("\tdefault:\n\t\treturn nil, false\n\t}\n}\n")

	b.WriteString("\n// currentDNSProviderCode maps a DNS provider code that lego has renamed to the code that replaces it\n")
	b.WriteString("// Renamed codes remain accepted so that configuration files written for an older lego version keep loading, and each replacement takes the same credential keys\n")
	b.WriteString("// The second return value reports whether the code was renamed\n")
	b.WriteString("func currentDNSProviderCode(code string) (string, bool) {\n")
	if len(aliases) == 0 {
		b.WriteString("\treturn code, false\n}\n")
	} else {
		b.WriteString("\tswitch code {\n")
		for _, code := range sortedMapKeys(aliases) {
			fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %q, true\n", code, aliases[code])
		}
		b.WriteString("\tdefault:\n\t\treturn code, false\n\t}\n}\n")
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt failed: %w\n%s", err, b.String())
	}

	return os.WriteFile(filepath.Join(configDir, "dnsproviders_gen.go"), src, 0o644) //nolint:gosec
}

// loadProviderNotes reads the hand-maintained per-provider documentation notes
func loadProviderNotes() (map[string]string, error) {
	notes := make(map[string]string)
	data, err := os.ReadFile(notesPath) //nolint:gosec
	if errors.Is(err, fs.ErrNotExist) {
		// A missing file is not an error, it just means no extra notes
		return notes, nil
	} else if err != nil {
		return nil, err
	}

	err = yaml.Unmarshal(data, &notes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse '%s': %w", notesPath, err)
	}

	return notes, nil
}

// reportProviderWarnings prints the descriptor fields that could not be mapped onto a lego Config field
// A provider with an entry in provider-notes.yaml is reported as a note, because the note is how the gap is acknowledged and explained to users
// Anything still reported as a warning either needs a note or needs the generator taught how to map it
func reportProviderWarnings(providers []provider, notes map[string]string) {
	for _, p := range providers {
		if len(p.Warnings) == 0 {
			continue
		}
		label := "warn"
		if notes[p.Code] != "" {
			label = "note"
		}
		for _, w := range p.Warnings {
			fmt.Fprintf(os.Stderr, "  %s: [%s] %s\n", label, p.Code, w)
		}
	}
}

// warnUnknownNotes prints a warning for any note keyed to a provider that does not exist
// This catches typos in provider-notes.yaml
func warnUnknownNotes(notes map[string]string, providers []provider) {
	known := make(map[string]bool, len(providers))
	for _, p := range providers {
		known[p.Code] = true
	}
	for _, code := range sortedMapKeys(notes) {
		if !known[code] {
			fmt.Fprintf(os.Stderr, "  warn: provider-notes.yaml has a note for unknown provider %q\n", code)
		}
	}
}

// loadProviderAliases reads the hand-maintained map of DNS provider codes that lego has renamed
func loadProviderAliases() (map[string]string, error) {
	aliases := make(map[string]string)
	data, err := os.ReadFile(aliasesPath) //nolint:gosec
	if errors.Is(err, fs.ErrNotExist) {
		// A missing file is not an error, it just means no provider has been renamed
		return aliases, nil
	} else if err != nil {
		return nil, err
	}

	err = yaml.Unmarshal(data, &aliases)
	if err != nil {
		return nil, fmt.Errorf("failed to parse '%s': %w", aliasesPath, err)
	}

	return aliases, nil
}

// loadUnsupportedProviders reads the hand-maintained list of DNS provider codes that are excluded from generation
// The codes are returned sorted, so the run summary does not churn
func loadUnsupportedProviders() ([]string, error) {
	var codes []string
	data, err := os.ReadFile(unsupportedPath) //nolint:gosec
	if errors.Is(err, fs.ErrNotExist) {
		// A missing file is not an error, it just means every lego provider is generated
		return codes, nil
	} else if err != nil {
		return nil, err
	}

	err = yaml.Unmarshal(data, &codes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse '%s': %w", unsupportedPath, err)
	}

	sort.Strings(codes)
	return codes, nil
}

// validateUnsupportedProviders checks provider-unsupported.yaml against the providers found in lego
// A code that lego does not have is a hard error, so a typo or a provider lego has renamed or removed shows up rather than quietly excluding nothing
func validateUnsupportedProviders(unsupported []string, providers []provider) error {
	known := make(map[string]bool, len(providers))
	for _, p := range providers {
		known[p.Code] = true
	}

	seen := make(map[string]bool, len(unsupported))
	for _, code := range unsupported {
		switch {
		case code == "":
			return fmt.Errorf("provider-unsupported.yaml has an empty entry")
		case seen[code]:
			return fmt.Errorf("provider-unsupported.yaml lists %q more than once", code)
		case !known[code]:
			return fmt.Errorf("provider-unsupported.yaml lists %q, which is not a known lego provider - remove the entry", code)
		}
		seen[code] = true
	}

	return nil
}

// excludeUnsupported returns the providers that are not listed in provider-unsupported.yaml
func excludeUnsupported(providers []provider, unsupported []string) []provider {
	if len(unsupported) == 0 {
		return providers
	}

	excluded := make(map[string]bool, len(unsupported))
	for _, code := range unsupported {
		excluded[code] = true
	}

	kept := make([]provider, 0, len(providers))
	for _, p := range providers {
		if excluded[p.Code] {
			continue
		}
		kept = append(kept, p)
	}
	return kept
}

// sortedMapKeys returns the keys of m in a stable order so the generated output does not churn
func sortedMapKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// validateProviderAliases checks provider-aliases.yaml against the providers found in lego
// A code that lego has reintroduced, or one pointing at a provider that no longer exists, is a hard error rather than a silently broken mapping
func validateProviderAliases(aliases map[string]string, providers []provider) error {
	known := make(map[string]bool, len(providers))
	for _, p := range providers {
		known[p.Code] = true
	}

	for _, code := range sortedMapKeys(aliases) {
		current := aliases[code]
		switch {
		case current == "":
			return fmt.Errorf("provider-aliases.yaml maps deprecated code %q to an empty value", code)
		case known[code]:
			return fmt.Errorf("provider-aliases.yaml lists %q as deprecated, but it is a current lego provider - remove the entry", code)
		case !known[current]:
			return fmt.Errorf("provider-aliases.yaml maps deprecated code %q to %q, which is not a known lego provider", code, current)
		}
	}

	return nil
}

// writeProviderDoc generates docs/content/dns-providers/<code>.md
// note is optional extra Markdown appended to the page
func writeProviderDoc(docsDir string, p provider, note string) error {
	var b strings.Builder

	title := p.Name
	if title == "" {
		title = p.Code
	}

	fmt.Fprintf(&b, "---\ntitle: %q\nnav_title: %q\n---\n\n", title, title)
	fmt.Fprintf(&b, "<!-- Code generated by gen-dns-providers; DO NOT EDIT. -->\n\n")

	if p.URL != "" && strings.HasPrefix(p.URL, "http") {
		fmt.Fprintf(&b, "Configuration for the [%s](%s) DNS provider.\n\n", title, p.URL)
	} else {
		fmt.Fprintf(&b, "Configuration for the %s DNS provider.\n\n", title)
	}
	fmt.Fprintf(&b, "See the [lego documentation](https://go-acme.github.io/lego/dns/%s/) for full details.\n\n", p.Code)

	b.WriteString("```yaml\n")
	b.WriteString("letsEncrypt:\n")
	fmt.Fprintf(&b, "  dnsProvider: %q\n", p.Code)
	if len(p.Fields) == 0 {
		b.WriteString("  # This provider requires no credentials in the config file\n")
	} else {
		b.WriteString("  dnsCredentials:\n")
		for _, f := range p.Fields {
			fmt.Fprintf(&b, "    # %s: %s\n", f.EnvVar, fieldComment(f))
			fmt.Fprintf(&b, "    %s: \"\"\n", f.YAMLName)
		}
	}
	b.WriteString("```\n\n")

	hasAlias := false
	for _, f := range p.Fields {
		if len(f.Aliases) > 0 {
			hasAlias = true
			break
		}
	}
	b.WriteString("Credentials are passed directly to lego using strong types and are never written to the process environment.\n")
	b.WriteString("You may also use the raw lego environment-variable names")
	if hasAlias {
		b.WriteString(" (and documented aliases)")
	}
	b.WriteString(" as keys instead of the normalized names.\n")

	// Append any hand-maintained note for this provider
	note = strings.TrimRight(note, "\n")
	if note != "" {
		b.WriteString("\n")
		b.WriteString(note)
		b.WriteString("\n")
	}

	name := filepath.Join(docsDir, p.Code+".md")
	return os.WriteFile(name, []byte(b.String()), 0o644) //nolint:gosec
}

// writeDocsIndex generates docs/content/dns-providers/_index.md
func writeDocsIndex(docsDir string, providers []provider, aliases map[string]string) error {
	var b strings.Builder

	b.WriteString("---\ntitle: \"DNS Providers\"\nnav_title: \"DNS Providers\"\nweight: 30\n---\n\n")
	b.WriteString("<!-- Code generated by gen-dns-providers; DO NOT EDIT. -->\n\n")
	b.WriteString("le-cert-server supports the DNS providers from the [lego](https://go-acme.github.io/lego/dns/) library.\n")
	b.WriteString("Credentials are configured under `letsEncrypt.dnsCredentials` using the normalized keys shown on each provider's page, or the raw lego environment-variable names.\n")
	b.WriteString("They are passed to lego using strong types and are never written to the process environment.\n\n")
	b.WriteString("> **Note:** A few providers load their credentials through a third-party cloud SDK (for example AWS Route53/Lightsail, Google Cloud DNS, Azure DNS, Oracle Cloud, and OpenStack Designate).\n")
	b.WriteString("> For those, the SDK discovers credentials from its own environment variables, shared credentials files, or instance metadata: only the non-secret options are listed on the provider page.\n\n")
	b.WriteString("## Supported providers\n\n")

	for _, p := range providers {
		title := p.Name
		if title == "" {
			title = p.Code
		}
		fmt.Fprintf(&b, "- [%s](/dns-providers/%s)\n", title, p.Code)
	}

	if len(aliases) > 0 {
		b.WriteString("\n## Renamed providers\n\n")
		b.WriteString("lego has renamed the providers below. The old code is still accepted in `letsEncrypt.dnsProvider` and is mapped to the current one automatically, using the same credential keys.\n")
		b.WriteString("| Old code | Current code |\n| --- | --- |\n")
		for _, code := range sortedMapKeys(aliases) {
			current := aliases[code]
			fmt.Fprintf(&b, "| `%s` | [`%s`](/dns-providers/%s) |\n", code, current, current)
		}
	}

	return os.WriteFile(filepath.Join(docsDir, "_index.md"), []byte(b.String()), 0o644) //nolint:gosec
}

// oneLine collapses any whitespace runs in a description to single spaces
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// ---- lego source analysis ----

// legoAnalysis holds the facts extracted from a provider's Go source
type legoAnalysis struct {
	hasConstructor bool
	// defaultConfigReturnsErr is true when NewDefaultConfig returns (*Config, error) rather than *Config
	defaultConfigReturnsErr bool
	// configFields maps a lego Config struct field name to its type string
	configFields map[string]string
	// fieldEnv maps a lego Config field name to the environment variable lego reads it from
	fieldEnv map[string]string
}

// analyzeLego parses the Go sources of a lego provider package
// legoDir is the lego module root, used to follow Config type aliases into internal packages
func analyzeLego(dir string, legoDir string) (legoAnalysis, error) {
	a := legoAnalysis{
		configFields: make(map[string]string),
		fieldEnv:     make(map[string]string),
	}

	files, err := parseDir(dir)
	if err != nil {
		return a, err
	}

	// Resolve string-valued constants (env var names use the EnvXxx naming convention)
	consts := resolveStringConsts(files)
	imports := collectImports(files)

	// Collect the Config struct fields
	// The Config type may be an alias into an internal package
	aliasPath := ""
	aliasSel := ""
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Name.Name != "Config" {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if ok {
					addStructFields(st, a.configFields)
					continue
				}
				sel, ok := ts.Type.(*ast.SelectorExpr)
				if ok {
					pid, ok := sel.X.(*ast.Ident)
					if ok {
						aliasPath = imports[pid.Name]
						aliasSel = sel.Sel.Name
					}
				}
			}
		}
	}

	// Follow a Config alias into the referenced (internal) lego package
	if len(a.configFields) == 0 && aliasPath != "" && strings.HasPrefix(aliasPath, legoModule) {
		rel := strings.TrimPrefix(aliasPath, legoModule)
		targetFiles, terr := parseDir(filepath.Join(legoDir, filepath.FromSlash(rel)))
		if terr == nil {
			collectNamedStruct(targetFiles, aliasSel, a.configFields)
		}
	}

	for _, f := range files {
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			switch fd.Name.Name {
			case "NewDNSProviderConfig":
				a.hasConstructor = true
			case "NewDefaultConfig":
				if fd.Type.Results != nil && fd.Type.Results.NumFields() > 1 {
					a.defaultConfigReturnsErr = true
				}
				collectFieldEnv(fd, consts, a.configFields, a.fieldEnv)
			case "NewDNSProvider":
				collectFieldEnv(fd, consts, a.configFields, a.fieldEnv)
			}
		}
	}

	return a, nil
}

// parseDir parses all non-test Go files in a directory
func parseDir(dir string) ([]*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	files := make([]*ast.File, 0, len(entries))
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, perr := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0)
		if perr != nil {
			return nil, perr
		}
		files = append(files, f)
	}
	return files, nil
}

// collectImports maps the local name of each import to its path
func collectImports(files []*ast.File) map[string]string {
	out := make(map[string]string)
	for _, f := range files {
		for _, imp := range f.Imports {
			path, err := strconv.Unquote(imp.Path.Value)
			if err != nil {
				continue
			}
			name := ""
			if imp.Name != nil {
				name = imp.Name.Name
			} else {
				name = path[strings.LastIndex(path, "/")+1:]
			}
			out[name] = path
		}
	}
	return out
}

// collectNamedStruct records the exported fields of the named struct type
func collectNamedStruct(files []*ast.File, structName string, out map[string]string) {
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Name.Name != structName {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if ok {
					addStructFields(st, out)
				}
			}
		}
	}
}

// addStructFields records the exported fields of a struct and their type strings
func addStructFields(st *ast.StructType, out map[string]string) {
	for _, field := range st.Fields.List {
		typ := exprTypeString(field.Type)
		for _, name := range field.Names {
			if name.IsExported() {
				out[name.Name] = typ
			}
		}
	}
}

// resolveStringConsts builds a map of constant name to its string value
// It runs a few passes so constants defined in terms of other constants resolve
func resolveStringConsts(files []*ast.File) map[string]string {
	consts := make(map[string]string)
	for range 4 {
		for _, f := range files {
			for _, decl := range f.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.CONST {
					continue
				}
				for _, spec := range gd.Specs {
					vs, ok := spec.(*ast.ValueSpec)
					if !ok || len(vs.Names) != 1 || len(vs.Values) != 1 {
						continue
					}
					v, ok := foldString(vs.Values[0], consts)
					if ok {
						consts[vs.Names[0].Name] = v
					}
				}
			}
		}
	}
	return consts
}

// foldString evaluates a constant string expression using already-known constants
func foldString(expr ast.Expr, consts map[string]string) (string, bool) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.STRING {
			return "", false
		}
		s, err := strconv.Unquote(e.Value)
		if err != nil {
			return "", false
		}
		return s, true
	case *ast.Ident:
		v, ok := consts[e.Name]
		return v, ok
	case *ast.BinaryExpr:
		if e.Op != token.ADD {
			return "", false
		}
		l, lok := foldString(e.X, consts)
		r, rok := foldString(e.Y, consts)
		if lok && rok {
			return l + r, true
		}
		return "", false
	default:
		return "", false
	}
}

// exprTypeString renders a type expression to a comparable string
func exprTypeString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		x, ok := e.X.(*ast.Ident)
		if ok {
			return x.Name + "." + e.Sel.Name
		}
		return e.Sel.Name
	case *ast.StarExpr:
		return "*" + exprTypeString(e.X)
	case *ast.ArrayType:
		return "[]" + exprTypeString(e.Elt)
	case *ast.MapType:
		return "map[" + exprTypeString(e.Key) + "]" + exprTypeString(e.Value)
	default:
		return ""
	}
}

// collectFieldEnv inspects a constructor for assignments of a Config field from an env constant
func collectFieldEnv(d *ast.FuncDecl, consts map[string]string, configFields map[string]string, out map[string]string) {
	// lego often reads an env var into a local variable first, then assigns that local onto the Config field
	// Resolving the locals up front keeps the link between the field and its env var
	locals := collectLocalEnv(d, consts)

	record := func(field string, valueExpr ast.Expr) {
		_, ok := configFields[field]
		if !ok {
			return
		}
		_, ok = out[field]
		if ok {
			return
		}
		env := firstEnvConst(valueExpr, consts)
		if env == "" {
			env = firstLocalEnv(valueExpr, locals)
		}
		if env != "" {
			out[field] = env
		}
	}

	ast.Inspect(d.Body, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.AssignStmt:
			for i, lhs := range node.Lhs {
				sel, ok := lhs.(*ast.SelectorExpr)
				if !ok || i >= len(node.Rhs) {
					continue
				}
				record(sel.Sel.Name, node.Rhs[i])
			}
		case *ast.KeyValueExpr:
			key, ok := node.Key.(*ast.Ident)
			if ok {
				record(key.Name, node.Value)
			}
		}
		return true
	})
}

// collectLocalEnv maps each local variable in a constructor to the env var it is assigned from
// Only single-name assignments are considered, so a variable holding an error or an unrelated value is never recorded
func collectLocalEnv(d *ast.FuncDecl, consts map[string]string) map[string]string {
	locals := make(map[string]string)

	ast.Inspect(d.Body, func(n ast.Node) bool {
		assign, ok := n.(*ast.AssignStmt)
		if !ok {
			return true
		}
		for i, lhs := range assign.Lhs {
			id, ok := lhs.(*ast.Ident)
			if !ok || id.Name == "_" || i >= len(assign.Rhs) {
				continue
			}
			_, ok = locals[id.Name]
			if ok {
				continue
			}
			env := firstEnvConst(assign.Rhs[i], consts)
			if env != "" {
				locals[id.Name] = env
			}
		}
		return true
	})

	return locals
}

// firstLocalEnv returns the env var behind the first known local variable referenced in an expression
func firstLocalEnv(expr ast.Expr, locals map[string]string) string {
	found := ""
	ast.Inspect(expr, func(n ast.Node) bool {
		if found != "" {
			return false
		}
		id, ok := n.(*ast.Ident)
		if !ok {
			return true
		}
		env, ok := locals[id.Name]
		if ok {
			found = env
			return false
		}
		return true
	})
	return found
}

// firstEnvConst returns the value of the first EnvXxx constant referenced in an expression
func firstEnvConst(expr ast.Expr, consts map[string]string) string {
	found := ""
	ast.Inspect(expr, func(n ast.Node) bool {
		if found != "" {
			return false
		}
		id, ok := n.(*ast.Ident)
		if !ok {
			return true
		}
		if !strings.HasPrefix(id.Name, "Env") {
			return true
		}
		v, ok := consts[id.Name]
		if ok && envVarRegexp.MatchString(v) {
			found = v
			return false
		}
		return true
	})
	return found
}
