// Command gen-dns-providers generates strongly-typed DNS provider credential structs
// It reads the lego provider TOML descriptors from the pinned module version and emits:
//   - pkg/config/provider_<code>.go: one credentials struct per provider
//   - pkg/config/dnsproviders_gen.go: the provider registry
//   - docs/content/dns-providers/<code>.md: one sample per provider plus _index.md
//
//nolint:forbidigo
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	toml "github.com/pelletier/go-toml/v2"
)

const generatedHeader = "// Code generated by gen-dns-providers; DO NOT EDIT."

// envVarRegexp matches valid environment-variable names
// Some lego TOMLs include descriptive prose as table keys, which we skip
var envVarRegexp = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// legoModule is the lego module path whose TOMLs are parsed
const legoModule = "github.com/go-acme/lego/v4"

// tomlConfig mirrors the parts of a lego provider TOML that we consume
type tomlConfig struct {
	Name          string
	Code          string
	URL           string
	Since         string
	Configuration struct {
		Credentials map[string]string
		Additional  map[string]string
	}
}

// provider is the resolved model for a single DNS provider
type provider struct {
	Code     string
	Name     string
	URL      string
	Since    string
	TypeName string
	Fields   []providerField
}

func main() {
	err := run()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-dns-providers:", err)
		os.Exit(1)
	}
}

func run() error {
	legoDir, err := resolveLegoDir()
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Reading lego provider TOMLs from '%s'\n", legoDir)

	tomls, err := filepath.Glob(filepath.Join(legoDir, "providers", "dns", "*", "*.toml"))
	if err != nil {
		return fmt.Errorf("failed to glob lego TOMLs: %w", err)
	}
	if len(tomls) == 0 {
		return fmt.Errorf("no provider TOMLs found under '%s'", legoDir)
	}

	providers := make([]provider, 0, len(tomls))
	for _, path := range tomls {
		p, parseErr := parseProvider(path)
		if parseErr != nil {
			return fmt.Errorf("failed to parse '%s': %w", path, parseErr)
		}
		providers = append(providers, p)
	}

	sort.Slice(providers, func(i, j int) bool {
		return providers[i].Code < providers[j].Code
	})

	configDir := filepath.Join("pkg", "config")
	docsDir := filepath.Join("docs", "content", "dns-providers")

	err = cleanGenerated(configDir, docsDir)
	if err != nil {
		return err
	}

	for _, p := range providers {
		err = writeProviderFile(configDir, p)
		if err != nil {
			return fmt.Errorf("failed to write provider file for '%s': %w", p.Code, err)
		}
		err = writeProviderDoc(docsDir, p)
		if err != nil {
			return fmt.Errorf("failed to write provider doc for '%s': %w", p.Code, err)
		}
	}

	err = writeRegistry(configDir, providers)
	if err != nil {
		return fmt.Errorf("failed to write registry: %w", err)
	}

	err = writeDocsIndex(docsDir, providers)
	if err != nil {
		return fmt.Errorf("failed to write docs index: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Generated %d DNS providers\n", len(providers))
	return nil
}

// resolveLegoDir returns the local module cache directory for the pinned lego version
func resolveLegoDir() (string, error) {
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", legoModule)
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("failed to resolve lego module dir: %w", err)
	}
	dir := strings.TrimSpace(string(out))
	if dir == "" {
		return "", fmt.Errorf("lego module dir is empty; run 'go mod download %s'", legoModule)
	}
	return dir, nil
}

// parseProvider reads and normalizes a single provider TOML
func parseProvider(path string) (provider, error) {
	data, err := os.ReadFile(path) //nolint:gosec
	if err != nil {
		return provider{}, err
	}

	var cfg tomlConfig
	err = toml.Unmarshal(data, &cfg)
	if err != nil {
		return provider{}, err
	}

	if cfg.Code == "" {
		return provider{}, fmt.Errorf("missing Code in '%s'", path)
	}

	descs := make(map[string]string)
	credKeys := sortedKeys(cfg.Configuration.Credentials, descs)
	addKeys := sortedKeys(cfg.Configuration.Additional, descs)

	return provider{
		Code:     cfg.Code,
		Name:     cfg.Name,
		URL:      cfg.URL,
		Since:    cfg.Since,
		TypeName: typeName(cfg.Code),
		Fields:   normalizeProvider(credKeys, addKeys, descs),
	}, nil
}

// sortedKeys returns the sorted env-var keys of m and records each description in descs
// Keys that are not valid environment-variable names (e.g. descriptive prose entries in the TOML) are skipped
func sortedKeys(m map[string]string, descs map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k, v := range m {
		if !envVarRegexp.MatchString(k) {
			continue
		}
		keys = append(keys, k)
		descs[k] = v
	}
	sort.Strings(keys)
	return keys
}

// typeName converts a lego provider code to a Go type name (e.g. "acme-dns" -> "AcmeDNSConfig")
func typeName(code string) string {
	parts := strings.FieldsFunc(code, func(r rune) bool {
		return r == '-' || r == '_'
	})
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(goToken(p))
	}
	return b.String() + "Config"
}

// fileSlug converts a lego provider code to a filename-safe slug
func fileSlug(code string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return r
		default:
			return '_'
		}
	}, code)
}

// cleanGenerated removes previously generated files so stale providers don't linger
func cleanGenerated(configDir string, docsDir string) error {
	patterns := []string{
		filepath.Join(configDir, "provider_*.go"),
		filepath.Join(configDir, "dnsproviders_gen.go"),
		filepath.Join(docsDir, "*.md"),
	}
	for _, pat := range patterns {
		matches, err := filepath.Glob(pat)
		if err != nil {
			return err
		}
		for _, m := range matches {
			err = os.Remove(m)
			if err != nil {
				return err
			}
		}
	}
	return os.MkdirAll(docsDir, 0o755)
}

// writeProviderFile generates pkg/config/provider_<code>.go
func writeProviderFile(configDir string, p provider) error {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n\n", generatedHeader)
	b.WriteString("package config\n\n")
	b.WriteString("import (\n\t\"fmt\"\n\n\tyaml \"sigs.k8s.io/yaml/goyaml.v3\"\n)\n\n")

	// Struct definition
	fmt.Fprintf(&b, "// %s holds configuration for the %q DNS provider", p.TypeName, p.Code)
	if p.Name != "" {
		fmt.Fprintf(&b, " (%s)", p.Name)
	}
	b.WriteString("\n")
	if p.URL != "" {
		fmt.Fprintf(&b, "// See %s\n", p.URL)
	}
	fmt.Fprintf(&b, "type %s struct {\n", p.TypeName)
	for _, f := range p.Fields {
		fmt.Fprintf(&b, "\t%s string // %s: %s\n", f.GoName, f.EnvVar, oneLine(f.Desc))
	}
	b.WriteString("}\n\n")

	// envVars method
	fmt.Fprintf(&b, "// envVars returns the lego environment variables for the populated (non-empty) fields\n")
	fmt.Fprintf(&b, "func (c *%s) envVars() map[string]string {\n", p.TypeName)
	fmt.Fprintf(&b, "\tm := make(map[string]string, %d)\n", len(p.Fields))
	for _, f := range p.Fields {
		fmt.Fprintf(&b, "\tif c.%s != \"\" {\n\t\tm[%q] = c.%s\n\t}\n", f.GoName, f.EnvVar, f.GoName)
	}
	b.WriteString("\treturn m\n}\n\n")

	// UnmarshalYAML method
	fmt.Fprintf(&b, "// UnmarshalYAML decodes the provider credentials\n")
	fmt.Fprintf(&b, "// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error\n")
	fmt.Fprintf(&b, "func (c *%s) UnmarshalYAML(value *yaml.Node) error {\n", p.TypeName)
	b.WriteString("\tif value.Kind != yaml.MappingNode {\n")
	fmt.Fprintf(&b, "\t\treturn fmt.Errorf(\"dnsCredentials for DNS provider \\\"%s\\\" must be a map\")\n", p.Code)
	b.WriteString("\t}\n")
	b.WriteString("\tfor i := 0; i+1 < len(value.Content); i += 2 {\n")
	b.WriteString("\t\tvar key string\n")
	b.WriteString("\t\terr := value.Content[i].Decode(&key)\n")
	b.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	b.WriteString("\t\tvar val string\n")
	b.WriteString("\t\terr = value.Content[i+1].Decode(&val)\n")
	b.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	b.WriteString("\t\tswitch key {\n")

	seen := make(map[string]bool)
	for _, f := range p.Fields {
		labels := make([]string, 0, 3)
		for _, k := range f.acceptedKeys() {
			if seen[k] {
				continue
			}
			seen[k] = true
			labels = append(labels, fmt.Sprintf("%q", k))
		}
		if len(labels) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t\tcase %s:\n\t\t\tc.%s = val\n", strings.Join(labels, ", "), f.GoName)
	}

	b.WriteString("\t\tdefault:\n")
	fmt.Fprintf(&b, "\t\t\treturn fmt.Errorf(\"unknown credential key %%q for DNS provider \\\"%s\\\"\", key)\n", p.Code)
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt failed: %w\n%s", err, b.String())
	}

	name := filepath.Join(configDir, "provider_"+fileSlug(p.Code)+".go")
	return os.WriteFile(name, src, 0o644) //nolint:gosec
}

// writeRegistry generates pkg/config/dnsproviders_gen.go
func writeRegistry(configDir string, providers []provider) error {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n\n", generatedHeader)
	b.WriteString("package config\n\n")
	b.WriteString("// dnsProviderConfig is implemented by every generated per-provider credentials struct\n")
	b.WriteString("type dnsProviderConfig interface {\n\tenvVars() map[string]string\n}\n\n")
	b.WriteString("// newDNSProviderConfig returns an empty credentials struct for the given lego provider code\n")
	b.WriteString("// The second return value is false when the code is not a known lego DNS provider\n")
	b.WriteString("func newDNSProviderConfig(code string) (dnsProviderConfig, bool) {\n")
	b.WriteString("\tswitch code {\n")
	for _, p := range providers {
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn &%s{}, true\n", p.Code, p.TypeName)
	}
	b.WriteString("\tdefault:\n\t\treturn nil, false\n\t}\n}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt failed: %w\n%s", err, b.String())
	}

	return os.WriteFile(filepath.Join(configDir, "dnsproviders_gen.go"), src, 0o644) //nolint:gosec
}

// writeProviderDoc generates docs/content/dns-providers/<code>.md
func writeProviderDoc(docsDir string, p provider) error {
	var b strings.Builder

	title := p.Name
	if title == "" {
		title = p.Code
	}

	fmt.Fprintf(&b, "---\ntitle: %q\nnav_title: %q\n---\n\n", title, title)
	fmt.Fprintf(&b, "<!-- Code generated by gen-dns-providers; DO NOT EDIT. -->\n\n")

	if p.URL != "" && strings.HasPrefix(p.URL, "http") {
		fmt.Fprintf(&b, "Configuration for the [%s](%s) DNS provider.\n\n", title, p.URL)
	} else {
		fmt.Fprintf(&b, "Configuration for the %s DNS provider.\n\n", title)
	}
	fmt.Fprintf(&b, "See the [lego documentation](https://go-acme.github.io/lego/dns/%s/) for full details.\n\n", p.Code)

	b.WriteString("```yaml\n")
	b.WriteString("letsEncrypt:\n")
	fmt.Fprintf(&b, "  dnsProvider: %q\n", p.Code)
	if len(p.Fields) == 0 {
		b.WriteString("  # This provider requires no credentials in the config file\n")
	} else {
		b.WriteString("  dnsCredentials:\n")
		for _, f := range p.Fields {
			fmt.Fprintf(&b, "    # %s: %s\n", f.EnvVar, oneLine(f.Desc))
			fmt.Fprintf(&b, "    %s: \"\"\n", f.YAMLName)
		}
	}
	b.WriteString("```\n\n")

	b.WriteString("You may also use the raw lego environment-variable names")
	hasAlias := false
	for _, f := range p.Fields {
		if len(f.Aliases) > 0 {
			hasAlias = true
			break
		}
	}
	if hasAlias {
		b.WriteString(" (and documented aliases)")
	}
	b.WriteString(" as keys instead of the normalized names.\n")
	b.WriteString("Credentials may also be supplied directly as system environment variables, in which case `dnsCredentials` can be omitted.\n")

	name := filepath.Join(docsDir, p.Code+".md")
	return os.WriteFile(name, []byte(b.String()), 0o644) //nolint:gosec
}

// writeDocsIndex generates docs/content/dns-providers/_index.md
func writeDocsIndex(docsDir string, providers []provider) error {
	var b strings.Builder

	b.WriteString("---\ntitle: \"DNS Providers\"\nnav_title: \"DNS Providers\"\nweight: 30\n---\n\n")
	b.WriteString("<!-- Code generated by gen-dns-providers; DO NOT EDIT. -->\n\n")
	b.WriteString("le-cert-server supports all DNS providers supported by the [lego](https://go-acme.github.io/lego/dns/) library.\n")
	b.WriteString("Credentials are configured under `letsEncrypt.dnsCredentials` using the normalized keys shown on each provider's page, or the raw lego environment-variable names.\n\n")
	b.WriteString("## Supported providers\n\n")

	for _, p := range providers {
		title := p.Name
		if title == "" {
			title = p.Code
		}
		fmt.Fprintf(&b, "- [%s](/dns-providers/%s)\n", title, p.Code)
	}

	return os.WriteFile(filepath.Join(docsDir, "_index.md"), []byte(b.String()), 0o644) //nolint:gosec
}

// oneLine collapses any whitespace runs in a description to single spaces
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
