// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// CloudxnsConfig holds configuration for the "cloudxns" DNS provider (CloudXNS (Deprecated))
// See https://github.com/go-acme/lego/issues/2323
type CloudxnsConfig struct {
	APIKey             string // CLOUDXNS_API_KEY: The API key
	SecretKey          string // CLOUDXNS_SECRET_KEY: The API secret key
	HTTPTimeout        string // CLOUDXNS_HTTP_TIMEOUT: API request timeout in seconds (Default: )
	PollingInterval    string // CLOUDXNS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: )
	PropagationTimeout string // CLOUDXNS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: )
	TTL                string // CLOUDXNS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: )
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *CloudxnsConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["CLOUDXNS_API_KEY"] = c.APIKey
	}
	if c.SecretKey != "" {
		m["CLOUDXNS_SECRET_KEY"] = c.SecretKey
	}
	if c.HTTPTimeout != "" {
		m["CLOUDXNS_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["CLOUDXNS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["CLOUDXNS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["CLOUDXNS_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *CloudxnsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"cloudxns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "CLOUDXNS_API_KEY":
			c.APIKey = val
		case "secretKey", "CLOUDXNS_SECRET_KEY":
			c.SecretKey = val
		case "httpTimeout", "CLOUDXNS_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "CLOUDXNS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CLOUDXNS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "CLOUDXNS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"cloudxns\"", key)
		}
	}
	return nil
}
