// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/active24"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Active24Config holds configuration for the "active24" DNS provider (Active24)
// See https://www.active24.cz
type Active24Config struct {
	APIKey             string // ACTIVE24_API_KEY: API key
	Secret             string // ACTIVE24_SECRET: Secret
	PollingInterval    string // ACTIVE24_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // ACTIVE24_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // ACTIVE24_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *Active24Config) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.Secret != "" {
		cfg.Secret = c.Secret
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Active24Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"active24\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "ACTIVE24_API_KEY":
			c.APIKey = val
		case "secret", "ACTIVE24_SECRET":
			c.Secret = val
		case "pollingInterval", "ACTIVE24_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "ACTIVE24_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "ACTIVE24_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"active24\"", key)
		}
	}
	return nil
}
