// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// RackspaceConfig holds configuration for the "rackspace" DNS provider (Rackspace)
// See https://www.rackspace.com/
type RackspaceConfig struct {
	APIKey             string // RACKSPACE_API_KEY: API key
	User               string // RACKSPACE_USER: API user
	HTTPTimeout        string // RACKSPACE_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // RACKSPACE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 3)
	PropagationTimeout string // RACKSPACE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // RACKSPACE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *RackspaceConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["RACKSPACE_API_KEY"] = c.APIKey
	}
	if c.User != "" {
		m["RACKSPACE_USER"] = c.User
	}
	if c.HTTPTimeout != "" {
		m["RACKSPACE_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["RACKSPACE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["RACKSPACE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["RACKSPACE_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *RackspaceConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"rackspace\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "RACKSPACE_API_KEY":
			c.APIKey = val
		case "user", "RACKSPACE_USER":
			c.User = val
		case "httpTimeout", "RACKSPACE_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "RACKSPACE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "RACKSPACE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "RACKSPACE_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"rackspace\"", key)
		}
	}
	return nil
}
