// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// HostingerConfig holds configuration for the "hostinger" DNS provider (Hostinger)
// See https://www.hostinger.com/
type HostingerConfig struct {
	APIToken           string // HOSTINGER_API_TOKEN: API Token
	HTTPTimeout        string // HOSTINGER_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // HOSTINGER_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // HOSTINGER_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // HOSTINGER_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *HostingerConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.APIToken != "" {
		m["HOSTINGER_API_TOKEN"] = c.APIToken
	}
	if c.HTTPTimeout != "" {
		m["HOSTINGER_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["HOSTINGER_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["HOSTINGER_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["HOSTINGER_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *HostingerConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"hostinger\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiToken", "HOSTINGER_API_TOKEN":
			c.APIToken = val
		case "httpTimeout", "HOSTINGER_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "HOSTINGER_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "HOSTINGER_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "HOSTINGER_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"hostinger\"", key)
		}
	}
	return nil
}
