// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/loopia"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// LoopiaConfig holds configuration for the "loopia" DNS provider (Loopia)
// See https://loopia.com
type LoopiaConfig struct {
	APIPassword        string // LOOPIA_API_PASSWORD: API password
	APIUser            string // LOOPIA_API_USER: API username
	APIURL             string // LOOPIA_API_URL: API endpoint. Ex: https://api.loopia.se/RPCSERV or https://api.loopia.rs/RPCSERV
	PollingInterval    string // LOOPIA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2400)
	PropagationTimeout string // LOOPIA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // LOOPIA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *LoopiaConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIPassword != "" {
		cfg.APIPassword = c.APIPassword
	}
	if c.APIUser != "" {
		cfg.APIUser = c.APIUser
	}
	if c.APIURL != "" {
		cfg.BaseURL = c.APIURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *LoopiaConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"loopia\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiPassword", "LOOPIA_API_PASSWORD":
			c.APIPassword = val
		case "apiUser", "LOOPIA_API_USER":
			c.APIUser = val
		case "apiURL", "LOOPIA_API_URL":
			c.APIURL = val
		case "pollingInterval", "LOOPIA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "LOOPIA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "LOOPIA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"loopia\"", key)
		}
	}
	return nil
}
