// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// MythicbeastsConfig holds configuration for the "mythicbeasts" DNS provider (MythicBeasts)
// See https://www.mythic-beasts.com/
type MythicbeastsConfig struct {
	Password           string // MYTHICBEASTS_PASSWORD: Password
	Username           string // MYTHICBEASTS_USERNAME: User name
	APIEndpoint        string // MYTHICBEASTS_API_ENDPOINT: The endpoint for the API (must implement v2)
	AuthAPIEndpoint    string // MYTHICBEASTS_AUTH_API_ENDPOINT: The endpoint for Mythic Beasts' Authentication
	HTTPTimeout        string // MYTHICBEASTS_HTTP_TIMEOUT: API request timeout in seconds (Default: 10)
	PollingInterval    string // MYTHICBEASTS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // MYTHICBEASTS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // MYTHICBEASTS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *MythicbeastsConfig) envVars() map[string]string {
	m := make(map[string]string, 8)
	if c.Password != "" {
		m["MYTHICBEASTS_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["MYTHICBEASTS_USERNAME"] = c.Username
	}
	if c.APIEndpoint != "" {
		m["MYTHICBEASTS_API_ENDPOINT"] = c.APIEndpoint
	}
	if c.AuthAPIEndpoint != "" {
		m["MYTHICBEASTS_AUTH_API_ENDPOINT"] = c.AuthAPIEndpoint
	}
	if c.HTTPTimeout != "" {
		m["MYTHICBEASTS_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["MYTHICBEASTS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["MYTHICBEASTS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["MYTHICBEASTS_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *MythicbeastsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"mythicbeasts\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "MYTHICBEASTS_PASSWORD":
			c.Password = val
		case "username", "MYTHICBEASTS_USERNAME":
			c.Username = val
		case "apiEndpoint", "MYTHICBEASTS_API_ENDPOINT":
			c.APIEndpoint = val
		case "authAPIEndpoint", "MYTHICBEASTS_AUTH_API_ENDPOINT":
			c.AuthAPIEndpoint = val
		case "httpTimeout", "MYTHICBEASTS_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "MYTHICBEASTS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "MYTHICBEASTS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "MYTHICBEASTS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"mythicbeasts\"", key)
		}
	}
	return nil
}
