// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// HetznerConfig holds configuration for the "hetzner" DNS provider (Hetzner)
// See https://hetzner.com
type HetznerConfig struct {
	APIToken           string // HETZNER_API_TOKEN: API token
	HTTPTimeout        string // HETZNER_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // HETZNER_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // HETZNER_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // HETZNER_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *HetznerConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.APIToken != "" {
		m["HETZNER_API_TOKEN"] = c.APIToken
	}
	if c.HTTPTimeout != "" {
		m["HETZNER_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["HETZNER_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["HETZNER_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["HETZNER_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *HetznerConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"hetzner\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiToken", "HETZNER_API_TOKEN":
			c.APIToken = val
		case "httpTimeout", "HETZNER_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "HETZNER_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "HETZNER_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "HETZNER_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"hetzner\"", key)
		}
	}
	return nil
}
