// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// ShellrentConfig holds configuration for the "shellrent" DNS provider (Shellrent)
// See https://www.shellrent.com/
type ShellrentConfig struct {
	Token              string // SHELLRENT_TOKEN: Token
	Username           string // SHELLRENT_USERNAME: Username
	HTTPTimeout        string // SHELLRENT_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // SHELLRENT_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // SHELLRENT_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 300)
	TTL                string // SHELLRENT_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 3600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *ShellrentConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.Token != "" {
		m["SHELLRENT_TOKEN"] = c.Token
	}
	if c.Username != "" {
		m["SHELLRENT_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["SHELLRENT_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["SHELLRENT_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["SHELLRENT_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["SHELLRENT_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *ShellrentConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"shellrent\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "SHELLRENT_TOKEN":
			c.Token = val
		case "username", "SHELLRENT_USERNAME":
			c.Username = val
		case "httpTimeout", "SHELLRENT_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "SHELLRENT_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "SHELLRENT_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "SHELLRENT_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"shellrent\"", key)
		}
	}
	return nil
}
