// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// IwantmynameConfig holds configuration for the "iwantmyname" DNS provider (iwantmyname (Deprecated))
// See https://iwantmyname.com
type IwantmynameConfig struct {
	Password           string // IWANTMYNAME_PASSWORD: API password
	Username           string // IWANTMYNAME_USERNAME: API username
	HTTPTimeout        string // IWANTMYNAME_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // IWANTMYNAME_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // IWANTMYNAME_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // IWANTMYNAME_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *IwantmynameConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.Password != "" {
		m["IWANTMYNAME_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["IWANTMYNAME_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["IWANTMYNAME_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["IWANTMYNAME_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["IWANTMYNAME_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["IWANTMYNAME_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *IwantmynameConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"iwantmyname\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "IWANTMYNAME_PASSWORD":
			c.Password = val
		case "username", "IWANTMYNAME_USERNAME":
			c.Username = val
		case "httpTimeout", "IWANTMYNAME_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "IWANTMYNAME_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "IWANTMYNAME_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "IWANTMYNAME_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"iwantmyname\"", key)
		}
	}
	return nil
}
