// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/ucloud"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// UcloudConfig holds configuration for the "ucloud" DNS provider (UCloud)
// See https://www.ucloud.cn/
type UcloudConfig struct {
	PrivateKey         string // UCLOUD_PRIVATE_KEY: Private key
	PublicKey          string // UCLOUD_PUBLIC_KEY: Public key
	HTTPTimeout        string // UCLOUD_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // UCLOUD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	ProjectID          string // UCLOUD_PROJECT_ID: Project ID
	PropagationTimeout string // UCLOUD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	Region             string // UCLOUD_REGION: Region
	TTL                string // UCLOUD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *UcloudConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.PrivateKey != "" {
		cfg.PrivateKey = c.PrivateKey
	}
	if c.PublicKey != "" {
		cfg.PublicKey = c.PublicKey
	}
	if c.HTTPTimeout != "" {
		v, err := strconv.Atoi(c.HTTPTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"httpTimeout\": %w", err)
		}
		cfg.HTTPTimeout = time.Duration(v) * time.Second
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.ProjectID != "" {
		cfg.ProjectID = c.ProjectID
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.Region != "" {
		cfg.Region = c.Region
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *UcloudConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"ucloud\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "privateKey", "UCLOUD_PRIVATE_KEY":
			c.PrivateKey = val
		case "publicKey", "UCLOUD_PUBLIC_KEY":
			c.PublicKey = val
		case "httpTimeout", "UCLOUD_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "UCLOUD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "projectID", "UCLOUD_PROJECT_ID":
			c.ProjectID = val
		case "propagationTimeout", "UCLOUD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "region", "UCLOUD_REGION":
			c.Region = val
		case "ttl", "UCLOUD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"ucloud\"", key)
		}
	}
	return nil
}
