// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// MyaddrConfig holds configuration for the "myaddr" DNS provider (myaddr.{tools,dev,io})
// See https://myaddr.tools/
type MyaddrConfig struct {
	PrivateKeysMapping string // MYADDR_PRIVATE_KEYS_MAPPING: Mapping between subdomains and private keys. The format is: `<subdomain1>:<private_key1>,<subdomain2>:<private_key2>,<subdomain3>:<private_key3>`
	HTTPTimeout        string // MYADDR_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // MYADDR_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // MYADDR_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SequenceInterval   string // MYADDR_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 2)
	TTL                string // MYADDR_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *MyaddrConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.PrivateKeysMapping != "" {
		m["MYADDR_PRIVATE_KEYS_MAPPING"] = c.PrivateKeysMapping
	}
	if c.HTTPTimeout != "" {
		m["MYADDR_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["MYADDR_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["MYADDR_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SequenceInterval != "" {
		m["MYADDR_SEQUENCE_INTERVAL"] = c.SequenceInterval
	}
	if c.TTL != "" {
		m["MYADDR_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *MyaddrConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"myaddr\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "privateKeysMapping", "MYADDR_PRIVATE_KEYS_MAPPING":
			c.PrivateKeysMapping = val
		case "httpTimeout", "MYADDR_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "MYADDR_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "MYADDR_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "MYADDR_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "MYADDR_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"myaddr\"", key)
		}
	}
	return nil
}
