// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/tencentcloud"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// TencentcloudConfig holds configuration for the "tencentcloud" DNS provider (Tencent Cloud DNS)
// See https://cloud.tencent.com/product/dns
type TencentcloudConfig struct {
	SecretID           string // TENCENTCLOUD_SECRET_ID: Access key ID
	SecretKey          string // TENCENTCLOUD_SECRET_KEY: Access Key secret
	HTTPTimeout        string // TENCENTCLOUD_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // TENCENTCLOUD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // TENCENTCLOUD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	Region             string // TENCENTCLOUD_REGION: Region
	SessionToken       string // TENCENTCLOUD_SESSION_TOKEN: Access Key token
	TTL                string // TENCENTCLOUD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *TencentcloudConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.SecretID != "" {
		cfg.SecretID = c.SecretID
	}
	if c.SecretKey != "" {
		cfg.SecretKey = c.SecretKey
	}
	if c.HTTPTimeout != "" {
		v, err := strconv.Atoi(c.HTTPTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"httpTimeout\": %w", err)
		}
		cfg.HTTPTimeout = time.Duration(v) * time.Second
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.Region != "" {
		cfg.Region = c.Region
	}
	if c.SessionToken != "" {
		cfg.SessionToken = c.SessionToken
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *TencentcloudConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"tencentcloud\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "secretID", "TENCENTCLOUD_SECRET_ID":
			c.SecretID = val
		case "secretKey", "TENCENTCLOUD_SECRET_KEY":
			c.SecretKey = val
		case "httpTimeout", "TENCENTCLOUD_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "TENCENTCLOUD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "TENCENTCLOUD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "region", "TENCENTCLOUD_REGION":
			c.Region = val
		case "sessionToken", "TENCENTCLOUD_SESSION_TOKEN":
			c.SessionToken = val
		case "ttl", "TENCENTCLOUD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"tencentcloud\"", key)
		}
	}
	return nil
}
