// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// BindmanConfig holds configuration for the "bindman" DNS provider (Bindman)
// See https://github.com/labbsr0x/bindman-dns-webhook
type BindmanConfig struct {
	ManagerAddress     string // BINDMAN_MANAGER_ADDRESS: The server URL, should have scheme, hostname, and port (if required) of the Bindman-DNS Manager server
	HTTPTimeout        string // BINDMAN_HTTP_TIMEOUT: API request timeout in seconds (Default: 60)
	PollingInterval    string // BINDMAN_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // BINDMAN_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *BindmanConfig) envVars() map[string]string {
	m := make(map[string]string, 4)
	if c.ManagerAddress != "" {
		m["BINDMAN_MANAGER_ADDRESS"] = c.ManagerAddress
	}
	if c.HTTPTimeout != "" {
		m["BINDMAN_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["BINDMAN_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["BINDMAN_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *BindmanConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"bindman\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "managerAddress", "BINDMAN_MANAGER_ADDRESS":
			c.ManagerAddress = val
		case "httpTimeout", "BINDMAN_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "BINDMAN_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "BINDMAN_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"bindman\"", key)
		}
	}
	return nil
}
