// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/allinkl"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AllinklConfig holds configuration for the "allinkl" DNS provider (all-inkl)
// See https://all-inkl.com
type AllinklConfig struct {
	InklLogin              string // ALL_INKL_LOGIN: KAS login
	InklPassword           string // ALL_INKL_PASSWORD: KAS password
	InklPollingInterval    string // ALL_INKL_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	InklPropagationTimeout string // ALL_INKL_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *AllinklConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.InklLogin != "" {
		cfg.Login = c.InklLogin
	}
	if c.InklPassword != "" {
		cfg.Password = c.InklPassword
	}
	if c.InklPollingInterval != "" {
		v, err := strconv.Atoi(c.InklPollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"inklPollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.InklPropagationTimeout != "" {
		v, err := strconv.Atoi(c.InklPropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"inklPropagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AllinklConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"allinkl\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "inklLogin", "ALL_INKL_LOGIN":
			c.InklLogin = val
		case "inklPassword", "ALL_INKL_PASSWORD":
			c.InklPassword = val
		case "inklPollingInterval", "ALL_INKL_POLLING_INTERVAL":
			c.InklPollingInterval = val
		case "inklPropagationTimeout", "ALL_INKL_PROPAGATION_TIMEOUT":
			c.InklPropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"allinkl\"", key)
		}
	}
	return nil
}
