// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/route53"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Route53Config holds configuration for the "route53" DNS provider (Amazon Route 53)
// See https://aws.amazon.com/route53/
type Route53Config struct {
	AccessKeyID              string // AWS_ACCESS_KEY_ID: Managed by the AWS client. Access key ID (`AWS_ACCESS_KEY_ID_FILE` is not supported, use `AWS_SHARED_CREDENTIALS_FILE` instead)
	AssumeRoleARN            string // AWS_ASSUME_ROLE_ARN: Managed by the AWS Role ARN (`AWS_ASSUME_ROLE_ARN_FILE` is not supported)
	ExternalID               string // AWS_EXTERNAL_ID: Managed by STS AssumeRole API operation (`AWS_EXTERNAL_ID_FILE` is not supported)
	HostedZoneID             string // AWS_HOSTED_ZONE_ID: Override the hosted zone ID.
	Region                   string // AWS_REGION: Managed by the AWS client (`AWS_REGION_FILE` is not supported)
	SecretAccessKey          string // AWS_SECRET_ACCESS_KEY: Managed by the AWS client. Secret access key (`AWS_SECRET_ACCESS_KEY_FILE` is not supported, use `AWS_SHARED_CREDENTIALS_FILE` instead)
	WaitForRecordSetsChanged string // AWS_WAIT_FOR_RECORD_SETS_CHANGED: Wait for changes to be INSYNC (it can be unstable)
	MaxRetries               string // AWS_MAX_RETRIES: The number of maximum returns the service will use to make an individual API request
	PollingInterval          string // AWS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 4)
	PrivateZone              string // AWS_PRIVATE_ZONE: Set to true to use private zones only (default: use public zones only)
	PropagationTimeout       string // AWS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                      string // AWS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 10)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *Route53Config) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.AccessKeyID != "" {
		cfg.AccessKeyID = c.AccessKeyID
	}
	if c.AssumeRoleARN != "" {
		cfg.AssumeRoleArn = c.AssumeRoleARN
	}
	if c.ExternalID != "" {
		cfg.ExternalID = c.ExternalID
	}
	if c.HostedZoneID != "" {
		cfg.HostedZoneID = c.HostedZoneID
	}
	if c.Region != "" {
		cfg.Region = c.Region
	}
	if c.SecretAccessKey != "" {
		cfg.SecretAccessKey = c.SecretAccessKey
	}
	if c.WaitForRecordSetsChanged != "" {
		v, err := strconv.ParseBool(c.WaitForRecordSetsChanged)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"waitForRecordSetsChanged\": %w", err)
		}
		cfg.WaitForRecordSetsChanged = v
	}
	if c.MaxRetries != "" {
		v, err := strconv.Atoi(c.MaxRetries)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"maxRetries\": %w", err)
		}
		cfg.MaxRetries = v
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PrivateZone != "" {
		v, err := strconv.ParseBool(c.PrivateZone)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"privateZone\": %w", err)
		}
		cfg.PrivateZone = v
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Route53Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"route53\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessKeyID", "AWS_ACCESS_KEY_ID":
			c.AccessKeyID = val
		case "assumeRoleARN", "AWS_ASSUME_ROLE_ARN":
			c.AssumeRoleARN = val
		case "externalID", "AWS_EXTERNAL_ID":
			c.ExternalID = val
		case "hostedZoneID", "AWS_HOSTED_ZONE_ID":
			c.HostedZoneID = val
		case "region", "AWS_REGION":
			c.Region = val
		case "secretAccessKey", "AWS_SECRET_ACCESS_KEY":
			c.SecretAccessKey = val
		case "waitForRecordSetsChanged", "AWS_WAIT_FOR_RECORD_SETS_CHANGED":
			c.WaitForRecordSetsChanged = val
		case "maxRetries", "AWS_MAX_RETRIES":
			c.MaxRetries = val
		case "pollingInterval", "AWS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "privateZone", "AWS_PRIVATE_ZONE":
			c.PrivateZone = val
		case "propagationTimeout", "AWS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "AWS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"route53\"", key)
		}
	}
	return nil
}
