// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/efficientip"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// EfficientipConfig holds configuration for the "efficientip" DNS provider (Efficient IP)
// See https://efficientip.com/
type EfficientipConfig struct {
	DNSName            string // EFFICIENTIP_DNS_NAME: DNS name (ex: dns.smart)
	Hostname           string // EFFICIENTIP_HOSTNAME: Hostname (ex: foo.example.com)
	Password           string // EFFICIENTIP_PASSWORD: Password
	Username           string // EFFICIENTIP_USERNAME: Username
	InsecureSkipVerify string // EFFICIENTIP_INSECURE_SKIP_VERIFY: Whether or not to verify EfficientIP API certificate
	PollingInterval    string // EFFICIENTIP_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // EFFICIENTIP_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	ViewName           string // EFFICIENTIP_VIEW_NAME: View name (ex: external)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *EfficientipConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.DNSName != "" {
		cfg.DNSName = c.DNSName
	}
	if c.Hostname != "" {
		cfg.Hostname = c.Hostname
	}
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.InsecureSkipVerify != "" {
		v, err := strconv.ParseBool(c.InsecureSkipVerify)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"insecureSkipVerify\": %w", err)
		}
		cfg.InsecureSkipVerify = v
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.ViewName != "" {
		cfg.ViewName = c.ViewName
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *EfficientipConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"efficientip\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "dnsName", "EFFICIENTIP_DNS_NAME":
			c.DNSName = val
		case "hostname", "EFFICIENTIP_HOSTNAME":
			c.Hostname = val
		case "password", "EFFICIENTIP_PASSWORD":
			c.Password = val
		case "username", "EFFICIENTIP_USERNAME":
			c.Username = val
		case "insecureSkipVerify", "EFFICIENTIP_INSECURE_SKIP_VERIFY":
			c.InsecureSkipVerify = val
		case "pollingInterval", "EFFICIENTIP_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "EFFICIENTIP_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "viewName", "EFFICIENTIP_VIEW_NAME":
			c.ViewName = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"efficientip\"", key)
		}
	}
	return nil
}
