// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AzureConfig holds configuration for the "azure" DNS provider (Azure (deprecated))
// See https://azure.microsoft.com/services/dns/
type AzureConfig struct {
	ClientID           string // AZURE_CLIENT_ID: Client ID
	ClientSecret       string // AZURE_CLIENT_SECRET: Client secret
	Environment        string // AZURE_ENVIRONMENT: Azure environment, one of: public, usgovernment, german, and china
	ResourceGroup      string // AZURE_RESOURCE_GROUP: Resource group
	SubscriptionID     string // AZURE_SUBSCRIPTION_ID: Subscription ID
	TenantID           string // AZURE_TENANT_ID: Tenant ID
	MetadataEndpoint   string // AZURE_METADATA_ENDPOINT: Metadata Service endpoint URL
	PollingInterval    string // AZURE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PrivateZone        string // AZURE_PRIVATE_ZONE: Set to true to use Azure Private DNS Zones and not public
	PropagationTimeout string // AZURE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // AZURE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)
	ZoneName           string // AZURE_ZONE_NAME: Zone name to use inside Azure DNS service to add the TXT record in
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *AzureConfig) envVars() map[string]string {
	m := make(map[string]string, 12)
	if c.ClientID != "" {
		m["AZURE_CLIENT_ID"] = c.ClientID
	}
	if c.ClientSecret != "" {
		m["AZURE_CLIENT_SECRET"] = c.ClientSecret
	}
	if c.Environment != "" {
		m["AZURE_ENVIRONMENT"] = c.Environment
	}
	if c.ResourceGroup != "" {
		m["AZURE_RESOURCE_GROUP"] = c.ResourceGroup
	}
	if c.SubscriptionID != "" {
		m["AZURE_SUBSCRIPTION_ID"] = c.SubscriptionID
	}
	if c.TenantID != "" {
		m["AZURE_TENANT_ID"] = c.TenantID
	}
	if c.MetadataEndpoint != "" {
		m["AZURE_METADATA_ENDPOINT"] = c.MetadataEndpoint
	}
	if c.PollingInterval != "" {
		m["AZURE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PrivateZone != "" {
		m["AZURE_PRIVATE_ZONE"] = c.PrivateZone
	}
	if c.PropagationTimeout != "" {
		m["AZURE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["AZURE_TTL"] = c.TTL
	}
	if c.ZoneName != "" {
		m["AZURE_ZONE_NAME"] = c.ZoneName
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AzureConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"azure\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "clientID", "AZURE_CLIENT_ID":
			c.ClientID = val
		case "clientSecret", "AZURE_CLIENT_SECRET":
			c.ClientSecret = val
		case "environment", "AZURE_ENVIRONMENT":
			c.Environment = val
		case "resourceGroup", "AZURE_RESOURCE_GROUP":
			c.ResourceGroup = val
		case "subscriptionID", "AZURE_SUBSCRIPTION_ID":
			c.SubscriptionID = val
		case "tenantID", "AZURE_TENANT_ID":
			c.TenantID = val
		case "metadataEndpoint", "AZURE_METADATA_ENDPOINT":
			c.MetadataEndpoint = val
		case "pollingInterval", "AZURE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "privateZone", "AZURE_PRIVATE_ZONE":
			c.PrivateZone = val
		case "propagationTimeout", "AZURE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "AZURE_TTL":
			c.TTL = val
		case "zoneName", "AZURE_ZONE_NAME":
			c.ZoneName = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"azure\"", key)
		}
	}
	return nil
}
