// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Active24Config holds configuration for the "active24" DNS provider (Active24)
// See https://www.active24.cz
type Active24Config struct {
	APIKey             string // ACTIVE24_API_KEY: API key
	Secret             string // ACTIVE24_SECRET: Secret
	HTTPTimeout        string // ACTIVE24_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // ACTIVE24_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // ACTIVE24_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // ACTIVE24_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *Active24Config) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["ACTIVE24_API_KEY"] = c.APIKey
	}
	if c.Secret != "" {
		m["ACTIVE24_SECRET"] = c.Secret
	}
	if c.HTTPTimeout != "" {
		m["ACTIVE24_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["ACTIVE24_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["ACTIVE24_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["ACTIVE24_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Active24Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"active24\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "ACTIVE24_API_KEY":
			c.APIKey = val
		case "secret", "ACTIVE24_SECRET":
			c.Secret = val
		case "httpTimeout", "ACTIVE24_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "ACTIVE24_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "ACTIVE24_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "ACTIVE24_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"active24\"", key)
		}
	}
	return nil
}
