// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// BegetConfig holds configuration for the "beget" DNS provider (Beget.com)
// See https://beget.com/
type BegetConfig struct {
	Password           string // BEGET_PASSWORD: API password
	Username           string // BEGET_USERNAME: API username
	HTTPTimeout        string // BEGET_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // BEGET_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 30)
	PropagationTimeout string // BEGET_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 300)
	TTL                string // BEGET_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *BegetConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.Password != "" {
		m["BEGET_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["BEGET_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["BEGET_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["BEGET_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["BEGET_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["BEGET_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *BegetConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"beget\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "BEGET_PASSWORD":
			c.Password = val
		case "username", "BEGET_USERNAME":
			c.Username = val
		case "httpTimeout", "BEGET_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "BEGET_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "BEGET_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "BEGET_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"beget\"", key)
		}
	}
	return nil
}
