// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/infoblox"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// InfobloxConfig holds configuration for the "infoblox" DNS provider (Infoblox)
// See https://www.infoblox.com/
type InfobloxConfig struct {
	Host               string // INFOBLOX_HOST: Host URI
	Password           string // INFOBLOX_PASSWORD: Account Password
	Username           string // INFOBLOX_USERNAME: Account Username
	CACertificate      string // INFOBLOX_CA_CERTIFICATE: The path to the CA certificate (PEM encoded)
	DNSView            string // INFOBLOX_DNS_VIEW: The view for the TXT records (Default: External)
	HTTPTimeout        string // INFOBLOX_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // INFOBLOX_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	Port               string // INFOBLOX_PORT: The port for the infoblox grid manager (Default: 443)
	PropagationTimeout string // INFOBLOX_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SSLVerify          string // INFOBLOX_SSL_VERIFY: Whether or not to verify the TLS certificate (Default: true)
	TTL                string // INFOBLOX_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
	WAPIVersion        string // INFOBLOX_WAPI_VERSION: The version of WAPI being used (Default: 2.11)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *InfobloxConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Host != "" {
		cfg.Host = c.Host
	}
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.CACertificate != "" {
		cfg.CACertificate = c.CACertificate
	}
	if c.DNSView != "" {
		cfg.DNSView = c.DNSView
	}
	if c.HTTPTimeout != "" {
		v, err := strconv.Atoi(c.HTTPTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"httpTimeout\": %w", err)
		}
		cfg.HTTPTimeout = v
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.Port != "" {
		cfg.Port = c.Port
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.SSLVerify != "" {
		v, err := strconv.ParseBool(c.SSLVerify)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"sslVerify\": %w", err)
		}
		cfg.SSLVerify = v
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	if c.WAPIVersion != "" {
		cfg.WapiVersion = c.WAPIVersion
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *InfobloxConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"infoblox\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "host", "INFOBLOX_HOST":
			c.Host = val
		case "password", "INFOBLOX_PASSWORD":
			c.Password = val
		case "username", "INFOBLOX_USERNAME":
			c.Username = val
		case "caCertificate", "INFOBLOX_CA_CERTIFICATE":
			c.CACertificate = val
		case "dnsView", "INFOBLOX_DNS_VIEW":
			c.DNSView = val
		case "httpTimeout", "INFOBLOX_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "INFOBLOX_POLLING_INTERVAL":
			c.PollingInterval = val
		case "port", "INFOBLOX_PORT":
			c.Port = val
		case "propagationTimeout", "INFOBLOX_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sslVerify", "INFOBLOX_SSL_VERIFY":
			c.SSLVerify = val
		case "ttl", "INFOBLOX_TTL":
			c.TTL = val
		case "wapiVersion", "INFOBLOX_WAPI_VERSION":
			c.WAPIVersion = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"infoblox\"", key)
		}
	}
	return nil
}
