// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/aliesa"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AliesaConfig holds configuration for the "aliesa" DNS provider (AlibabaCloud ESA)
// See https://www.alibabacloud.com/en/product/esa
type AliesaConfig struct {
	AccessKey          string // ALIESA_ACCESS_KEY: Access key ID
	RAMRole            string // ALIESA_RAM_ROLE: Your instance RAM role (https://www.alibabacloud.com/help/en/ecs/user-guide/attach-an-instance-ram-role-to-an-ecs-instance)
	SecretKey          string // ALIESA_SECRET_KEY: Access Key secret
	SecurityToken      string // ALIESA_SECURITY_TOKEN: STS Security Token (optional)
	HTTPTimeout        string // ALIESA_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // ALIESA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // ALIESA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // ALIESA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *AliesaConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.AccessKey != "" {
		cfg.APIKey = c.AccessKey
	}
	if c.RAMRole != "" {
		cfg.RAMRole = c.RAMRole
	}
	if c.SecretKey != "" {
		cfg.SecretKey = c.SecretKey
	}
	if c.SecurityToken != "" {
		cfg.SecurityToken = c.SecurityToken
	}
	if c.HTTPTimeout != "" {
		v, err := strconv.Atoi(c.HTTPTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"httpTimeout\": %w", err)
		}
		cfg.HTTPTimeout = time.Duration(v) * time.Second
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AliesaConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"aliesa\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessKey", "ALIESA_ACCESS_KEY":
			c.AccessKey = val
		case "ramRole", "ALIESA_RAM_ROLE":
			c.RAMRole = val
		case "secretKey", "ALIESA_SECRET_KEY":
			c.SecretKey = val
		case "securityToken", "ALIESA_SECURITY_TOKEN":
			c.SecurityToken = val
		case "httpTimeout", "ALIESA_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "ALIESA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "ALIESA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "ALIESA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"aliesa\"", key)
		}
	}
	return nil
}
