// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// NamecheapConfig holds configuration for the "namecheap" DNS provider (Namecheap)
// See https://www.namecheap.com
type NamecheapConfig struct {
	APIKey             string // NAMECHEAP_API_KEY: API key
	APIUser            string // NAMECHEAP_API_USER: API user
	HTTPTimeout        string // NAMECHEAP_HTTP_TIMEOUT: API request timeout in seconds (Default: 60)
	PollingInterval    string // NAMECHEAP_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 15)
	PropagationTimeout string // NAMECHEAP_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 3600)
	Sandbox            string // NAMECHEAP_SANDBOX: Activate the sandbox (boolean)
	TTL                string // NAMECHEAP_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *NamecheapConfig) envVars() map[string]string {
	m := make(map[string]string, 7)
	if c.APIKey != "" {
		m["NAMECHEAP_API_KEY"] = c.APIKey
	}
	if c.APIUser != "" {
		m["NAMECHEAP_API_USER"] = c.APIUser
	}
	if c.HTTPTimeout != "" {
		m["NAMECHEAP_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["NAMECHEAP_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["NAMECHEAP_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.Sandbox != "" {
		m["NAMECHEAP_SANDBOX"] = c.Sandbox
	}
	if c.TTL != "" {
		m["NAMECHEAP_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *NamecheapConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"namecheap\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "NAMECHEAP_API_KEY":
			c.APIKey = val
		case "apiUser", "NAMECHEAP_API_USER":
			c.APIUser = val
		case "httpTimeout", "NAMECHEAP_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "NAMECHEAP_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "NAMECHEAP_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sandbox", "NAMECHEAP_SANDBOX":
			c.Sandbox = val
		case "ttl", "NAMECHEAP_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"namecheap\"", key)
		}
	}
	return nil
}
