// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// JokerConfig holds configuration for the "joker" DNS provider (Joker)
// See https://joker.com
type JokerConfig struct {
	APIKey             string // JOKER_API_KEY: API key (only with DMAPI mode)
	APIMode            string // JOKER_API_MODE: 'DMAPI' or 'SVC'. DMAPI is for resellers accounts. (Default: DMAPI)
	Password           string // JOKER_PASSWORD: Joker.com password
	Username           string // JOKER_USERNAME: Joker.com username
	HTTPTimeout        string // JOKER_HTTP_TIMEOUT: API request timeout in seconds (Default: 60)
	PollingInterval    string // JOKER_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // JOKER_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	SequenceInterval   string // JOKER_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 60), only with 'SVC' mode
	TTL                string // JOKER_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *JokerConfig) envVars() map[string]string {
	m := make(map[string]string, 9)
	if c.APIKey != "" {
		m["JOKER_API_KEY"] = c.APIKey
	}
	if c.APIMode != "" {
		m["JOKER_API_MODE"] = c.APIMode
	}
	if c.Password != "" {
		m["JOKER_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["JOKER_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["JOKER_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["JOKER_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["JOKER_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SequenceInterval != "" {
		m["JOKER_SEQUENCE_INTERVAL"] = c.SequenceInterval
	}
	if c.TTL != "" {
		m["JOKER_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *JokerConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"joker\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "JOKER_API_KEY":
			c.APIKey = val
		case "apiMode", "JOKER_API_MODE":
			c.APIMode = val
		case "password", "JOKER_PASSWORD":
			c.Password = val
		case "username", "JOKER_USERNAME":
			c.Username = val
		case "httpTimeout", "JOKER_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "JOKER_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "JOKER_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "JOKER_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "JOKER_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"joker\"", key)
		}
	}
	return nil
}
