// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DnspodConfig holds configuration for the "dnspod" DNS provider (DNSPod (deprecated))
// See https://www.dnspod.com/
type DnspodConfig struct {
	APIKey             string // DNSPOD_API_KEY: The user token
	HTTPTimeout        string // DNSPOD_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // DNSPOD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // DNSPOD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // DNSPOD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *DnspodConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.APIKey != "" {
		m["DNSPOD_API_KEY"] = c.APIKey
	}
	if c.HTTPTimeout != "" {
		m["DNSPOD_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["DNSPOD_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["DNSPOD_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["DNSPOD_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DnspodConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"dnspod\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "DNSPOD_API_KEY":
			c.APIKey = val
		case "httpTimeout", "DNSPOD_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "DNSPOD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DNSPOD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "DNSPOD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"dnspod\"", key)
		}
	}
	return nil
}
