// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// TodaynicConfig holds configuration for the "todaynic" DNS provider (TodayNIC/时代互联)
// See https://www.todaynic.com/
type TodaynicConfig struct {
	APIKey             string // TODAYNIC_API_KEY: API key
	AuthUserID         string // TODAYNIC_AUTH_USER_ID: account ID
	HTTPTimeout        string // TODAYNIC_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // TODAYNIC_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // TODAYNIC_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // TODAYNIC_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *TodaynicConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["TODAYNIC_API_KEY"] = c.APIKey
	}
	if c.AuthUserID != "" {
		m["TODAYNIC_AUTH_USER_ID"] = c.AuthUserID
	}
	if c.HTTPTimeout != "" {
		m["TODAYNIC_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["TODAYNIC_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["TODAYNIC_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["TODAYNIC_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *TodaynicConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"todaynic\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "TODAYNIC_API_KEY":
			c.APIKey = val
		case "authUserID", "TODAYNIC_AUTH_USER_ID":
			c.AuthUserID = val
		case "httpTimeout", "TODAYNIC_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "TODAYNIC_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "TODAYNIC_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "TODAYNIC_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"todaynic\"", key)
		}
	}
	return nil
}
