// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// ClouddnsConfig holds configuration for the "clouddns" DNS provider (CloudDNS)
// See https://vshosting.eu/
type ClouddnsConfig struct {
	ClientID           string // CLOUDDNS_CLIENT_ID: Client ID
	Email              string // CLOUDDNS_EMAIL: Account email
	Password           string // CLOUDDNS_PASSWORD: Account password
	HTTPTimeout        string // CLOUDDNS_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // CLOUDDNS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 5)
	PropagationTimeout string // CLOUDDNS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // CLOUDDNS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *ClouddnsConfig) envVars() map[string]string {
	m := make(map[string]string, 7)
	if c.ClientID != "" {
		m["CLOUDDNS_CLIENT_ID"] = c.ClientID
	}
	if c.Email != "" {
		m["CLOUDDNS_EMAIL"] = c.Email
	}
	if c.Password != "" {
		m["CLOUDDNS_PASSWORD"] = c.Password
	}
	if c.HTTPTimeout != "" {
		m["CLOUDDNS_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["CLOUDDNS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["CLOUDDNS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["CLOUDDNS_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *ClouddnsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"clouddns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "clientID", "CLOUDDNS_CLIENT_ID":
			c.ClientID = val
		case "email", "CLOUDDNS_EMAIL":
			c.Email = val
		case "password", "CLOUDDNS_PASSWORD":
			c.Password = val
		case "httpTimeout", "CLOUDDNS_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "CLOUDDNS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CLOUDDNS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "CLOUDDNS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"clouddns\"", key)
		}
	}
	return nil
}
