// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/cloudflare"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// CloudflareConfig holds configuration for the "cloudflare" DNS provider (Cloudflare)
// See https://www.cloudflare.com/dns/
type CloudflareConfig struct {
	APIEmail           string // CF_API_EMAIL: Account email
	APIKey             string // CF_API_KEY: API key
	DNSAPIToken        string // CF_DNS_API_TOKEN: API token with DNS:Edit permission (since v3.1.0)
	ZoneAPIToken       string // CF_ZONE_API_TOKEN: API token with Zone:Read permission (since v3.1.0)
	BaseURL            string // CLOUDFLARE_BASE_URL: API base URL (Default: https://api.cloudflare.com/client/v4)
	PollingInterval    string // CLOUDFLARE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // CLOUDFLARE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // CLOUDFLARE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *CloudflareConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIEmail != "" {
		cfg.AuthEmail = c.APIEmail
	}
	if c.APIKey != "" {
		cfg.AuthKey = c.APIKey
	}
	if c.DNSAPIToken != "" {
		cfg.AuthToken = c.DNSAPIToken
	}
	if c.ZoneAPIToken != "" {
		cfg.ZoneToken = c.ZoneAPIToken
	}
	if c.BaseURL != "" {
		cfg.BaseURL = c.BaseURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *CloudflareConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"cloudflare\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiEmail", "CF_API_EMAIL", "CLOUDFLARE_EMAIL":
			c.APIEmail = val
		case "apiKey", "CF_API_KEY", "CLOUDFLARE_API_KEY":
			c.APIKey = val
		case "dnsAPIToken", "CF_DNS_API_TOKEN", "CLOUDFLARE_DNS_API_TOKEN":
			c.DNSAPIToken = val
		case "zoneAPIToken", "CF_ZONE_API_TOKEN", "CLOUDFLARE_ZONE_API_TOKEN":
			c.ZoneAPIToken = val
		case "baseURL", "CLOUDFLARE_BASE_URL":
			c.BaseURL = val
		case "pollingInterval", "CLOUDFLARE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CLOUDFLARE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "CLOUDFLARE_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"cloudflare\"", key)
		}
	}
	return nil
}
