// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v5/challenge"
	prov "github.com/go-acme/lego/v5/providers/dns/euserv"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// EuservConfig holds configuration for the "euserv" DNS provider (EUserv)
// See https://www.euserv.com/en/
type EuservConfig struct {
	Email              string // EUSERV_EMAIL: The customer email address. You can also use the customer id instead.
	OrderID            string // EUSERV_ORDER_ID: The order ID of the API contract that you want to use for this login session.
	Password           string // EUSERV_PASSWORD: The customer account password.
	PollingInterval    string // EUSERV_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // EUSERV_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 360)
	TTL                string // EUSERV_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *EuservConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Email != "" {
		cfg.Email = c.Email
	}
	if c.OrderID != "" {
		cfg.OrderID = c.OrderID
	}
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases
func (c *EuservConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"euserv\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "email", "EUSERV_EMAIL":
			c.Email = val
		case "orderID", "EUSERV_ORDER_ID":
			c.OrderID = val
		case "password", "EUSERV_PASSWORD":
			c.Password = val
		case "pollingInterval", "EUSERV_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "EUSERV_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "EUSERV_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"euserv\"", key)
		}
	}
	return nil
}
