// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// MetanameConfig holds configuration for the "metaname" DNS provider (Metaname)
// See https://metaname.net
type MetanameConfig struct {
	AccountReference   string // METANAME_ACCOUNT_REFERENCE: The four-digit reference of a Metaname account
	APIKey             string // METANAME_API_KEY: API Key
	PollingInterval    string // METANAME_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // METANAME_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // METANAME_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *MetanameConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.AccountReference != "" {
		m["METANAME_ACCOUNT_REFERENCE"] = c.AccountReference
	}
	if c.APIKey != "" {
		m["METANAME_API_KEY"] = c.APIKey
	}
	if c.PollingInterval != "" {
		m["METANAME_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["METANAME_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["METANAME_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *MetanameConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"metaname\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accountReference", "METANAME_ACCOUNT_REFERENCE":
			c.AccountReference = val
		case "apiKey", "METANAME_API_KEY":
			c.APIKey = val
		case "pollingInterval", "METANAME_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "METANAME_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "METANAME_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"metaname\"", key)
		}
	}
	return nil
}
