// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/todaynic"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// TodaynicConfig holds configuration for the "todaynic" DNS provider (TodayNIC/时代互联)
// See https://www.todaynic.com/
type TodaynicConfig struct {
	APIKey             string // TODAYNIC_API_KEY: API key
	AuthUserID         string // TODAYNIC_AUTH_USER_ID: account ID
	PollingInterval    string // TODAYNIC_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // TODAYNIC_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // TODAYNIC_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *TodaynicConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.AuthUserID != "" {
		cfg.AuthUserID = c.AuthUserID
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *TodaynicConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"todaynic\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "TODAYNIC_API_KEY":
			c.APIKey = val
		case "authUserID", "TODAYNIC_AUTH_USER_ID":
			c.AuthUserID = val
		case "pollingInterval", "TODAYNIC_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "TODAYNIC_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "TODAYNIC_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"todaynic\"", key)
		}
	}
	return nil
}
