// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// GodaddyConfig holds configuration for the "godaddy" DNS provider (Go Daddy)
// See https://godaddy.com
type GodaddyConfig struct {
	APIKey             string // GODADDY_API_KEY: API key
	APISecret          string // GODADDY_API_SECRET: API secret
	HTTPTimeout        string // GODADDY_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // GODADDY_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // GODADDY_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // GODADDY_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *GodaddyConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["GODADDY_API_KEY"] = c.APIKey
	}
	if c.APISecret != "" {
		m["GODADDY_API_SECRET"] = c.APISecret
	}
	if c.HTTPTimeout != "" {
		m["GODADDY_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["GODADDY_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["GODADDY_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["GODADDY_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *GodaddyConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"godaddy\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "GODADDY_API_KEY":
			c.APIKey = val
		case "apiSecret", "GODADDY_API_SECRET":
			c.APISecret = val
		case "httpTimeout", "GODADDY_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "GODADDY_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "GODADDY_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "GODADDY_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"godaddy\"", key)
		}
	}
	return nil
}
