// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/cloudru"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// CloudruConfig holds configuration for the "cloudru" DNS provider (Cloud.ru)
// See https://cloud.ru
type CloudruConfig struct {
	KeyID              string // CLOUDRU_KEY_ID: Key ID (login)
	Secret             string // CLOUDRU_SECRET: Key Secret
	ServiceInstanceID  string // CLOUDRU_SERVICE_INSTANCE_ID: Service Instance ID (parentId)
	PollingInterval    string // CLOUDRU_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 5)
	PropagationTimeout string // CLOUDRU_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 300)
	SequenceInterval   string // CLOUDRU_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 120)
	TTL                string // CLOUDRU_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *CloudruConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.KeyID != "" {
		cfg.KeyID = c.KeyID
	}
	if c.Secret != "" {
		cfg.Secret = c.Secret
	}
	if c.ServiceInstanceID != "" {
		cfg.ServiceInstanceID = c.ServiceInstanceID
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.SequenceInterval != "" {
		v, err := strconv.Atoi(c.SequenceInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"sequenceInterval\": %w", err)
		}
		cfg.SequenceInterval = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *CloudruConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"cloudru\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "keyID", "CLOUDRU_KEY_ID":
			c.KeyID = val
		case "secret", "CLOUDRU_SECRET":
			c.Secret = val
		case "serviceInstanceID", "CLOUDRU_SERVICE_INSTANCE_ID":
			c.ServiceInstanceID = val
		case "pollingInterval", "CLOUDRU_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CLOUDRU_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "CLOUDRU_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "CLOUDRU_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"cloudru\"", key)
		}
	}
	return nil
}
