// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// HostingdeConfig holds configuration for the "hostingde" DNS provider (Hosting.de)
// See https://www.hosting.de/
type HostingdeConfig struct {
	APIKey             string // HOSTINGDE_API_KEY: API key
	HTTPTimeout        string // HOSTINGDE_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // HOSTINGDE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // HOSTINGDE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // HOSTINGDE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
	ZoneName           string // HOSTINGDE_ZONE_NAME: Zone name in ACE format
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *HostingdeConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["HOSTINGDE_API_KEY"] = c.APIKey
	}
	if c.HTTPTimeout != "" {
		m["HOSTINGDE_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["HOSTINGDE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["HOSTINGDE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["HOSTINGDE_TTL"] = c.TTL
	}
	if c.ZoneName != "" {
		m["HOSTINGDE_ZONE_NAME"] = c.ZoneName
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *HostingdeConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"hostingde\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "HOSTINGDE_API_KEY":
			c.APIKey = val
		case "httpTimeout", "HOSTINGDE_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "HOSTINGDE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "HOSTINGDE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "HOSTINGDE_TTL":
			c.TTL = val
		case "zoneName", "HOSTINGDE_ZONE_NAME":
			c.ZoneName = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"hostingde\"", key)
		}
	}
	return nil
}
