// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/nicmanager"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// NicmanagerConfig holds configuration for the "nicmanager" DNS provider (Nicmanager)
// See https://www.nicmanager.com/
type NicmanagerConfig struct {
	APIEmail           string // NICMANAGER_API_EMAIL: Email-based login
	APILogin           string // NICMANAGER_API_LOGIN: Login, used for Username-based login
	APIPassword        string // NICMANAGER_API_PASSWORD: Password, always required
	APIUsername        string // NICMANAGER_API_USERNAME: Username, used for Username-based login
	APIMode            string // NICMANAGER_API_MODE: mode: 'anycast' or 'zones' (for FreeDNS) (default: 'anycast')
	APIOTP             string // NICMANAGER_API_OTP: TOTP Secret (optional)
	PollingInterval    string // NICMANAGER_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // NICMANAGER_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 300)
	TTL                string // NICMANAGER_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 900)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *NicmanagerConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIEmail != "" {
		cfg.Email = c.APIEmail
	}
	if c.APILogin != "" {
		cfg.Login = c.APILogin
	}
	if c.APIPassword != "" {
		cfg.Password = c.APIPassword
	}
	if c.APIUsername != "" {
		cfg.Username = c.APIUsername
	}
	if c.APIMode != "" {
		cfg.Mode = c.APIMode
	}
	if c.APIOTP != "" {
		cfg.OTPSecret = c.APIOTP
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *NicmanagerConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"nicmanager\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiEmail", "NICMANAGER_API_EMAIL":
			c.APIEmail = val
		case "apiLogin", "NICMANAGER_API_LOGIN":
			c.APILogin = val
		case "apiPassword", "NICMANAGER_API_PASSWORD":
			c.APIPassword = val
		case "apiUsername", "NICMANAGER_API_USERNAME":
			c.APIUsername = val
		case "apiMode", "NICMANAGER_API_MODE":
			c.APIMode = val
		case "apiOTP", "NICMANAGER_API_OTP":
			c.APIOTP = val
		case "pollingInterval", "NICMANAGER_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "NICMANAGER_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "NICMANAGER_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"nicmanager\"", key)
		}
	}
	return nil
}
