// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DesecConfig holds configuration for the "desec" DNS provider (deSEC.io)
// See https://desec.io
type DesecConfig struct {
	Token              string // DESEC_TOKEN: Domain token
	HTTPTimeout        string // DESEC_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // DESEC_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 4)
	PropagationTimeout string // DESEC_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // DESEC_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 3600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *DesecConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.Token != "" {
		m["DESEC_TOKEN"] = c.Token
	}
	if c.HTTPTimeout != "" {
		m["DESEC_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["DESEC_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["DESEC_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["DESEC_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DesecConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"desec\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "DESEC_TOKEN":
			c.Token = val
		case "httpTimeout", "DESEC_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "DESEC_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DESEC_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "DESEC_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"desec\"", key)
		}
	}
	return nil
}
