// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// ServercowConfig holds configuration for the "servercow" DNS provider (Servercow)
// See https://servercow.de/
type ServercowConfig struct {
	Password           string // SERVERCOW_PASSWORD: API password
	Username           string // SERVERCOW_USERNAME: API username
	HTTPTimeout        string // SERVERCOW_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // SERVERCOW_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // SERVERCOW_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // SERVERCOW_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *ServercowConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.Password != "" {
		m["SERVERCOW_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["SERVERCOW_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["SERVERCOW_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["SERVERCOW_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["SERVERCOW_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["SERVERCOW_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *ServercowConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"servercow\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "SERVERCOW_PASSWORD":
			c.Password = val
		case "username", "SERVERCOW_USERNAME":
			c.Username = val
		case "httpTimeout", "SERVERCOW_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "SERVERCOW_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "SERVERCOW_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "SERVERCOW_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"servercow\"", key)
		}
	}
	return nil
}
