// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// NamesurferConfig holds configuration for the "namesurfer" DNS provider (FusionLayer NameSurfer)
// See https://www.fusionlayer.com/
type NamesurferConfig struct {
	APIKey             string // NAMESURFER_API_KEY: API key name
	APISecret          string // NAMESURFER_API_SECRET: API secret
	BaseURL            string // NAMESURFER_BASE_URL: The base URL of NameSurfer API (jsonrpc10) endpoint URL (e.g., https://foo.example.com:8443/API/NSService_10)
	HTTPTimeout        string // NAMESURFER_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	InsecureSkipVerify string // NAMESURFER_INSECURE_SKIP_VERIFY: Whether to verify the API certificate
	PollingInterval    string // NAMESURFER_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // NAMESURFER_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // NAMESURFER_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
	View               string // NAMESURFER_VIEW: DNS view name (optional, default: empty string)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *NamesurferConfig) envVars() map[string]string {
	m := make(map[string]string, 9)
	if c.APIKey != "" {
		m["NAMESURFER_API_KEY"] = c.APIKey
	}
	if c.APISecret != "" {
		m["NAMESURFER_API_SECRET"] = c.APISecret
	}
	if c.BaseURL != "" {
		m["NAMESURFER_BASE_URL"] = c.BaseURL
	}
	if c.HTTPTimeout != "" {
		m["NAMESURFER_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.InsecureSkipVerify != "" {
		m["NAMESURFER_INSECURE_SKIP_VERIFY"] = c.InsecureSkipVerify
	}
	if c.PollingInterval != "" {
		m["NAMESURFER_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["NAMESURFER_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["NAMESURFER_TTL"] = c.TTL
	}
	if c.View != "" {
		m["NAMESURFER_VIEW"] = c.View
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *NamesurferConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"namesurfer\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "NAMESURFER_API_KEY":
			c.APIKey = val
		case "apiSecret", "NAMESURFER_API_SECRET":
			c.APISecret = val
		case "baseURL", "NAMESURFER_BASE_URL":
			c.BaseURL = val
		case "httpTimeout", "NAMESURFER_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "insecureSkipVerify", "NAMESURFER_INSECURE_SKIP_VERIFY":
			c.InsecureSkipVerify = val
		case "pollingInterval", "NAMESURFER_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "NAMESURFER_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "NAMESURFER_TTL":
			c.TTL = val
		case "view", "NAMESURFER_VIEW":
			c.View = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"namesurfer\"", key)
		}
	}
	return nil
}
