// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// LuadnsConfig holds configuration for the "luadns" DNS provider (LuaDNS)
// See https://luadns.com
type LuadnsConfig struct {
	APIToken           string // LUADNS_API_TOKEN: API token
	APIUsername        string // LUADNS_API_USERNAME: Username (your email)
	HTTPTimeout        string // LUADNS_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // LUADNS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // LUADNS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // LUADNS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *LuadnsConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIToken != "" {
		m["LUADNS_API_TOKEN"] = c.APIToken
	}
	if c.APIUsername != "" {
		m["LUADNS_API_USERNAME"] = c.APIUsername
	}
	if c.HTTPTimeout != "" {
		m["LUADNS_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["LUADNS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["LUADNS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["LUADNS_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *LuadnsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"luadns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiToken", "LUADNS_API_TOKEN":
			c.APIToken = val
		case "apiUsername", "LUADNS_API_USERNAME":
			c.APIUsername = val
		case "httpTimeout", "LUADNS_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "LUADNS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "LUADNS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "LUADNS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"luadns\"", key)
		}
	}
	return nil
}
