// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AlwaysdataConfig holds configuration for the "alwaysdata" DNS provider (Alwaysdata)
// See https://alwaysdata.com/
type AlwaysdataConfig struct {
	APIKey             string // ALWAYSDATA_API_KEY: API Key
	Account            string // ALWAYSDATA_ACCOUNT: Account name
	HTTPTimeout        string // ALWAYSDATA_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // ALWAYSDATA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // ALWAYSDATA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // ALWAYSDATA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *AlwaysdataConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["ALWAYSDATA_API_KEY"] = c.APIKey
	}
	if c.Account != "" {
		m["ALWAYSDATA_ACCOUNT"] = c.Account
	}
	if c.HTTPTimeout != "" {
		m["ALWAYSDATA_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["ALWAYSDATA_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["ALWAYSDATA_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["ALWAYSDATA_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AlwaysdataConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"alwaysdata\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "ALWAYSDATA_API_KEY":
			c.APIKey = val
		case "account", "ALWAYSDATA_ACCOUNT":
			c.Account = val
		case "httpTimeout", "ALWAYSDATA_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "ALWAYSDATA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "ALWAYSDATA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "ALWAYSDATA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"alwaysdata\"", key)
		}
	}
	return nil
}
