// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/selectel"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// SelectelConfig holds configuration for the "selectel" DNS provider (Selectel)
// See https://kb.selectel.com/
type SelectelConfig struct {
	APIToken           string // SELECTEL_API_TOKEN: API token
	BaseURL            string // SELECTEL_BASE_URL: API endpoint URL
	PollingInterval    string // SELECTEL_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // SELECTEL_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // SELECTEL_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *SelectelConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIToken != "" {
		cfg.Token = c.APIToken
	}
	if c.BaseURL != "" {
		cfg.BaseURL = c.BaseURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *SelectelConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"selectel\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiToken", "SELECTEL_API_TOKEN":
			c.APIToken = val
		case "baseURL", "SELECTEL_BASE_URL":
			c.BaseURL = val
		case "pollingInterval", "SELECTEL_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "SELECTEL_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "SELECTEL_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"selectel\"", key)
		}
	}
	return nil
}
