// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// PorkbunConfig holds configuration for the "porkbun" DNS provider (Porkbun)
// See https://porkbun.com/
type PorkbunConfig struct {
	APIKey             string // PORKBUN_API_KEY: API key
	SecretAPIKey       string // PORKBUN_SECRET_API_KEY: secret API key
	HTTPTimeout        string // PORKBUN_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // PORKBUN_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // PORKBUN_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 600)
	TTL                string // PORKBUN_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *PorkbunConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["PORKBUN_API_KEY"] = c.APIKey
	}
	if c.SecretAPIKey != "" {
		m["PORKBUN_SECRET_API_KEY"] = c.SecretAPIKey
	}
	if c.HTTPTimeout != "" {
		m["PORKBUN_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["PORKBUN_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["PORKBUN_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["PORKBUN_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *PorkbunConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"porkbun\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "PORKBUN_API_KEY":
			c.APIKey = val
		case "secretAPIKey", "PORKBUN_SECRET_API_KEY":
			c.SecretAPIKey = val
		case "httpTimeout", "PORKBUN_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "PORKBUN_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "PORKBUN_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "PORKBUN_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"porkbun\"", key)
		}
	}
	return nil
}
