// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// LoopiaConfig holds configuration for the "loopia" DNS provider (Loopia)
// See https://loopia.com
type LoopiaConfig struct {
	APIPassword        string // LOOPIA_API_PASSWORD: API password
	APIUser            string // LOOPIA_API_USER: API username
	APIURL             string // LOOPIA_API_URL: API endpoint. Ex: https://api.loopia.se/RPCSERV or https://api.loopia.rs/RPCSERV
	HTTPTimeout        string // LOOPIA_HTTP_TIMEOUT: API request timeout in seconds (Default: 60)
	PollingInterval    string // LOOPIA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2400)
	PropagationTimeout string // LOOPIA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // LOOPIA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *LoopiaConfig) envVars() map[string]string {
	m := make(map[string]string, 7)
	if c.APIPassword != "" {
		m["LOOPIA_API_PASSWORD"] = c.APIPassword
	}
	if c.APIUser != "" {
		m["LOOPIA_API_USER"] = c.APIUser
	}
	if c.APIURL != "" {
		m["LOOPIA_API_URL"] = c.APIURL
	}
	if c.HTTPTimeout != "" {
		m["LOOPIA_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["LOOPIA_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["LOOPIA_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["LOOPIA_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *LoopiaConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"loopia\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiPassword", "LOOPIA_API_PASSWORD":
			c.APIPassword = val
		case "apiUser", "LOOPIA_API_USER":
			c.APIUser = val
		case "apiURL", "LOOPIA_API_URL":
			c.APIURL = val
		case "httpTimeout", "LOOPIA_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "LOOPIA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "LOOPIA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "LOOPIA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"loopia\"", key)
		}
	}
	return nil
}
