// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v5/challenge"
	prov "github.com/go-acme/lego/v5/providers/dns/veesp"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// VeespConfig holds configuration for the "veesp" DNS provider (Veesp)
// See https://veesp.com
type VeespConfig struct {
	Password           string // VEESP_PASSWORD: Password
	Username           string // VEESP_USERNAME: Username
	PollingInterval    string // VEESP_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // VEESP_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // VEESP_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *VeespConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases
func (c *VeespConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"veesp\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "VEESP_PASSWORD":
			c.Password = val
		case "username", "VEESP_USERNAME":
			c.Username = val
		case "pollingInterval", "VEESP_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "VEESP_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "VEESP_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"veesp\"", key)
		}
	}
	return nil
}
