// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// MijnhostConfig holds configuration for the "mijnhost" DNS provider (mijn.host)
// See https://mijn.host/
type MijnhostConfig struct {
	APIKey             string // MIJNHOST_API_KEY: The API key
	HTTPTimeout        string // MIJNHOST_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // MIJNHOST_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // MIJNHOST_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SequenceInterval   string // MIJNHOST_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 60)
	TTL                string // MIJNHOST_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *MijnhostConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["MIJNHOST_API_KEY"] = c.APIKey
	}
	if c.HTTPTimeout != "" {
		m["MIJNHOST_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["MIJNHOST_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["MIJNHOST_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SequenceInterval != "" {
		m["MIJNHOST_SEQUENCE_INTERVAL"] = c.SequenceInterval
	}
	if c.TTL != "" {
		m["MIJNHOST_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *MijnhostConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"mijnhost\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "MIJNHOST_API_KEY":
			c.APIKey = val
		case "httpTimeout", "MIJNHOST_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "MIJNHOST_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "MIJNHOST_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "MIJNHOST_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "MIJNHOST_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"mijnhost\"", key)
		}
	}
	return nil
}
