// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/excedo"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// ExcedoConfig holds configuration for the "excedo" DNS provider (Excedo)
// See https://excedo.se/
type ExcedoConfig struct {
	APIKey             string // EXCEDO_API_KEY: API key
	APIURL             string // EXCEDO_API_URL: API base URL
	PollingInterval    string // EXCEDO_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // EXCEDO_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 300)
	TTL                string // EXCEDO_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *ExcedoConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.APIURL != "" {
		cfg.APIURL = c.APIURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *ExcedoConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"excedo\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "EXCEDO_API_KEY":
			c.APIKey = val
		case "apiURL", "EXCEDO_API_URL":
			c.APIURL = val
		case "pollingInterval", "EXCEDO_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "EXCEDO_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "EXCEDO_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"excedo\"", key)
		}
	}
	return nil
}
