// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/bluecat"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// BluecatConfig holds configuration for the "bluecat" DNS provider (Bluecat)
// See https://www.bluecatnetworks.com
type BluecatConfig struct {
	ConfigName         string // BLUECAT_CONFIG_NAME: Configuration name
	DNSView            string // BLUECAT_DNS_VIEW: External DNS View Name
	Password           string // BLUECAT_PASSWORD: API password
	ServerURL          string // BLUECAT_SERVER_URL: The server URL, should have scheme, hostname, and port (if required) of the authoritative Bluecat BAM serve
	UserName           string // BLUECAT_USER_NAME: API username
	PollingInterval    string // BLUECAT_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // BLUECAT_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SkipDeploy         string // BLUECAT_SKIP_DEPLOY: Skip deployements
	TTL                string // BLUECAT_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *BluecatConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.ConfigName != "" {
		cfg.ConfigName = c.ConfigName
	}
	if c.DNSView != "" {
		cfg.DNSView = c.DNSView
	}
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.ServerURL != "" {
		cfg.BaseURL = c.ServerURL
	}
	if c.UserName != "" {
		cfg.UserName = c.UserName
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.SkipDeploy != "" {
		v, err := strconv.ParseBool(c.SkipDeploy)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"skipDeploy\": %w", err)
		}
		cfg.SkipDeploy = v
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *BluecatConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"bluecat\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "configName", "BLUECAT_CONFIG_NAME":
			c.ConfigName = val
		case "dnsView", "BLUECAT_DNS_VIEW":
			c.DNSView = val
		case "password", "BLUECAT_PASSWORD":
			c.Password = val
		case "serverURL", "BLUECAT_SERVER_URL":
			c.ServerURL = val
		case "userName", "BLUECAT_USER_NAME":
			c.UserName = val
		case "pollingInterval", "BLUECAT_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "BLUECAT_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "skipDeploy", "BLUECAT_SKIP_DEPLOY":
			c.SkipDeploy = val
		case "ttl", "BLUECAT_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"bluecat\"", key)
		}
	}
	return nil
}
