// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// YandexConfig holds configuration for the "yandex" DNS provider (Yandex PDD)
// See https://pdd.yandex.com
type YandexConfig struct {
	PDDToken           string // YANDEX_PDD_TOKEN: Basic authentication username
	HTTPTimeout        string // YANDEX_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // YANDEX_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // YANDEX_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // YANDEX_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 21600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *YandexConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.PDDToken != "" {
		m["YANDEX_PDD_TOKEN"] = c.PDDToken
	}
	if c.HTTPTimeout != "" {
		m["YANDEX_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["YANDEX_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["YANDEX_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["YANDEX_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *YandexConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"yandex\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "pddToken", "YANDEX_PDD_TOKEN":
			c.PDDToken = val
		case "httpTimeout", "YANDEX_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "YANDEX_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "YANDEX_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "YANDEX_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"yandex\"", key)
		}
	}
	return nil
}
