// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// HyperoneConfig holds configuration for the "hyperone" DNS provider (HyperOne)
// See https://www.hyperone.com
type HyperoneConfig struct {
	APIURL             string // HYPERONE_API_URL: Allows to pass custom API Endpoint to be used in the challenge (default https://api.hyperone.com/v2)
	HTTPTimeout        string // HYPERONE_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	LocationID         string // HYPERONE_LOCATION_ID: Specifies location (region) to be used in API calls. (default pl-waw-1)
	PassportLocation   string // HYPERONE_PASSPORT_LOCATION: Allows to pass custom passport file location (default ~/.h1/passport.json)
	PollingInterval    string // HYPERONE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 60)
	PropagationTimeout string // HYPERONE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 2)
	TTL                string // HYPERONE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *HyperoneConfig) envVars() map[string]string {
	m := make(map[string]string, 7)
	if c.APIURL != "" {
		m["HYPERONE_API_URL"] = c.APIURL
	}
	if c.HTTPTimeout != "" {
		m["HYPERONE_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.LocationID != "" {
		m["HYPERONE_LOCATION_ID"] = c.LocationID
	}
	if c.PassportLocation != "" {
		m["HYPERONE_PASSPORT_LOCATION"] = c.PassportLocation
	}
	if c.PollingInterval != "" {
		m["HYPERONE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["HYPERONE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["HYPERONE_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *HyperoneConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"hyperone\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiURL", "HYPERONE_API_URL":
			c.APIURL = val
		case "httpTimeout", "HYPERONE_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "locationID", "HYPERONE_LOCATION_ID":
			c.LocationID = val
		case "passportLocation", "HYPERONE_PASSPORT_LOCATION":
			c.PassportLocation = val
		case "pollingInterval", "HYPERONE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "HYPERONE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "HYPERONE_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"hyperone\"", key)
		}
	}
	return nil
}
