// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// NamedotcomConfig holds configuration for the "namedotcom" DNS provider (Name.com)
// See https://www.name.com
type NamedotcomConfig struct {
	APIToken           string // NAMECOM_API_TOKEN: API token
	Username           string // NAMECOM_USERNAME: Username
	HTTPTimeout        string // NAMECOM_HTTP_TIMEOUT: API request timeout in seconds (Default: 10)
	PollingInterval    string // NAMECOM_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 20)
	PropagationTimeout string // NAMECOM_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 900)
	TTL                string // NAMECOM_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *NamedotcomConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIToken != "" {
		m["NAMECOM_API_TOKEN"] = c.APIToken
	}
	if c.Username != "" {
		m["NAMECOM_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["NAMECOM_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["NAMECOM_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["NAMECOM_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["NAMECOM_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *NamedotcomConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"namedotcom\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiToken", "NAMECOM_API_TOKEN":
			c.APIToken = val
		case "username", "NAMECOM_USERNAME":
			c.Username = val
		case "httpTimeout", "NAMECOM_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "NAMECOM_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "NAMECOM_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "NAMECOM_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"namedotcom\"", key)
		}
	}
	return nil
}
