// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AcmeDNSConfig holds configuration for the "acme-dns" DNS provider (Joohoi's ACME-DNS)
// See https://github.com/joohoi/acme-dns
type AcmeDNSConfig struct {
	DNSAPIBase        string // ACME_DNS_API_BASE: The ACME-DNS API address
	DNSStorageBaseURL string // ACME_DNS_STORAGE_BASE_URL: The ACME-DNS JSON account data server.
	DNSStoragePath    string // ACME_DNS_STORAGE_PATH: The ACME-DNS JSON account data file. A per-domain account will be registered/persisted to this file and used for TXT updates.
	DNSAllowlist      string // ACME_DNS_ALLOWLIST: Source networks using CIDR notation (multiple values should be separated with a comma).
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *AcmeDNSConfig) envVars() map[string]string {
	m := make(map[string]string, 4)
	if c.DNSAPIBase != "" {
		m["ACME_DNS_API_BASE"] = c.DNSAPIBase
	}
	if c.DNSStorageBaseURL != "" {
		m["ACME_DNS_STORAGE_BASE_URL"] = c.DNSStorageBaseURL
	}
	if c.DNSStoragePath != "" {
		m["ACME_DNS_STORAGE_PATH"] = c.DNSStoragePath
	}
	if c.DNSAllowlist != "" {
		m["ACME_DNS_ALLOWLIST"] = c.DNSAllowlist
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AcmeDNSConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"acme-dns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "dnsAPIBase", "ACME_DNS_API_BASE":
			c.DNSAPIBase = val
		case "dnsStorageBaseURL", "ACME_DNS_STORAGE_BASE_URL":
			c.DNSStorageBaseURL = val
		case "dnsStoragePath", "ACME_DNS_STORAGE_PATH":
			c.DNSStoragePath = val
		case "dnsAllowlist", "ACME_DNS_ALLOWLIST":
			c.DNSAllowlist = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"acme-dns\"", key)
		}
	}
	return nil
}
