// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// ExecConfig holds configuration for the "exec" DNS provider (External program)
// See /dns/exec
type ExecConfig struct {
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *ExecConfig) envVars() map[string]string {
	m := make(map[string]string, 0)
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *ExecConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"exec\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"exec\"", key)
		}
	}
	return nil
}
