// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// EfficientipConfig holds configuration for the "efficientip" DNS provider (Efficient IP)
// See https://efficientip.com/
type EfficientipConfig struct {
	DNSName            string // EFFICIENTIP_DNS_NAME: DNS name (ex: dns.smart)
	Hostname           string // EFFICIENTIP_HOSTNAME: Hostname (ex: foo.example.com)
	Password           string // EFFICIENTIP_PASSWORD: Password
	Username           string // EFFICIENTIP_USERNAME: Username
	HTTPTimeout        string // EFFICIENTIP_HTTP_TIMEOUT: API request timeout in seconds (Default: 10)
	InsecureSkipVerify string // EFFICIENTIP_INSECURE_SKIP_VERIFY: Whether or not to verify EfficientIP API certificate
	PollingInterval    string // EFFICIENTIP_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // EFFICIENTIP_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	ViewName           string // EFFICIENTIP_VIEW_NAME: View name (ex: external)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *EfficientipConfig) envVars() map[string]string {
	m := make(map[string]string, 9)
	if c.DNSName != "" {
		m["EFFICIENTIP_DNS_NAME"] = c.DNSName
	}
	if c.Hostname != "" {
		m["EFFICIENTIP_HOSTNAME"] = c.Hostname
	}
	if c.Password != "" {
		m["EFFICIENTIP_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["EFFICIENTIP_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["EFFICIENTIP_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.InsecureSkipVerify != "" {
		m["EFFICIENTIP_INSECURE_SKIP_VERIFY"] = c.InsecureSkipVerify
	}
	if c.PollingInterval != "" {
		m["EFFICIENTIP_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["EFFICIENTIP_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.ViewName != "" {
		m["EFFICIENTIP_VIEW_NAME"] = c.ViewName
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *EfficientipConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"efficientip\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "dnsName", "EFFICIENTIP_DNS_NAME":
			c.DNSName = val
		case "hostname", "EFFICIENTIP_HOSTNAME":
			c.Hostname = val
		case "password", "EFFICIENTIP_PASSWORD":
			c.Password = val
		case "username", "EFFICIENTIP_USERNAME":
			c.Username = val
		case "httpTimeout", "EFFICIENTIP_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "insecureSkipVerify", "EFFICIENTIP_INSECURE_SKIP_VERIFY":
			c.InsecureSkipVerify = val
		case "pollingInterval", "EFFICIENTIP_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "EFFICIENTIP_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "viewName", "EFFICIENTIP_VIEW_NAME":
			c.ViewName = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"efficientip\"", key)
		}
	}
	return nil
}
