// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Selectelv2Config holds configuration for the "selectelv2" DNS provider (Selectel v2)
// See https://selectel.ru
type Selectelv2Config struct {
	AccountID          string // SELECTELV2_ACCOUNT_ID: Selectel account ID (INT)
	Password           string // SELECTELV2_PASSWORD: Openstack username's password
	ProjectID          string // SELECTELV2_PROJECT_ID: Cloud project ID (UUID)
	Username           string // SELECTELV2_USERNAME: Openstack username
	AuthRegion         string // SELECTELV2_AUTH_REGION: Location for auth endpoint like ResellAPI or Keystone (default: 'ru-1')
	AuthURL            string // SELECTELV2_AUTH_URL: Identity endpoint (defaul: 'https://cloud.api.selcloud.ru/identity/v3/')
	BaseURL            string // SELECTELV2_BASE_URL: API endpoint URL
	HTTPTimeout        string // SELECTELV2_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // SELECTELV2_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 5)
	PropagationTimeout string // SELECTELV2_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // SELECTELV2_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)
	UserDomainName     string // SELECTELV2_USER_DOMAIN_NAME: To specify the domain name (account ID) where the user is located. (default: SELECTELV2_ACCOUNT_ID)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *Selectelv2Config) envVars() map[string]string {
	m := make(map[string]string, 12)
	if c.AccountID != "" {
		m["SELECTELV2_ACCOUNT_ID"] = c.AccountID
	}
	if c.Password != "" {
		m["SELECTELV2_PASSWORD"] = c.Password
	}
	if c.ProjectID != "" {
		m["SELECTELV2_PROJECT_ID"] = c.ProjectID
	}
	if c.Username != "" {
		m["SELECTELV2_USERNAME"] = c.Username
	}
	if c.AuthRegion != "" {
		m["SELECTELV2_AUTH_REGION"] = c.AuthRegion
	}
	if c.AuthURL != "" {
		m["SELECTELV2_AUTH_URL"] = c.AuthURL
	}
	if c.BaseURL != "" {
		m["SELECTELV2_BASE_URL"] = c.BaseURL
	}
	if c.HTTPTimeout != "" {
		m["SELECTELV2_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["SELECTELV2_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["SELECTELV2_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["SELECTELV2_TTL"] = c.TTL
	}
	if c.UserDomainName != "" {
		m["SELECTELV2_USER_DOMAIN_NAME"] = c.UserDomainName
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Selectelv2Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"selectelv2\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accountID", "SELECTELV2_ACCOUNT_ID":
			c.AccountID = val
		case "password", "SELECTELV2_PASSWORD":
			c.Password = val
		case "projectID", "SELECTELV2_PROJECT_ID":
			c.ProjectID = val
		case "username", "SELECTELV2_USERNAME":
			c.Username = val
		case "authRegion", "SELECTELV2_AUTH_REGION":
			c.AuthRegion = val
		case "authURL", "SELECTELV2_AUTH_URL":
			c.AuthURL = val
		case "baseURL", "SELECTELV2_BASE_URL":
			c.BaseURL = val
		case "httpTimeout", "SELECTELV2_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "SELECTELV2_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "SELECTELV2_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "SELECTELV2_TTL":
			c.TTL = val
		case "userDomainName", "SELECTELV2_USER_DOMAIN_NAME":
			c.UserDomainName = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"selectelv2\"", key)
		}
	}
	return nil
}
