// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// BookmynameConfig holds configuration for the "bookmyname" DNS provider (BookMyName)
// See https://www.bookmyname.com/
type BookmynameConfig struct {
	Password           string // BOOKMYNAME_PASSWORD: Password
	Username           string // BOOKMYNAME_USERNAME: Username
	HTTPTimeout        string // BOOKMYNAME_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // BOOKMYNAME_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // BOOKMYNAME_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // BOOKMYNAME_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *BookmynameConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.Password != "" {
		m["BOOKMYNAME_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["BOOKMYNAME_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["BOOKMYNAME_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["BOOKMYNAME_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["BOOKMYNAME_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["BOOKMYNAME_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *BookmynameConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"bookmyname\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "BOOKMYNAME_PASSWORD":
			c.Password = val
		case "username", "BOOKMYNAME_USERNAME":
			c.Username = val
		case "httpTimeout", "BOOKMYNAME_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "BOOKMYNAME_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "BOOKMYNAME_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "BOOKMYNAME_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"bookmyname\"", key)
		}
	}
	return nil
}
