// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/mydnsjp"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// MydnsjpConfig holds configuration for the "mydnsjp" DNS provider (MyDNS.jp)
// See https://www.mydns.jp
type MydnsjpConfig struct {
	MasterID           string // MYDNSJP_MASTER_ID: Master ID
	Password           string // MYDNSJP_PASSWORD: Password
	PollingInterval    string // MYDNSJP_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // MYDNSJP_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *MydnsjpConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.MasterID != "" {
		cfg.MasterID = c.MasterID
	}
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *MydnsjpConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"mydnsjp\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "masterID", "MYDNSJP_MASTER_ID":
			c.MasterID = val
		case "password", "MYDNSJP_PASSWORD":
			c.Password = val
		case "pollingInterval", "MYDNSJP_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "MYDNSJP_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"mydnsjp\"", key)
		}
	}
	return nil
}
