// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// WebnamesConfig holds configuration for the "webnames" DNS provider (webnames.ru)
// See https://www.webnames.ru/
type WebnamesConfig struct {
	APIKey             string // WEBNAMESRU_API_KEY: Domain API key
	HTTPTimeout        string // WEBNAMESRU_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // WEBNAMESRU_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // WEBNAMESRU_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *WebnamesConfig) envVars() map[string]string {
	m := make(map[string]string, 4)
	if c.APIKey != "" {
		m["WEBNAMESRU_API_KEY"] = c.APIKey
	}
	if c.HTTPTimeout != "" {
		m["WEBNAMESRU_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["WEBNAMESRU_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["WEBNAMESRU_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *WebnamesConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"webnames\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "WEBNAMESRU_API_KEY":
			c.APIKey = val
		case "httpTimeout", "WEBNAMESRU_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "WEBNAMESRU_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "WEBNAMESRU_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"webnames\"", key)
		}
	}
	return nil
}
