// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// UcloudConfig holds configuration for the "ucloud" DNS provider (UCloud)
// See https://www.ucloud.cn/
type UcloudConfig struct {
	PrivateKey         string // UCLOUD_PRIVATE_KEY: Private key
	PublicKey          string // UCLOUD_PUBLIC_KEY: Public key
	HTTPTimeout        string // UCLOUD_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // UCLOUD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	ProjectID          string // UCLOUD_PROJECT_ID: Project ID
	PropagationTimeout string // UCLOUD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	Region             string // UCLOUD_REGION: Region
	TTL                string // UCLOUD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *UcloudConfig) envVars() map[string]string {
	m := make(map[string]string, 8)
	if c.PrivateKey != "" {
		m["UCLOUD_PRIVATE_KEY"] = c.PrivateKey
	}
	if c.PublicKey != "" {
		m["UCLOUD_PUBLIC_KEY"] = c.PublicKey
	}
	if c.HTTPTimeout != "" {
		m["UCLOUD_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["UCLOUD_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.ProjectID != "" {
		m["UCLOUD_PROJECT_ID"] = c.ProjectID
	}
	if c.PropagationTimeout != "" {
		m["UCLOUD_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.Region != "" {
		m["UCLOUD_REGION"] = c.Region
	}
	if c.TTL != "" {
		m["UCLOUD_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *UcloudConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"ucloud\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "privateKey", "UCLOUD_PRIVATE_KEY":
			c.PrivateKey = val
		case "publicKey", "UCLOUD_PUBLIC_KEY":
			c.PublicKey = val
		case "httpTimeout", "UCLOUD_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "UCLOUD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "projectID", "UCLOUD_PROJECT_ID":
			c.ProjectID = val
		case "propagationTimeout", "UCLOUD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "region", "UCLOUD_REGION":
			c.Region = val
		case "ttl", "UCLOUD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"ucloud\"", key)
		}
	}
	return nil
}
