// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// ScalewayConfig holds configuration for the "scaleway" DNS provider (Scaleway)
// See https://developers.scaleway.com/
type ScalewayConfig struct {
	ProjectID          string // SCW_PROJECT_ID: Project to use (optional)
	SecretKey          string // SCW_SECRET_KEY: Secret key
	AccessKey          string // SCW_ACCESS_KEY: Access key
	HTTPTimeout        string // SCW_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // SCW_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // SCW_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // SCW_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *ScalewayConfig) envVars() map[string]string {
	m := make(map[string]string, 7)
	if c.ProjectID != "" {
		m["SCW_PROJECT_ID"] = c.ProjectID
	}
	if c.SecretKey != "" {
		m["SCW_SECRET_KEY"] = c.SecretKey
	}
	if c.AccessKey != "" {
		m["SCW_ACCESS_KEY"] = c.AccessKey
	}
	if c.HTTPTimeout != "" {
		m["SCW_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["SCW_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["SCW_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["SCW_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *ScalewayConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"scaleway\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "projectID", "SCW_PROJECT_ID":
			c.ProjectID = val
		case "secretKey", "SCW_SECRET_KEY":
			c.SecretKey = val
		case "accessKey", "SCW_ACCESS_KEY":
			c.AccessKey = val
		case "httpTimeout", "SCW_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "SCW_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "SCW_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "SCW_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"scaleway\"", key)
		}
	}
	return nil
}
