// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/ipv64"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Ipv64Config holds configuration for the "ipv64" DNS provider (IPv64)
// See https://ipv64.net/
type Ipv64Config struct {
	APIKey             string // IPV64_API_KEY: Account API Key
	PollingInterval    string // IPV64_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // IPV64_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *Ipv64Config) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Ipv64Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"ipv64\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "IPV64_API_KEY":
			c.APIKey = val
		case "pollingInterval", "IPV64_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "IPV64_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"ipv64\"", key)
		}
	}
	return nil
}
