// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// OvhConfig holds configuration for the "ovh" DNS provider (OVH)
// See https://www.ovh.com/
type OvhConfig struct {
	AccessToken        string // OVH_ACCESS_TOKEN: Access token
	ApplicationKey     string // OVH_APPLICATION_KEY: Application key (Application Key authentication)
	ApplicationSecret  string // OVH_APPLICATION_SECRET: Application secret (Application Key authentication)
	ClientID           string // OVH_CLIENT_ID: Client ID (OAuth2)
	ClientSecret       string // OVH_CLIENT_SECRET: Client secret (OAuth2)
	ConsumerKey        string // OVH_CONSUMER_KEY: Consumer key (Application Key authentication)
	Endpoint           string // OVH_ENDPOINT: Endpoint URL (ovh-eu or ovh-ca)
	HTTPTimeout        string // OVH_HTTP_TIMEOUT: API request timeout in seconds (Default: 180)
	PollingInterval    string // OVH_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // OVH_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // OVH_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *OvhConfig) envVars() map[string]string {
	m := make(map[string]string, 11)
	if c.AccessToken != "" {
		m["OVH_ACCESS_TOKEN"] = c.AccessToken
	}
	if c.ApplicationKey != "" {
		m["OVH_APPLICATION_KEY"] = c.ApplicationKey
	}
	if c.ApplicationSecret != "" {
		m["OVH_APPLICATION_SECRET"] = c.ApplicationSecret
	}
	if c.ClientID != "" {
		m["OVH_CLIENT_ID"] = c.ClientID
	}
	if c.ClientSecret != "" {
		m["OVH_CLIENT_SECRET"] = c.ClientSecret
	}
	if c.ConsumerKey != "" {
		m["OVH_CONSUMER_KEY"] = c.ConsumerKey
	}
	if c.Endpoint != "" {
		m["OVH_ENDPOINT"] = c.Endpoint
	}
	if c.HTTPTimeout != "" {
		m["OVH_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["OVH_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["OVH_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["OVH_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *OvhConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"ovh\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessToken", "OVH_ACCESS_TOKEN":
			c.AccessToken = val
		case "applicationKey", "OVH_APPLICATION_KEY":
			c.ApplicationKey = val
		case "applicationSecret", "OVH_APPLICATION_SECRET":
			c.ApplicationSecret = val
		case "clientID", "OVH_CLIENT_ID":
			c.ClientID = val
		case "clientSecret", "OVH_CLIENT_SECRET":
			c.ClientSecret = val
		case "consumerKey", "OVH_CONSUMER_KEY":
			c.ConsumerKey = val
		case "endpoint", "OVH_ENDPOINT":
			c.Endpoint = val
		case "httpTimeout", "OVH_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "OVH_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "OVH_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "OVH_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"ovh\"", key)
		}
	}
	return nil
}
