// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/versio"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// VersioConfig holds configuration for the "versio" DNS provider (Versio.[nl|eu|uk])
// See https://www.versio.nl/domeinnamen
type VersioConfig struct {
	Password           string // VERSIO_PASSWORD: Basic authentication password
	Username           string // VERSIO_USERNAME: Basic authentication username
	PollingInterval    string // VERSIO_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 5)
	PropagationTimeout string // VERSIO_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SequenceInterval   string // VERSIO_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 60)
	TTL                string // VERSIO_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *VersioConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.SequenceInterval != "" {
		v, err := strconv.Atoi(c.SequenceInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"sequenceInterval\": %w", err)
		}
		cfg.SequenceInterval = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *VersioConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"versio\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "VERSIO_PASSWORD":
			c.Password = val
		case "username", "VERSIO_USERNAME":
			c.Username = val
		case "pollingInterval", "VERSIO_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "VERSIO_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "VERSIO_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "VERSIO_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"versio\"", key)
		}
	}
	return nil
}
