// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DyndnsfreeConfig holds configuration for the "dyndnsfree" DNS provider (DynDnsFree.de)
// See https://www.dyndnsfree.de
type DyndnsfreeConfig struct {
	Password           string // DYNDNSFREE_PASSWORD: Password
	Username           string // DYNDNSFREE_USERNAME: Username
	HTTPTimeout        string // DYNDNSFREE_HTTP_TIMEOUT: Request timeout in seconds (Default: 30)
	PollingInterval    string // DYNDNSFREE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // DYNDNSFREE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *DyndnsfreeConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.Password != "" {
		m["DYNDNSFREE_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["DYNDNSFREE_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["DYNDNSFREE_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["DYNDNSFREE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["DYNDNSFREE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DyndnsfreeConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"dyndnsfree\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "DYNDNSFREE_PASSWORD":
			c.Password = val
		case "username", "DYNDNSFREE_USERNAME":
			c.Username = val
		case "httpTimeout", "DYNDNSFREE_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "DYNDNSFREE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DYNDNSFREE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"dyndnsfree\"", key)
		}
	}
	return nil
}
