// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// CivoConfig holds configuration for the "civo" DNS provider (Civo)
// See https://civo.com
type CivoConfig struct {
	Token              string // CIVO_TOKEN: Authentication token
	PollingInterval    string // CIVO_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 30)
	PropagationTimeout string // CIVO_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 300)
	TTL                string // CIVO_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *CivoConfig) envVars() map[string]string {
	m := make(map[string]string, 4)
	if c.Token != "" {
		m["CIVO_TOKEN"] = c.Token
	}
	if c.PollingInterval != "" {
		m["CIVO_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["CIVO_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["CIVO_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *CivoConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"civo\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "CIVO_TOKEN":
			c.Token = val
		case "pollingInterval", "CIVO_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CIVO_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "CIVO_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"civo\"", key)
		}
	}
	return nil
}
