// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// SakuracloudConfig holds configuration for the "sakuracloud" DNS provider (Sakura Cloud)
// See https://cloud.sakura.ad.jp/
type SakuracloudConfig struct {
	AccessToken        string // SAKURACLOUD_ACCESS_TOKEN: Access token
	AccessTokenSecret  string // SAKURACLOUD_ACCESS_TOKEN_SECRET: Access token secret
	HTTPTimeout        string // SAKURACLOUD_HTTP_TIMEOUT: API request timeout in seconds (Default: 10)
	PollingInterval    string // SAKURACLOUD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // SAKURACLOUD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // SAKURACLOUD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *SakuracloudConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.AccessToken != "" {
		m["SAKURACLOUD_ACCESS_TOKEN"] = c.AccessToken
	}
	if c.AccessTokenSecret != "" {
		m["SAKURACLOUD_ACCESS_TOKEN_SECRET"] = c.AccessTokenSecret
	}
	if c.HTTPTimeout != "" {
		m["SAKURACLOUD_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["SAKURACLOUD_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["SAKURACLOUD_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["SAKURACLOUD_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *SakuracloudConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"sakuracloud\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessToken", "SAKURACLOUD_ACCESS_TOKEN":
			c.AccessToken = val
		case "accessTokenSecret", "SAKURACLOUD_ACCESS_TOKEN_SECRET":
			c.AccessTokenSecret = val
		case "httpTimeout", "SAKURACLOUD_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "SAKURACLOUD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "SAKURACLOUD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "SAKURACLOUD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"sakuracloud\"", key)
		}
	}
	return nil
}
