// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/iij"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// IijConfig holds configuration for the "iij" DNS provider (Internet Initiative Japan)
// See https://www.iij.ad.jp/en/
type IijConfig struct {
	APIAccessKey       string // IIJ_API_ACCESS_KEY: API access key
	APISecretKey       string // IIJ_API_SECRET_KEY: API secret key
	DoServiceCode      string // IIJ_DO_SERVICE_CODE: DO service code
	PollingInterval    string // IIJ_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 4)
	PropagationTimeout string // IIJ_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 240)
	TTL                string // IIJ_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *IijConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIAccessKey != "" {
		cfg.AccessKey = c.APIAccessKey
	}
	if c.APISecretKey != "" {
		cfg.SecretKey = c.APISecretKey
	}
	if c.DoServiceCode != "" {
		cfg.DoServiceCode = c.DoServiceCode
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *IijConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"iij\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiAccessKey", "IIJ_API_ACCESS_KEY":
			c.APIAccessKey = val
		case "apiSecretKey", "IIJ_API_SECRET_KEY":
			c.APISecretKey = val
		case "doServiceCode", "IIJ_DO_SERVICE_CODE":
			c.DoServiceCode = val
		case "pollingInterval", "IIJ_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "IIJ_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "IIJ_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"iij\"", key)
		}
	}
	return nil
}
