// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DnsmadeeasyConfig holds configuration for the "dnsmadeeasy" DNS provider (DNS Made Easy)
// See https://dnsmadeeasy.com/
type DnsmadeeasyConfig struct {
	APIKey             string // DNSMADEEASY_API_KEY: The API key
	APISecret          string // DNSMADEEASY_API_SECRET: The API Secret key
	HTTPTimeout        string // DNSMADEEASY_HTTP_TIMEOUT: API request timeout in seconds (Default: 10)
	PollingInterval    string // DNSMADEEASY_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // DNSMADEEASY_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	Sandbox            string // DNSMADEEASY_SANDBOX: Activate the sandbox (boolean)
	TTL                string // DNSMADEEASY_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *DnsmadeeasyConfig) envVars() map[string]string {
	m := make(map[string]string, 7)
	if c.APIKey != "" {
		m["DNSMADEEASY_API_KEY"] = c.APIKey
	}
	if c.APISecret != "" {
		m["DNSMADEEASY_API_SECRET"] = c.APISecret
	}
	if c.HTTPTimeout != "" {
		m["DNSMADEEASY_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["DNSMADEEASY_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["DNSMADEEASY_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.Sandbox != "" {
		m["DNSMADEEASY_SANDBOX"] = c.Sandbox
	}
	if c.TTL != "" {
		m["DNSMADEEASY_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DnsmadeeasyConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"dnsmadeeasy\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "DNSMADEEASY_API_KEY":
			c.APIKey = val
		case "apiSecret", "DNSMADEEASY_API_SECRET":
			c.APISecret = val
		case "httpTimeout", "DNSMADEEASY_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "DNSMADEEASY_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DNSMADEEASY_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sandbox", "DNSMADEEASY_SANDBOX":
			c.Sandbox = val
		case "ttl", "DNSMADEEASY_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"dnsmadeeasy\"", key)
		}
	}
	return nil
}
