// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/auroradns"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AuroradnsConfig holds configuration for the "auroradns" DNS provider (Aurora DNS)
// See https://www.pcextreme.com/dns-health-checks
type AuroradnsConfig struct {
	APIKey             string // AURORA_API_KEY: API key or username to used
	Secret             string // AURORA_SECRET: Secret password to be used
	Endpoint           string // AURORA_ENDPOINT: API endpoint URL
	PollingInterval    string // AURORA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // AURORA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // AURORA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *AuroradnsConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.Secret != "" {
		cfg.Secret = c.Secret
	}
	if c.Endpoint != "" {
		cfg.BaseURL = c.Endpoint
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AuroradnsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"auroradns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "AURORA_API_KEY":
			c.APIKey = val
		case "secret", "AURORA_SECRET":
			c.Secret = val
		case "endpoint", "AURORA_ENDPOINT":
			c.Endpoint = val
		case "pollingInterval", "AURORA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "AURORA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "AURORA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"auroradns\"", key)
		}
	}
	return nil
}
