// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DirectadminConfig holds configuration for the "directadmin" DNS provider (DirectAdmin)
// See https://www.directadmin.com
type DirectadminConfig struct {
	APIURL             string // DIRECTADMIN_API_URL: URL of the API
	Password           string // DIRECTADMIN_PASSWORD: API password
	Username           string // DIRECTADMIN_USERNAME: API username
	HTTPTimeout        string // DIRECTADMIN_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // DIRECTADMIN_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 5)
	PropagationTimeout string // DIRECTADMIN_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // DIRECTADMIN_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 30)
	ZoneName           string // DIRECTADMIN_ZONE_NAME: Zone name used to add the TXT record
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *DirectadminConfig) envVars() map[string]string {
	m := make(map[string]string, 8)
	if c.APIURL != "" {
		m["DIRECTADMIN_API_URL"] = c.APIURL
	}
	if c.Password != "" {
		m["DIRECTADMIN_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["DIRECTADMIN_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["DIRECTADMIN_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["DIRECTADMIN_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["DIRECTADMIN_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["DIRECTADMIN_TTL"] = c.TTL
	}
	if c.ZoneName != "" {
		m["DIRECTADMIN_ZONE_NAME"] = c.ZoneName
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DirectadminConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"directadmin\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiURL", "DIRECTADMIN_API_URL":
			c.APIURL = val
		case "password", "DIRECTADMIN_PASSWORD":
			c.Password = val
		case "username", "DIRECTADMIN_USERNAME":
			c.Username = val
		case "httpTimeout", "DIRECTADMIN_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "DIRECTADMIN_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DIRECTADMIN_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "DIRECTADMIN_TTL":
			c.TTL = val
		case "zoneName", "DIRECTADMIN_ZONE_NAME":
			c.ZoneName = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"directadmin\"", key)
		}
	}
	return nil
}
