// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// VultrConfig holds configuration for the "vultr" DNS provider (Vultr)
// See https://www.vultr.com/
type VultrConfig struct {
	APIKey             string // VULTR_API_KEY: API key
	HTTPTimeout        string // VULTR_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // VULTR_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // VULTR_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // VULTR_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *VultrConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.APIKey != "" {
		m["VULTR_API_KEY"] = c.APIKey
	}
	if c.HTTPTimeout != "" {
		m["VULTR_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["VULTR_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["VULTR_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["VULTR_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *VultrConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"vultr\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "VULTR_API_KEY":
			c.APIKey = val
		case "httpTimeout", "VULTR_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "VULTR_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "VULTR_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "VULTR_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"vultr\"", key)
		}
	}
	return nil
}
