// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// MittwaldConfig holds configuration for the "mittwald" DNS provider (Mittwald)
// See https://www.mittwald.de/
type MittwaldConfig struct {
	Token              string // MITTWALD_TOKEN: API token
	HTTPTimeout        string // MITTWALD_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // MITTWALD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // MITTWALD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	SequenceInterval   string // MITTWALD_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 120)
	TTL                string // MITTWALD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *MittwaldConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.Token != "" {
		m["MITTWALD_TOKEN"] = c.Token
	}
	if c.HTTPTimeout != "" {
		m["MITTWALD_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["MITTWALD_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["MITTWALD_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SequenceInterval != "" {
		m["MITTWALD_SEQUENCE_INTERVAL"] = c.SequenceInterval
	}
	if c.TTL != "" {
		m["MITTWALD_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *MittwaldConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"mittwald\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "MITTWALD_TOKEN":
			c.Token = val
		case "httpTimeout", "MITTWALD_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "MITTWALD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "MITTWALD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "MITTWALD_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "MITTWALD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"mittwald\"", key)
		}
	}
	return nil
}
