// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/mittwald"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// MittwaldConfig holds configuration for the "mittwald" DNS provider (Mittwald)
// See https://www.mittwald.de/
type MittwaldConfig struct {
	Token              string // MITTWALD_TOKEN: API token
	PollingInterval    string // MITTWALD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // MITTWALD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	SequenceInterval   string // MITTWALD_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 120)
	TTL                string // MITTWALD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *MittwaldConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Token != "" {
		cfg.Token = c.Token
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.SequenceInterval != "" {
		v, err := strconv.Atoi(c.SequenceInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"sequenceInterval\": %w", err)
		}
		cfg.SequenceInterval = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *MittwaldConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"mittwald\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "MITTWALD_TOKEN":
			c.Token = val
		case "pollingInterval", "MITTWALD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "MITTWALD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "MITTWALD_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "MITTWALD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"mittwald\"", key)
		}
	}
	return nil
}
