// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DuckdnsConfig holds configuration for the "duckdns" DNS provider (Duck DNS)
// See https://www.duckdns.org/
type DuckdnsConfig struct {
	Token              string // DUCKDNS_TOKEN: Account token
	HTTPTimeout        string // DUCKDNS_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // DUCKDNS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // DUCKDNS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SequenceInterval   string // DUCKDNS_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *DuckdnsConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.Token != "" {
		m["DUCKDNS_TOKEN"] = c.Token
	}
	if c.HTTPTimeout != "" {
		m["DUCKDNS_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["DUCKDNS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["DUCKDNS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SequenceInterval != "" {
		m["DUCKDNS_SEQUENCE_INTERVAL"] = c.SequenceInterval
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DuckdnsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"duckdns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "DUCKDNS_TOKEN":
			c.Token = val
		case "httpTimeout", "DUCKDNS_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "DUCKDNS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DUCKDNS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "DUCKDNS_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"duckdns\"", key)
		}
	}
	return nil
}
