// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// ConohaConfig holds configuration for the "conoha" DNS provider (ConoHa v2)
// See https://www.conoha.jp/
type ConohaConfig struct {
	APIPassword        string // CONOHA_API_PASSWORD: The API password
	APIUsername        string // CONOHA_API_USERNAME: The API username
	TenantID           string // CONOHA_TENANT_ID: Tenant ID
	HTTPTimeout        string // CONOHA_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // CONOHA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // CONOHA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	Region             string // CONOHA_REGION: The region (Default: tyo1)
	TTL                string // CONOHA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *ConohaConfig) envVars() map[string]string {
	m := make(map[string]string, 8)
	if c.APIPassword != "" {
		m["CONOHA_API_PASSWORD"] = c.APIPassword
	}
	if c.APIUsername != "" {
		m["CONOHA_API_USERNAME"] = c.APIUsername
	}
	if c.TenantID != "" {
		m["CONOHA_TENANT_ID"] = c.TenantID
	}
	if c.HTTPTimeout != "" {
		m["CONOHA_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["CONOHA_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["CONOHA_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.Region != "" {
		m["CONOHA_REGION"] = c.Region
	}
	if c.TTL != "" {
		m["CONOHA_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *ConohaConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"conoha\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiPassword", "CONOHA_API_PASSWORD":
			c.APIPassword = val
		case "apiUsername", "CONOHA_API_USERNAME":
			c.APIUsername = val
		case "tenantID", "CONOHA_TENANT_ID":
			c.TenantID = val
		case "httpTimeout", "CONOHA_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "CONOHA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CONOHA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "region", "CONOHA_REGION":
			c.Region = val
		case "ttl", "CONOHA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"conoha\"", key)
		}
	}
	return nil
}
