// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// BinarylaneConfig holds configuration for the "binarylane" DNS provider (Binary Lane)
// See https://www.binarylane.com.au/
type BinarylaneConfig struct {
	APIToken           string // BINARYLANE_API_TOKEN: API token
	HTTPTimeout        string // BINARYLANE_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // BINARYLANE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // BINARYLANE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // BINARYLANE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *BinarylaneConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.APIToken != "" {
		m["BINARYLANE_API_TOKEN"] = c.APIToken
	}
	if c.HTTPTimeout != "" {
		m["BINARYLANE_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["BINARYLANE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["BINARYLANE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["BINARYLANE_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *BinarylaneConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"binarylane\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiToken", "BINARYLANE_API_TOKEN":
			c.APIToken = val
		case "httpTimeout", "BINARYLANE_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "BINARYLANE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "BINARYLANE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "BINARYLANE_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"binarylane\"", key)
		}
	}
	return nil
}
