// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// OcteniumConfig holds configuration for the "octenium" DNS provider (Octenium)
// See https://octenium.com/
type OcteniumConfig struct {
	APIKey             string // OCTENIUM_API_KEY: API key
	HTTPTimeout        string // OCTENIUM_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // OCTENIUM_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // OCTENIUM_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // OCTENIUM_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *OcteniumConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.APIKey != "" {
		m["OCTENIUM_API_KEY"] = c.APIKey
	}
	if c.HTTPTimeout != "" {
		m["OCTENIUM_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["OCTENIUM_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["OCTENIUM_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["OCTENIUM_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *OcteniumConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"octenium\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "OCTENIUM_API_KEY":
			c.APIKey = val
		case "httpTimeout", "OCTENIUM_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "OCTENIUM_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "OCTENIUM_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "OCTENIUM_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"octenium\"", key)
		}
	}
	return nil
}
