// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// VegadnsConfig holds configuration for the "vegadns" DNS provider (VegaDNS)
// See https://github.com/shupp/VegaDNS-API
type VegadnsConfig struct {
	VegadnsKey         string // SECRET_VEGADNS_KEY: API key
	VegadnsSecret      string // SECRET_VEGADNS_SECRET: API secret
	URL                string // VEGADNS_URL: API endpoint URL
	PollingInterval    string // VEGADNS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 60)
	PropagationTimeout string // VEGADNS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 720)
	TTL                string // VEGADNS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 10)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *VegadnsConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.VegadnsKey != "" {
		m["SECRET_VEGADNS_KEY"] = c.VegadnsKey
	}
	if c.VegadnsSecret != "" {
		m["SECRET_VEGADNS_SECRET"] = c.VegadnsSecret
	}
	if c.URL != "" {
		m["VEGADNS_URL"] = c.URL
	}
	if c.PollingInterval != "" {
		m["VEGADNS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["VEGADNS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["VEGADNS_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *VegadnsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"vegadns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "vegadnsKey", "SECRET_VEGADNS_KEY":
			c.VegadnsKey = val
		case "vegadnsSecret", "SECRET_VEGADNS_SECRET":
			c.VegadnsSecret = val
		case "url", "VEGADNS_URL":
			c.URL = val
		case "pollingInterval", "VEGADNS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "VEGADNS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "VEGADNS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"vegadns\"", key)
		}
	}
	return nil
}
