// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/digitalocean"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DigitaloceanConfig holds configuration for the "digitalocean" DNS provider (Digital Ocean)
// See https://www.digitalocean.com/docs/networking/dns/
type DigitaloceanConfig struct {
	AuthToken          string // DO_AUTH_TOKEN: Authentication token
	APIURL             string // DO_API_URL: The URL of the API
	PollingInterval    string // DO_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 5)
	PropagationTimeout string // DO_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // DO_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 30)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *DigitaloceanConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.AuthToken != "" {
		cfg.AuthToken = c.AuthToken
	}
	if c.APIURL != "" {
		cfg.BaseURL = c.APIURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DigitaloceanConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"digitalocean\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "authToken", "DO_AUTH_TOKEN":
			c.AuthToken = val
		case "apiURL", "DO_API_URL":
			c.APIURL = val
		case "pollingInterval", "DO_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DO_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "DO_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"digitalocean\"", key)
		}
	}
	return nil
}
