// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// F5xcConfig holds configuration for the "f5xc" DNS provider (F5 XC)
// See https://www.f5.com/products/distributed-cloud-services
type F5xcConfig struct {
	APIToken           string // F5XC_API_TOKEN: API token
	GroupName          string // F5XC_GROUP_NAME: Group name
	TenantName         string // F5XC_TENANT_NAME: XC Tenant shortname
	HTTPTimeout        string // F5XC_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // F5XC_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // F5XC_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	Server             string // F5XC_SERVER: Server domain (Default: console.ves.volterra.io)
	TTL                string // F5XC_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *F5xcConfig) envVars() map[string]string {
	m := make(map[string]string, 8)
	if c.APIToken != "" {
		m["F5XC_API_TOKEN"] = c.APIToken
	}
	if c.GroupName != "" {
		m["F5XC_GROUP_NAME"] = c.GroupName
	}
	if c.TenantName != "" {
		m["F5XC_TENANT_NAME"] = c.TenantName
	}
	if c.HTTPTimeout != "" {
		m["F5XC_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["F5XC_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["F5XC_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.Server != "" {
		m["F5XC_SERVER"] = c.Server
	}
	if c.TTL != "" {
		m["F5XC_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *F5xcConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"f5xc\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiToken", "F5XC_API_TOKEN":
			c.APIToken = val
		case "groupName", "F5XC_GROUP_NAME":
			c.GroupName = val
		case "tenantName", "F5XC_TENANT_NAME":
			c.TenantName = val
		case "httpTimeout", "F5XC_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "F5XC_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "F5XC_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "server", "F5XC_SERVER":
			c.Server = val
		case "ttl", "F5XC_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"f5xc\"", key)
		}
	}
	return nil
}
