// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/liquidweb"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// LiquidwebConfig holds configuration for the "liquidweb" DNS provider (Liquid Web)
// See https://liquidweb.com
type LiquidwebConfig struct {
	Password           string // LWAPI_PASSWORD: Liquid Web API Password
	Username           string // LWAPI_USERNAME: Liquid Web API Username
	HTTPTimeout        string // LWAPI_HTTP_TIMEOUT: API request timeout in seconds (Default: 60)
	PollingInterval    string // LWAPI_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // LWAPI_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // LWAPI_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
	Zone               string // LWAPI_ZONE: DNS Zone
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *LiquidwebConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.HTTPTimeout != "" {
		v, err := strconv.Atoi(c.HTTPTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"httpTimeout\": %w", err)
		}
		cfg.HTTPTimeout = time.Duration(v) * time.Second
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	if c.Zone != "" {
		cfg.Zone = c.Zone
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *LiquidwebConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"liquidweb\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "LWAPI_PASSWORD":
			c.Password = val
		case "username", "LWAPI_USERNAME":
			c.Username = val
		case "httpTimeout", "LWAPI_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "LWAPI_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "LWAPI_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "LWAPI_TTL":
			c.TTL = val
		case "zone", "LWAPI_ZONE":
			c.Zone = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"liquidweb\"", key)
		}
	}
	return nil
}
