// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Route53Config holds configuration for the "route53" DNS provider (Amazon Route 53)
// See https://aws.amazon.com/route53/
type Route53Config struct {
	AccessKeyID              string // AWS_ACCESS_KEY_ID: Managed by the AWS client. Access key ID (`AWS_ACCESS_KEY_ID_FILE` is not supported, use `AWS_SHARED_CREDENTIALS_FILE` instead)
	AssumeRoleARN            string // AWS_ASSUME_ROLE_ARN: Managed by the AWS Role ARN (`AWS_ASSUME_ROLE_ARN_FILE` is not supported)
	ExternalID               string // AWS_EXTERNAL_ID: Managed by STS AssumeRole API operation (`AWS_EXTERNAL_ID_FILE` is not supported)
	HostedZoneID             string // AWS_HOSTED_ZONE_ID: Override the hosted zone ID.
	Profile                  string // AWS_PROFILE: Managed by the AWS client (`AWS_PROFILE_FILE` is not supported)
	Region                   string // AWS_REGION: Managed by the AWS client (`AWS_REGION_FILE` is not supported)
	SDKLoadConfig            string // AWS_SDK_LOAD_CONFIG: Managed by the AWS client. Retrieve the region from the CLI config file (`AWS_SDK_LOAD_CONFIG_FILE` is not supported)
	SecretAccessKey          string // AWS_SECRET_ACCESS_KEY: Managed by the AWS client. Secret access key (`AWS_SECRET_ACCESS_KEY_FILE` is not supported, use `AWS_SHARED_CREDENTIALS_FILE` instead)
	WaitForRecordSetsChanged string // AWS_WAIT_FOR_RECORD_SETS_CHANGED: Wait for changes to be INSYNC (it can be unstable)
	MaxRetries               string // AWS_MAX_RETRIES: The number of maximum returns the service will use to make an individual API request
	PollingInterval          string // AWS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 4)
	PrivateZone              string // AWS_PRIVATE_ZONE: Set to true to use private zones only (default: use public zones only)
	PropagationTimeout       string // AWS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	SharedCredentialsFile    string // AWS_SHARED_CREDENTIALS_FILE: Managed by the AWS client. Shared credentials file.
	TTL                      string // AWS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 10)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *Route53Config) envVars() map[string]string {
	m := make(map[string]string, 15)
	if c.AccessKeyID != "" {
		m["AWS_ACCESS_KEY_ID"] = c.AccessKeyID
	}
	if c.AssumeRoleARN != "" {
		m["AWS_ASSUME_ROLE_ARN"] = c.AssumeRoleARN
	}
	if c.ExternalID != "" {
		m["AWS_EXTERNAL_ID"] = c.ExternalID
	}
	if c.HostedZoneID != "" {
		m["AWS_HOSTED_ZONE_ID"] = c.HostedZoneID
	}
	if c.Profile != "" {
		m["AWS_PROFILE"] = c.Profile
	}
	if c.Region != "" {
		m["AWS_REGION"] = c.Region
	}
	if c.SDKLoadConfig != "" {
		m["AWS_SDK_LOAD_CONFIG"] = c.SDKLoadConfig
	}
	if c.SecretAccessKey != "" {
		m["AWS_SECRET_ACCESS_KEY"] = c.SecretAccessKey
	}
	if c.WaitForRecordSetsChanged != "" {
		m["AWS_WAIT_FOR_RECORD_SETS_CHANGED"] = c.WaitForRecordSetsChanged
	}
	if c.MaxRetries != "" {
		m["AWS_MAX_RETRIES"] = c.MaxRetries
	}
	if c.PollingInterval != "" {
		m["AWS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PrivateZone != "" {
		m["AWS_PRIVATE_ZONE"] = c.PrivateZone
	}
	if c.PropagationTimeout != "" {
		m["AWS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SharedCredentialsFile != "" {
		m["AWS_SHARED_CREDENTIALS_FILE"] = c.SharedCredentialsFile
	}
	if c.TTL != "" {
		m["AWS_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Route53Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"route53\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessKeyID", "AWS_ACCESS_KEY_ID":
			c.AccessKeyID = val
		case "assumeRoleARN", "AWS_ASSUME_ROLE_ARN":
			c.AssumeRoleARN = val
		case "externalID", "AWS_EXTERNAL_ID":
			c.ExternalID = val
		case "hostedZoneID", "AWS_HOSTED_ZONE_ID":
			c.HostedZoneID = val
		case "profile", "AWS_PROFILE":
			c.Profile = val
		case "region", "AWS_REGION":
			c.Region = val
		case "sdkLoadConfig", "AWS_SDK_LOAD_CONFIG":
			c.SDKLoadConfig = val
		case "secretAccessKey", "AWS_SECRET_ACCESS_KEY":
			c.SecretAccessKey = val
		case "waitForRecordSetsChanged", "AWS_WAIT_FOR_RECORD_SETS_CHANGED":
			c.WaitForRecordSetsChanged = val
		case "maxRetries", "AWS_MAX_RETRIES":
			c.MaxRetries = val
		case "pollingInterval", "AWS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "privateZone", "AWS_PRIVATE_ZONE":
			c.PrivateZone = val
		case "propagationTimeout", "AWS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sharedCredentialsFile", "AWS_SHARED_CREDENTIALS_FILE":
			c.SharedCredentialsFile = val
		case "ttl", "AWS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"route53\"", key)
		}
	}
	return nil
}
