// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// CzechiaConfig holds configuration for the "czechia" DNS provider (Czechia)
// See https://www.czechia.com/
type CzechiaConfig struct {
	Token              string // CZECHIA_TOKEN: Authorization token
	HTTPTimeout        string // CZECHIA_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // CZECHIA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // CZECHIA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // CZECHIA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *CzechiaConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.Token != "" {
		m["CZECHIA_TOKEN"] = c.Token
	}
	if c.HTTPTimeout != "" {
		m["CZECHIA_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["CZECHIA_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["CZECHIA_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["CZECHIA_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *CzechiaConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"czechia\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "CZECHIA_TOKEN":
			c.Token = val
		case "httpTimeout", "CZECHIA_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "CZECHIA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CZECHIA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "CZECHIA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"czechia\"", key)
		}
	}
	return nil
}
