// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/wedos"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// WedosConfig holds configuration for the "wedos" DNS provider (WEDOS)
// See https://www.wedos.com
type WedosConfig struct {
	Username           string // WEDOS_USERNAME: Username is the same as for the admin account
	WAPIPassword       string // WEDOS_WAPI_PASSWORD: Password needs to be generated and IP allowed in the admin interface
	PollingInterval    string // WEDOS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // WEDOS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 600)
	TTL                string // WEDOS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *WedosConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.WAPIPassword != "" {
		cfg.Password = c.WAPIPassword
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *WedosConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"wedos\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "username", "WEDOS_USERNAME":
			c.Username = val
		case "wapiPassword", "WEDOS_WAPI_PASSWORD":
			c.WAPIPassword = val
		case "pollingInterval", "WEDOS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "WEDOS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "WEDOS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"wedos\"", key)
		}
	}
	return nil
}
