// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/directadmin"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DirectadminConfig holds configuration for the "directadmin" DNS provider (DirectAdmin)
// See https://www.directadmin.com
type DirectadminConfig struct {
	APIURL             string // DIRECTADMIN_API_URL: URL of the API
	Password           string // DIRECTADMIN_PASSWORD: API password
	Username           string // DIRECTADMIN_USERNAME: API username
	PollingInterval    string // DIRECTADMIN_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 5)
	PropagationTimeout string // DIRECTADMIN_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // DIRECTADMIN_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 30)
	ZoneName           string // DIRECTADMIN_ZONE_NAME: Zone name used to add the TXT record
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *DirectadminConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIURL != "" {
		cfg.BaseURL = c.APIURL
	}
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	if c.ZoneName != "" {
		cfg.ZoneName = c.ZoneName
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DirectadminConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"directadmin\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiURL", "DIRECTADMIN_API_URL":
			c.APIURL = val
		case "password", "DIRECTADMIN_PASSWORD":
			c.Password = val
		case "username", "DIRECTADMIN_USERNAME":
			c.Username = val
		case "pollingInterval", "DIRECTADMIN_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DIRECTADMIN_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "DIRECTADMIN_TTL":
			c.TTL = val
		case "zoneName", "DIRECTADMIN_ZONE_NAME":
			c.ZoneName = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"directadmin\"", key)
		}
	}
	return nil
}
