// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// GoogledomainsConfig holds configuration for the "googledomains" DNS provider (Google Domains)
// See https://github.com/go-acme/lego/issues/2553
type GoogledomainsConfig struct {
	DomainsAccessToken        string // GOOGLE_DOMAINS_ACCESS_TOKEN: Access token
	DomainsHTTPTimeout        string // GOOGLE_DOMAINS_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	DomainsPollingInterval    string // GOOGLE_DOMAINS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	DomainsPropagationTimeout string // GOOGLE_DOMAINS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *GoogledomainsConfig) envVars() map[string]string {
	m := make(map[string]string, 4)
	if c.DomainsAccessToken != "" {
		m["GOOGLE_DOMAINS_ACCESS_TOKEN"] = c.DomainsAccessToken
	}
	if c.DomainsHTTPTimeout != "" {
		m["GOOGLE_DOMAINS_HTTP_TIMEOUT"] = c.DomainsHTTPTimeout
	}
	if c.DomainsPollingInterval != "" {
		m["GOOGLE_DOMAINS_POLLING_INTERVAL"] = c.DomainsPollingInterval
	}
	if c.DomainsPropagationTimeout != "" {
		m["GOOGLE_DOMAINS_PROPAGATION_TIMEOUT"] = c.DomainsPropagationTimeout
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *GoogledomainsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"googledomains\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "domainsAccessToken", "GOOGLE_DOMAINS_ACCESS_TOKEN":
			c.DomainsAccessToken = val
		case "domainsHTTPTimeout", "GOOGLE_DOMAINS_HTTP_TIMEOUT":
			c.DomainsHTTPTimeout = val
		case "domainsPollingInterval", "GOOGLE_DOMAINS_POLLING_INTERVAL":
			c.DomainsPollingInterval = val
		case "domainsPropagationTimeout", "GOOGLE_DOMAINS_PROPAGATION_TIMEOUT":
			c.DomainsPropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"googledomains\"", key)
		}
	}
	return nil
}
