// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/namesurfer"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// NamesurferConfig holds configuration for the "namesurfer" DNS provider (FusionLayer NameSurfer)
// See https://www.fusionlayer.com/
type NamesurferConfig struct {
	APIKey             string // NAMESURFER_API_KEY: API key name
	APISecret          string // NAMESURFER_API_SECRET: API secret
	BaseURL            string // NAMESURFER_BASE_URL: The base URL of NameSurfer API (jsonrpc10) endpoint URL (e.g., https://foo.example.com:8443/API/NSService_10)
	PollingInterval    string // NAMESURFER_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // NAMESURFER_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // NAMESURFER_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
	View               string // NAMESURFER_VIEW: DNS view name (optional, default: empty string)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *NamesurferConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.APISecret != "" {
		cfg.APISecret = c.APISecret
	}
	if c.BaseURL != "" {
		cfg.BaseURL = c.BaseURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	if c.View != "" {
		cfg.View = c.View
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *NamesurferConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"namesurfer\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "NAMESURFER_API_KEY":
			c.APIKey = val
		case "apiSecret", "NAMESURFER_API_SECRET":
			c.APISecret = val
		case "baseURL", "NAMESURFER_BASE_URL":
			c.BaseURL = val
		case "pollingInterval", "NAMESURFER_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "NAMESURFER_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "NAMESURFER_TTL":
			c.TTL = val
		case "view", "NAMESURFER_VIEW":
			c.View = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"namesurfer\"", key)
		}
	}
	return nil
}
