// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// InfobloxConfig holds configuration for the "infoblox" DNS provider (Infoblox)
// See https://www.infoblox.com/
type InfobloxConfig struct {
	Host               string // INFOBLOX_HOST: Host URI
	Password           string // INFOBLOX_PASSWORD: Account Password
	Username           string // INFOBLOX_USERNAME: Account Username
	CACertificate      string // INFOBLOX_CA_CERTIFICATE: The path to the CA certificate (PEM encoded)
	DNSView            string // INFOBLOX_DNS_VIEW: The view for the TXT records (Default: External)
	HTTPTimeout        string // INFOBLOX_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // INFOBLOX_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	Port               string // INFOBLOX_PORT: The port for the infoblox grid manager (Default: 443)
	PropagationTimeout string // INFOBLOX_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SSLVerify          string // INFOBLOX_SSL_VERIFY: Whether or not to verify the TLS certificate (Default: true)
	TTL                string // INFOBLOX_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
	WAPIVersion        string // INFOBLOX_WAPI_VERSION: The version of WAPI being used (Default: 2.11)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *InfobloxConfig) envVars() map[string]string {
	m := make(map[string]string, 12)
	if c.Host != "" {
		m["INFOBLOX_HOST"] = c.Host
	}
	if c.Password != "" {
		m["INFOBLOX_PASSWORD"] = c.Password
	}
	if c.Username != "" {
		m["INFOBLOX_USERNAME"] = c.Username
	}
	if c.CACertificate != "" {
		m["INFOBLOX_CA_CERTIFICATE"] = c.CACertificate
	}
	if c.DNSView != "" {
		m["INFOBLOX_DNS_VIEW"] = c.DNSView
	}
	if c.HTTPTimeout != "" {
		m["INFOBLOX_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["INFOBLOX_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.Port != "" {
		m["INFOBLOX_PORT"] = c.Port
	}
	if c.PropagationTimeout != "" {
		m["INFOBLOX_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SSLVerify != "" {
		m["INFOBLOX_SSL_VERIFY"] = c.SSLVerify
	}
	if c.TTL != "" {
		m["INFOBLOX_TTL"] = c.TTL
	}
	if c.WAPIVersion != "" {
		m["INFOBLOX_WAPI_VERSION"] = c.WAPIVersion
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *InfobloxConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"infoblox\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "host", "INFOBLOX_HOST":
			c.Host = val
		case "password", "INFOBLOX_PASSWORD":
			c.Password = val
		case "username", "INFOBLOX_USERNAME":
			c.Username = val
		case "caCertificate", "INFOBLOX_CA_CERTIFICATE":
			c.CACertificate = val
		case "dnsView", "INFOBLOX_DNS_VIEW":
			c.DNSView = val
		case "httpTimeout", "INFOBLOX_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "INFOBLOX_POLLING_INTERVAL":
			c.PollingInterval = val
		case "port", "INFOBLOX_PORT":
			c.Port = val
		case "propagationTimeout", "INFOBLOX_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sslVerify", "INFOBLOX_SSL_VERIFY":
			c.SSLVerify = val
		case "ttl", "INFOBLOX_TTL":
			c.TTL = val
		case "wapiVersion", "INFOBLOX_WAPI_VERSION":
			c.WAPIVersion = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"infoblox\"", key)
		}
	}
	return nil
}
