// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// IspconfigConfig holds configuration for the "ispconfig" DNS provider (ISPConfig 3)
// See https://www.ispconfig.org/
type IspconfigConfig struct {
	Password           string // ISPCONFIG_PASSWORD: Password
	ServerURL          string // ISPCONFIG_SERVER_URL: Server URL
	Username           string // ISPCONFIG_USERNAME: Username
	HTTPTimeout        string // ISPCONFIG_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	InsecureSkipVerify string // ISPCONFIG_INSECURE_SKIP_VERIFY: Whether to verify the API certificate
	PollingInterval    string // ISPCONFIG_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // ISPCONFIG_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // ISPCONFIG_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *IspconfigConfig) envVars() map[string]string {
	m := make(map[string]string, 8)
	if c.Password != "" {
		m["ISPCONFIG_PASSWORD"] = c.Password
	}
	if c.ServerURL != "" {
		m["ISPCONFIG_SERVER_URL"] = c.ServerURL
	}
	if c.Username != "" {
		m["ISPCONFIG_USERNAME"] = c.Username
	}
	if c.HTTPTimeout != "" {
		m["ISPCONFIG_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.InsecureSkipVerify != "" {
		m["ISPCONFIG_INSECURE_SKIP_VERIFY"] = c.InsecureSkipVerify
	}
	if c.PollingInterval != "" {
		m["ISPCONFIG_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["ISPCONFIG_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["ISPCONFIG_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *IspconfigConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"ispconfig\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "ISPCONFIG_PASSWORD":
			c.Password = val
		case "serverURL", "ISPCONFIG_SERVER_URL":
			c.ServerURL = val
		case "username", "ISPCONFIG_USERNAME":
			c.Username = val
		case "httpTimeout", "ISPCONFIG_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "insecureSkipVerify", "ISPCONFIG_INSECURE_SKIP_VERIFY":
			c.InsecureSkipVerify = val
		case "pollingInterval", "ISPCONFIG_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "ISPCONFIG_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "ISPCONFIG_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"ispconfig\"", key)
		}
	}
	return nil
}
