// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/dnsimple"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DnsimpleConfig holds configuration for the "dnsimple" DNS provider (DNSimple)
// See https://dnsimple.com/
type DnsimpleConfig struct {
	OAUTHToken         string // DNSIMPLE_OAUTH_TOKEN: OAuth token
	BaseURL            string // DNSIMPLE_BASE_URL: API endpoint URL
	PollingInterval    string // DNSIMPLE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // DNSIMPLE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // DNSIMPLE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *DnsimpleConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.OAUTHToken != "" {
		cfg.AccessToken = c.OAUTHToken
	}
	if c.BaseURL != "" {
		cfg.BaseURL = c.BaseURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DnsimpleConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"dnsimple\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "oauthToken", "DNSIMPLE_OAUTH_TOKEN":
			c.OAUTHToken = val
		case "baseURL", "DNSIMPLE_BASE_URL":
			c.BaseURL = val
		case "pollingInterval", "DNSIMPLE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DNSIMPLE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "DNSIMPLE_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"dnsimple\"", key)
		}
	}
	return nil
}
