// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/dreamhost"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DreamhostConfig holds configuration for the "dreamhost" DNS provider (DreamHost)
// See https://www.dreamhost.com
type DreamhostConfig struct {
	APIKey             string // DREAMHOST_API_KEY: The API key
	PollingInterval    string // DREAMHOST_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 60)
	PropagationTimeout string // DREAMHOST_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 3600)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *DreamhostConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DreamhostConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"dreamhost\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "DREAMHOST_API_KEY":
			c.APIKey = val
		case "pollingInterval", "DREAMHOST_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DREAMHOST_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"dreamhost\"", key)
		}
	}
	return nil
}
