// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// EdgednsConfig holds configuration for the "edgedns" DNS provider (Akamai EdgeDNS)
// See https://www.akamai.com/us/en/products/security/edge-dns.jsp
type EdgednsConfig struct {
	AccessToken        string // AKAMAI_ACCESS_TOKEN: Access token, managed by the Akamai EdgeGrid client
	ClientSecret       string // AKAMAI_CLIENT_SECRET: Client secret, managed by the Akamai EdgeGrid client
	ClientToken        string // AKAMAI_CLIENT_TOKEN: Client token, managed by the Akamai EdgeGrid client
	Edgerc             string // AKAMAI_EDGERC: Path to the .edgerc file, managed by the Akamai EdgeGrid client
	EdgercSection      string // AKAMAI_EDGERC_SECTION: Configuration section, managed by the Akamai EdgeGrid client
	Host               string // AKAMAI_HOST: API host, managed by the Akamai EdgeGrid client
	AccountSwitchKey   string // AKAMAI_ACCOUNT_SWITCH_KEY: Target account ID when the DNS zone and credentials belong to different accounts
	PollingInterval    string // AKAMAI_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 15)
	PropagationTimeout string // AKAMAI_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 180)
	TTL                string // AKAMAI_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *EdgednsConfig) envVars() map[string]string {
	m := make(map[string]string, 10)
	if c.AccessToken != "" {
		m["AKAMAI_ACCESS_TOKEN"] = c.AccessToken
	}
	if c.ClientSecret != "" {
		m["AKAMAI_CLIENT_SECRET"] = c.ClientSecret
	}
	if c.ClientToken != "" {
		m["AKAMAI_CLIENT_TOKEN"] = c.ClientToken
	}
	if c.Edgerc != "" {
		m["AKAMAI_EDGERC"] = c.Edgerc
	}
	if c.EdgercSection != "" {
		m["AKAMAI_EDGERC_SECTION"] = c.EdgercSection
	}
	if c.Host != "" {
		m["AKAMAI_HOST"] = c.Host
	}
	if c.AccountSwitchKey != "" {
		m["AKAMAI_ACCOUNT_SWITCH_KEY"] = c.AccountSwitchKey
	}
	if c.PollingInterval != "" {
		m["AKAMAI_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["AKAMAI_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["AKAMAI_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *EdgednsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"edgedns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessToken", "AKAMAI_ACCESS_TOKEN":
			c.AccessToken = val
		case "clientSecret", "AKAMAI_CLIENT_SECRET":
			c.ClientSecret = val
		case "clientToken", "AKAMAI_CLIENT_TOKEN":
			c.ClientToken = val
		case "edgerc", "AKAMAI_EDGERC":
			c.Edgerc = val
		case "edgercSection", "AKAMAI_EDGERC_SECTION":
			c.EdgercSection = val
		case "host", "AKAMAI_HOST":
			c.Host = val
		case "accountSwitchKey", "AKAMAI_ACCOUNT_SWITCH_KEY":
			c.AccountSwitchKey = val
		case "pollingInterval", "AKAMAI_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "AKAMAI_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "AKAMAI_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"edgedns\"", key)
		}
	}
	return nil
}
