// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// GcoreConfig holds configuration for the "gcore" DNS provider (G-Core)
// See https://gcore.com/dns/
type GcoreConfig struct {
	PermanentAPIToken  string // GCORE_PERMANENT_API_TOKEN: Permanent API token (https://gcore.com/blog/permanent-api-token-explained/)
	HTTPTimeout        string // GCORE_HTTP_TIMEOUT: API request timeout in seconds (Default: 10)
	PollingInterval    string // GCORE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 20)
	PropagationTimeout string // GCORE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 360)
	TTL                string // GCORE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *GcoreConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.PermanentAPIToken != "" {
		m["GCORE_PERMANENT_API_TOKEN"] = c.PermanentAPIToken
	}
	if c.HTTPTimeout != "" {
		m["GCORE_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["GCORE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["GCORE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["GCORE_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *GcoreConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"gcore\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "permanentAPIToken", "GCORE_PERMANENT_API_TOKEN":
			c.PermanentAPIToken = val
		case "httpTimeout", "GCORE_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "GCORE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "GCORE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "GCORE_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"gcore\"", key)
		}
	}
	return nil
}
