// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// CorenetworksConfig holds configuration for the "corenetworks" DNS provider (Core-Networks)
// See https://www.core-networks.de/
type CorenetworksConfig struct {
	Login              string // CORENETWORKS_LOGIN: The username of the API account
	Password           string // CORENETWORKS_PASSWORD: The password
	HTTPTimeout        string // CORENETWORKS_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // CORENETWORKS_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // CORENETWORKS_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SequenceInterval   string // CORENETWORKS_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 60)
	TTL                string // CORENETWORKS_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 3600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *CorenetworksConfig) envVars() map[string]string {
	m := make(map[string]string, 7)
	if c.Login != "" {
		m["CORENETWORKS_LOGIN"] = c.Login
	}
	if c.Password != "" {
		m["CORENETWORKS_PASSWORD"] = c.Password
	}
	if c.HTTPTimeout != "" {
		m["CORENETWORKS_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["CORENETWORKS_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["CORENETWORKS_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SequenceInterval != "" {
		m["CORENETWORKS_SEQUENCE_INTERVAL"] = c.SequenceInterval
	}
	if c.TTL != "" {
		m["CORENETWORKS_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *CorenetworksConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"corenetworks\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "login", "CORENETWORKS_LOGIN":
			c.Login = val
		case "password", "CORENETWORKS_PASSWORD":
			c.Password = val
		case "httpTimeout", "CORENETWORKS_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "CORENETWORKS_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CORENETWORKS_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "CORENETWORKS_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		case "ttl", "CORENETWORKS_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"corenetworks\"", key)
		}
	}
	return nil
}
