// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Bluecatv2Config holds configuration for the "bluecatv2" DNS provider (Bluecat v2)
// See https://www.bluecatnetworks.com
type Bluecatv2Config struct {
	ConfigName         string // BLUECATV2_CONFIG_NAME: Configuration name
	Password           string // BLUECATV2_PASSWORD: API password
	ServerURL          string // BLUECATV2_SERVER_URL: The server URL: it should have a scheme, hostname, and port (if required) of the authoritative Bluecat BAM serve
	Username           string // BLUECATV2_USERNAME: API username
	ViewName           string // BLUECATV2_VIEW_NAME: DNS View Name
	HTTPTimeout        string // BLUECATV2_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // BLUECATV2_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // BLUECATV2_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	SkipDeploy         string // BLUECATV2_SKIP_DEPLOY: Skip quick deployements
	TTL                string // BLUECATV2_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *Bluecatv2Config) envVars() map[string]string {
	m := make(map[string]string, 10)
	if c.ConfigName != "" {
		m["BLUECATV2_CONFIG_NAME"] = c.ConfigName
	}
	if c.Password != "" {
		m["BLUECATV2_PASSWORD"] = c.Password
	}
	if c.ServerURL != "" {
		m["BLUECATV2_SERVER_URL"] = c.ServerURL
	}
	if c.Username != "" {
		m["BLUECATV2_USERNAME"] = c.Username
	}
	if c.ViewName != "" {
		m["BLUECATV2_VIEW_NAME"] = c.ViewName
	}
	if c.HTTPTimeout != "" {
		m["BLUECATV2_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["BLUECATV2_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["BLUECATV2_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.SkipDeploy != "" {
		m["BLUECATV2_SKIP_DEPLOY"] = c.SkipDeploy
	}
	if c.TTL != "" {
		m["BLUECATV2_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Bluecatv2Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"bluecatv2\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "configName", "BLUECATV2_CONFIG_NAME":
			c.ConfigName = val
		case "password", "BLUECATV2_PASSWORD":
			c.Password = val
		case "serverURL", "BLUECATV2_SERVER_URL":
			c.ServerURL = val
		case "username", "BLUECATV2_USERNAME":
			c.Username = val
		case "viewName", "BLUECATV2_VIEW_NAME":
			c.ViewName = val
		case "httpTimeout", "BLUECATV2_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "BLUECATV2_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "BLUECATV2_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "skipDeploy", "BLUECATV2_SKIP_DEPLOY":
			c.SkipDeploy = val
		case "ttl", "BLUECATV2_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"bluecatv2\"", key)
		}
	}
	return nil
}
