// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// BaiducloudConfig holds configuration for the "baiducloud" DNS provider (Baidu Cloud)
// See https://cloud.baidu.com
type BaiducloudConfig struct {
	AccessKeyID        string // BAIDUCLOUD_ACCESS_KEY_ID: Access key
	SecretAccessKey    string // BAIDUCLOUD_SECRET_ACCESS_KEY: Secret access key
	PollingInterval    string // BAIDUCLOUD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // BAIDUCLOUD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // BAIDUCLOUD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *BaiducloudConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.AccessKeyID != "" {
		m["BAIDUCLOUD_ACCESS_KEY_ID"] = c.AccessKeyID
	}
	if c.SecretAccessKey != "" {
		m["BAIDUCLOUD_SECRET_ACCESS_KEY"] = c.SecretAccessKey
	}
	if c.PollingInterval != "" {
		m["BAIDUCLOUD_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["BAIDUCLOUD_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["BAIDUCLOUD_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *BaiducloudConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"baiducloud\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessKeyID", "BAIDUCLOUD_ACCESS_KEY_ID":
			c.AccessKeyID = val
		case "secretAccessKey", "BAIDUCLOUD_SECRET_ACCESS_KEY":
			c.SecretAccessKey = val
		case "pollingInterval", "BAIDUCLOUD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "BAIDUCLOUD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "BAIDUCLOUD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"baiducloud\"", key)
		}
	}
	return nil
}
