// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/keyhelp"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// KeyhelpConfig holds configuration for the "keyhelp" DNS provider (KeyHelp)
// See https://www.keyweb.de/en/keyhelp/keyhelp/
type KeyhelpConfig struct {
	APIKey             string // KEYHELP_API_KEY: API key
	BaseURL            string // KEYHELP_BASE_URL: Server URL
	PollingInterval    string // KEYHELP_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // KEYHELP_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // KEYHELP_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *KeyhelpConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.APIKey != "" {
		cfg.APIKey = c.APIKey
	}
	if c.BaseURL != "" {
		cfg.BaseURL = c.BaseURL
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *KeyhelpConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"keyhelp\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "KEYHELP_API_KEY":
			c.APIKey = val
		case "baseURL", "KEYHELP_BASE_URL":
			c.BaseURL = val
		case "pollingInterval", "KEYHELP_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "KEYHELP_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "KEYHELP_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"keyhelp\"", key)
		}
	}
	return nil
}
