// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/dnshomede"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// DnshomedeConfig holds configuration for the "dnshomede" DNS provider (dnsHome.de)
// See https://www.dnshome.de
type DnshomedeConfig struct {
	PollingInterval    string // DNSHOMEDE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 1200)
	PropagationTimeout string // DNSHOMEDE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 2)
	SequenceInterval   string // DNSHOMEDE_SEQUENCE_INTERVAL: Time between sequential requests in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *DnshomedeConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.SequenceInterval != "" {
		v, err := strconv.Atoi(c.SequenceInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"sequenceInterval\": %w", err)
		}
		cfg.SequenceInterval = time.Duration(v) * time.Second
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *DnshomedeConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"dnshomede\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "pollingInterval", "DNSHOMEDE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "DNSHOMEDE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "sequenceInterval", "DNSHOMEDE_SEQUENCE_INTERVAL":
			c.SequenceInterval = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"dnshomede\"", key)
		}
	}
	return nil
}
