// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// StackpathConfig holds configuration for the "stackpath" DNS provider (Stackpath)
// See https://www.stackpath.com/
type StackpathConfig struct {
	ClientID           string // STACKPATH_CLIENT_ID: Client ID
	ClientSecret       string // STACKPATH_CLIENT_SECRET: Client secret
	StackID            string // STACKPATH_STACK_ID: Stack ID
	PollingInterval    string // STACKPATH_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // STACKPATH_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // STACKPATH_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *StackpathConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.ClientID != "" {
		m["STACKPATH_CLIENT_ID"] = c.ClientID
	}
	if c.ClientSecret != "" {
		m["STACKPATH_CLIENT_SECRET"] = c.ClientSecret
	}
	if c.StackID != "" {
		m["STACKPATH_STACK_ID"] = c.StackID
	}
	if c.PollingInterval != "" {
		m["STACKPATH_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["STACKPATH_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["STACKPATH_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *StackpathConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"stackpath\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "clientID", "STACKPATH_CLIENT_ID":
			c.ClientID = val
		case "clientSecret", "STACKPATH_CLIENT_SECRET":
			c.ClientSecret = val
		case "stackID", "STACKPATH_STACK_ID":
			c.StackID = val
		case "pollingInterval", "STACKPATH_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "STACKPATH_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "STACKPATH_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"stackpath\"", key)
		}
	}
	return nil
}
