// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// LiaraConfig holds configuration for the "liara" DNS provider (Liara)
// See https://liara.ir
type LiaraConfig struct {
	APIKey             string // LIARA_API_KEY: The API key
	HTTPTimeout        string // LIARA_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // LIARA_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // LIARA_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TeamID             string // LIARA_TEAM_ID: The team ID to access services in a team
	TTL                string // LIARA_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 3600)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *LiaraConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.APIKey != "" {
		m["LIARA_API_KEY"] = c.APIKey
	}
	if c.HTTPTimeout != "" {
		m["LIARA_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["LIARA_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["LIARA_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TeamID != "" {
		m["LIARA_TEAM_ID"] = c.TeamID
	}
	if c.TTL != "" {
		m["LIARA_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *LiaraConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"liara\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiKey", "LIARA_API_KEY":
			c.APIKey = val
		case "httpTimeout", "LIARA_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "LIARA_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "LIARA_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "teamID", "LIARA_TEAM_ID":
			c.TeamID = val
		case "ttl", "LIARA_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"liara\"", key)
		}
	}
	return nil
}
