// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/volcengine"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// VolcengineConfig holds configuration for the "volcengine" DNS provider (Volcano Engine/火山引擎)
// See https://www.volcengine.com/
type VolcengineConfig struct {
	Accesskey          string // VOLC_ACCESSKEY: Access Key ID (AK)
	Secretkey          string // VOLC_SECRETKEY: Secret Access Key (SK)
	Host               string // VOLC_HOST: API host
	HTTPTimeout        string // VOLC_HTTP_TIMEOUT: API request timeout in seconds (Default: 15)
	PollingInterval    string // VOLC_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 10)
	PropagationTimeout string // VOLC_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 240)
	Region             string // VOLC_REGION: Region
	Scheme             string // VOLC_SCHEME: API scheme
	TTL                string // VOLC_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *VolcengineConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Accesskey != "" {
		cfg.AccessKey = c.Accesskey
	}
	if c.Secretkey != "" {
		cfg.SecretKey = c.Secretkey
	}
	if c.Host != "" {
		cfg.Host = c.Host
	}
	if c.HTTPTimeout != "" {
		v, err := strconv.Atoi(c.HTTPTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"httpTimeout\": %w", err)
		}
		cfg.HTTPTimeout = time.Duration(v) * time.Second
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.Region != "" {
		cfg.Region = c.Region
	}
	if c.Scheme != "" {
		cfg.Scheme = c.Scheme
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *VolcengineConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"volcengine\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accesskey", "VOLC_ACCESSKEY":
			c.Accesskey = val
		case "secretkey", "VOLC_SECRETKEY":
			c.Secretkey = val
		case "host", "VOLC_HOST":
			c.Host = val
		case "httpTimeout", "VOLC_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "VOLC_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "VOLC_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "region", "VOLC_REGION":
			c.Region = val
		case "scheme", "VOLC_SCHEME":
			c.Scheme = val
		case "ttl", "VOLC_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"volcengine\"", key)
		}
	}
	return nil
}
