// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/alidns"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AlidnsConfig holds configuration for the "alidns" DNS provider (Alibaba Cloud DNS)
// See https://www.alibabacloud.com/product/dns
type AlidnsConfig struct {
	AccessKey          string // ALICLOUD_ACCESS_KEY: Access key ID
	RAMRole            string // ALICLOUD_RAM_ROLE: Your instance RAM role (https://www.alibabacloud.com/help/en/ecs/user-guide/attach-an-instance-ram-role-to-an-ecs-instance)
	SecretKey          string // ALICLOUD_SECRET_KEY: Access Key secret
	SecurityToken      string // ALICLOUD_SECURITY_TOKEN: STS Security Token (optional)
	HTTPTimeout        string // ALICLOUD_HTTP_TIMEOUT: API request timeout in seconds (Default: 10)
	Line               string // ALICLOUD_LINE: Line (Default: default)
	PollingInterval    string // ALICLOUD_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // ALICLOUD_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	RegionID           string // ALICLOUD_REGION_ID: Region ID (Default: cn-hangzhou)
	TTL                string // ALICLOUD_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 600)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *AlidnsConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.AccessKey != "" {
		cfg.APIKey = c.AccessKey
	}
	if c.RAMRole != "" {
		cfg.RAMRole = c.RAMRole
	}
	if c.SecretKey != "" {
		cfg.SecretKey = c.SecretKey
	}
	if c.SecurityToken != "" {
		cfg.SecurityToken = c.SecurityToken
	}
	if c.HTTPTimeout != "" {
		v, err := strconv.Atoi(c.HTTPTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"httpTimeout\": %w", err)
		}
		cfg.HTTPTimeout = time.Duration(v) * time.Second
	}
	if c.Line != "" {
		cfg.Line = c.Line
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.RegionID != "" {
		cfg.RegionID = c.RegionID
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AlidnsConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"alidns\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "accessKey", "ALICLOUD_ACCESS_KEY":
			c.AccessKey = val
		case "ramRole", "ALICLOUD_RAM_ROLE":
			c.RAMRole = val
		case "secretKey", "ALICLOUD_SECRET_KEY":
			c.SecretKey = val
		case "securityToken", "ALICLOUD_SECURITY_TOKEN":
			c.SecurityToken = val
		case "httpTimeout", "ALICLOUD_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "line", "ALICLOUD_LINE":
			c.Line = val
		case "pollingInterval", "ALICLOUD_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "ALICLOUD_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "regionID", "ALICLOUD_REGION_ID":
			c.RegionID = val
		case "ttl", "ALICLOUD_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"alidns\"", key)
		}
	}
	return nil
}
