// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AllinklConfig holds configuration for the "allinkl" DNS provider (all-inkl)
// See https://all-inkl.com
type AllinklConfig struct {
	InklLogin              string // ALL_INKL_LOGIN: KAS login
	InklPassword           string // ALL_INKL_PASSWORD: KAS password
	InklHTTPTimeout        string // ALL_INKL_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	InklPollingInterval    string // ALL_INKL_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	InklPropagationTimeout string // ALL_INKL_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *AllinklConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.InklLogin != "" {
		m["ALL_INKL_LOGIN"] = c.InklLogin
	}
	if c.InklPassword != "" {
		m["ALL_INKL_PASSWORD"] = c.InklPassword
	}
	if c.InklHTTPTimeout != "" {
		m["ALL_INKL_HTTP_TIMEOUT"] = c.InklHTTPTimeout
	}
	if c.InklPollingInterval != "" {
		m["ALL_INKL_POLLING_INTERVAL"] = c.InklPollingInterval
	}
	if c.InklPropagationTimeout != "" {
		m["ALL_INKL_PROPAGATION_TIMEOUT"] = c.InklPropagationTimeout
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AllinklConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"allinkl\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "inklLogin", "ALL_INKL_LOGIN":
			c.InklLogin = val
		case "inklPassword", "ALL_INKL_PASSWORD":
			c.InklPassword = val
		case "inklHTTPTimeout", "ALL_INKL_HTTP_TIMEOUT":
			c.InklHTTPTimeout = val
		case "inklPollingInterval", "ALL_INKL_POLLING_INTERVAL":
			c.InklPollingInterval = val
		case "inklPropagationTimeout", "ALL_INKL_PROPAGATION_TIMEOUT":
			c.InklPropagationTimeout = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"allinkl\"", key)
		}
	}
	return nil
}
