// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// LinodeConfig holds configuration for the "linode" DNS provider (Linode (v4))
// See https://www.linode.com/
type LinodeConfig struct {
	Token              string // LINODE_TOKEN: API token
	HTTPTimeout        string // LINODE_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // LINODE_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 15)
	PropagationTimeout string // LINODE_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 120)
	TTL                string // LINODE_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *LinodeConfig) envVars() map[string]string {
	m := make(map[string]string, 5)
	if c.Token != "" {
		m["LINODE_TOKEN"] = c.Token
	}
	if c.HTTPTimeout != "" {
		m["LINODE_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["LINODE_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["LINODE_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["LINODE_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *LinodeConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"linode\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "token", "LINODE_TOKEN":
			c.Token = val
		case "httpTimeout", "LINODE_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "LINODE_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "LINODE_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "LINODE_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"linode\"", key)
		}
	}
	return nil
}
