// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// Conohav3Config holds configuration for the "conohav3" DNS provider (ConoHa v3)
// See https://www.conoha.jp/
type Conohav3Config struct {
	APIPassword        string // CONOHAV3_API_PASSWORD: The API password
	APIUserID          string // CONOHAV3_API_USER_ID: The API user ID
	TenantID           string // CONOHAV3_TENANT_ID: Tenant ID
	HTTPTimeout        string // CONOHAV3_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PollingInterval    string // CONOHAV3_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // CONOHAV3_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	Region             string // CONOHAV3_REGION: The region (Default: c3j1)
	TTL                string // CONOHAV3_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *Conohav3Config) envVars() map[string]string {
	m := make(map[string]string, 8)
	if c.APIPassword != "" {
		m["CONOHAV3_API_PASSWORD"] = c.APIPassword
	}
	if c.APIUserID != "" {
		m["CONOHAV3_API_USER_ID"] = c.APIUserID
	}
	if c.TenantID != "" {
		m["CONOHAV3_TENANT_ID"] = c.TenantID
	}
	if c.HTTPTimeout != "" {
		m["CONOHAV3_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PollingInterval != "" {
		m["CONOHAV3_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["CONOHAV3_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.Region != "" {
		m["CONOHAV3_REGION"] = c.Region
	}
	if c.TTL != "" {
		m["CONOHAV3_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *Conohav3Config) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"conohav3\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "apiPassword", "CONOHAV3_API_PASSWORD":
			c.APIPassword = val
		case "apiUserID", "CONOHAV3_API_USER_ID":
			c.APIUserID = val
		case "tenantID", "CONOHAV3_TENANT_ID":
			c.TenantID = val
		case "httpTimeout", "CONOHAV3_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pollingInterval", "CONOHAV3_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "CONOHAV3_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "region", "CONOHAV3_REGION":
			c.Region = val
		case "ttl", "CONOHAV3_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"conohav3\"", key)
		}
	}
	return nil
}
