// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"

	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// AzionConfig holds configuration for the "azion" DNS provider (Azion)
// See https://www.azion.com/en/products/edge-dns/
type AzionConfig struct {
	PersonalToken      string // AZION_PERSONAL_TOKEN: Your Azion personal token.
	HTTPTimeout        string // AZION_HTTP_TIMEOUT: API request timeout in seconds (Default: 30)
	PageSize           string // AZION_PAGE_SIZE: The page size for the API request (Default: 50)
	PollingInterval    string // AZION_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // AZION_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // AZION_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// envVars returns the lego environment variables for the populated (non-empty) fields
func (c *AzionConfig) envVars() map[string]string {
	m := make(map[string]string, 6)
	if c.PersonalToken != "" {
		m["AZION_PERSONAL_TOKEN"] = c.PersonalToken
	}
	if c.HTTPTimeout != "" {
		m["AZION_HTTP_TIMEOUT"] = c.HTTPTimeout
	}
	if c.PageSize != "" {
		m["AZION_PAGE_SIZE"] = c.PageSize
	}
	if c.PollingInterval != "" {
		m["AZION_POLLING_INTERVAL"] = c.PollingInterval
	}
	if c.PropagationTimeout != "" {
		m["AZION_PROPAGATION_TIMEOUT"] = c.PropagationTimeout
	}
	if c.TTL != "" {
		m["AZION_TTL"] = c.TTL
	}
	return m
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *AzionConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"azion\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "personalToken", "AZION_PERSONAL_TOKEN":
			c.PersonalToken = val
		case "httpTimeout", "AZION_HTTP_TIMEOUT":
			c.HTTPTimeout = val
		case "pageSize", "AZION_PAGE_SIZE":
			c.PageSize = val
		case "pollingInterval", "AZION_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "AZION_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "AZION_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"azion\"", key)
		}
	}
	return nil
}
