// Code generated by gen-dns-providers; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"
	"time"

	"github.com/go-acme/lego/v4/challenge"
	prov "github.com/go-acme/lego/v4/providers/dns/ispconfig"
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

// IspconfigConfig holds configuration for the "ispconfig" DNS provider (ISPConfig 3)
// See https://www.ispconfig.org/
type IspconfigConfig struct {
	Password           string // ISPCONFIG_PASSWORD: Password
	ServerURL          string // ISPCONFIG_SERVER_URL: Server URL
	Username           string // ISPCONFIG_USERNAME: Username
	InsecureSkipVerify string // ISPCONFIG_INSECURE_SKIP_VERIFY: Whether to verify the API certificate
	PollingInterval    string // ISPCONFIG_POLLING_INTERVAL: Time between DNS propagation check in seconds (Default: 2)
	PropagationTimeout string // ISPCONFIG_PROPAGATION_TIMEOUT: Maximum waiting time for DNS propagation in seconds (Default: 60)
	TTL                string // ISPCONFIG_TTL: The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)
}

// newProvider builds the lego DNS challenge provider using strong types
// Credentials are passed directly to lego and never written to the process environment
func (c *IspconfigConfig) newProvider() (challenge.Provider, error) {
	cfg := prov.NewDefaultConfig()
	if c.Password != "" {
		cfg.Password = c.Password
	}
	if c.ServerURL != "" {
		cfg.ServerURL = c.ServerURL
	}
	if c.Username != "" {
		cfg.Username = c.Username
	}
	if c.InsecureSkipVerify != "" {
		v, err := strconv.ParseBool(c.InsecureSkipVerify)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"insecureSkipVerify\": %w", err)
		}
		cfg.InsecureSkipVerify = v
	}
	if c.PollingInterval != "" {
		v, err := strconv.Atoi(c.PollingInterval)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"pollingInterval\": %w", err)
		}
		cfg.PollingInterval = time.Duration(v) * time.Second
	}
	if c.PropagationTimeout != "" {
		v, err := strconv.Atoi(c.PropagationTimeout)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"propagationTimeout\": %w", err)
		}
		cfg.PropagationTimeout = time.Duration(v) * time.Second
	}
	if c.TTL != "" {
		v, err := strconv.Atoi(c.TTL)
		if err != nil {
			return nil, fmt.Errorf("invalid value for \"ttl\": %w", err)
		}
		cfg.TTL = v
	}
	return prov.NewDNSProviderConfig(cfg)
}

// UnmarshalYAML decodes the provider credentials
// It accepts the normalized name, the raw lego environment variable, and documented aliases; unknown keys error
func (c *IspconfigConfig) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("dnsCredentials for DNS provider \"ispconfig\" must be a map")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		var key string
		err := value.Content[i].Decode(&key)
		if err != nil {
			return err
		}
		var val string
		err = value.Content[i+1].Decode(&val)
		if err != nil {
			return err
		}
		switch key {
		case "password", "ISPCONFIG_PASSWORD":
			c.Password = val
		case "serverURL", "ISPCONFIG_SERVER_URL":
			c.ServerURL = val
		case "username", "ISPCONFIG_USERNAME":
			c.Username = val
		case "insecureSkipVerify", "ISPCONFIG_INSECURE_SKIP_VERIFY":
			c.InsecureSkipVerify = val
		case "pollingInterval", "ISPCONFIG_POLLING_INTERVAL":
			c.PollingInterval = val
		case "propagationTimeout", "ISPCONFIG_PROPAGATION_TIMEOUT":
			c.PropagationTimeout = val
		case "ttl", "ISPCONFIG_TTL":
			c.TTL = val
		default:
			return fmt.Errorf("unknown credential key %q for DNS provider \"ispconfig\"", key)
		}
	}
	return nil
}
